### ISSUE TITLE
Run execute_shell in same environment as execute_python_code

### ISSUE THREAD

**Issue by Wladastic** [Significant-Gravitas/AutoGPT#1299]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

My Auto-gpt keeps trying to install pip packages to execute the python3 scripts it builds.
But the python shells are executed in a docker container and the shell is executed locally.

This results in auto-gpt trying to resolve why it cannot install the packages it need and getting stuck in a weird loop where it breaks out by using other agents again and does weird stuff on it's own or keeps triggering speak.py in the background with a mix of gibberish and stuff like "run specified file with python python version set version set view option set output log path path to verbose log, no proxy proxy"
It sounds funny actually 

### Your prompt 📝

```yaml
# Paste your prompt here
```

**Comment by Pwuts** [comment]
Please include your log and reopen.

**Comment by Boostrix** [comment]
>  the python shells are executed in a docker container and the shell is executed locally.

would not have closed that yet, that's actually a valid issue: there is a discrepancy here if execute_shell and execute_python run in different environments, as explained by @valayDave here: https://github.com/Significant-Gravitas/Auto-GPT/issues/2987#issuecomment-1536929354

**Comment by Pwuts** [comment]
Related: #3541

**Comment by Boostrix** [comment]
not in favor of closing this one, pwuts introduced a "fridge" a while ago - maybe we need some notion of "attic" or "in a perfect world" or just label these "good first issue" please

**Comment by Pwuts** [comment]
> not in favor of closing this one, pwuts introduced a "fridge" a while ago - maybe we need some notion of "attic" or "in a perfect world" or just label these "good first issue" please

`fridge` is now also whitelisted from the stale monster. Because you know, things don't go stale in the fridge. :)

**Comment by kusuta012** [comment]
does this issue still persist
