### ISSUE TITLE
Change AI provider

### ISSUE THREAD

**Issue by windowsagent** [Significant-Gravitas/AutoGPT#2011]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Add a feature so that we can use custom API endpoints, or custom LLMs.

### Examples 🌈

Utilizing free endpoints like this:
https://api.pawan.krd/v1/chat/completions

### Motivation 🔦

Haven't been able to use AutoGPT as my free credits expired...

**Comment by yf007** [comment]
Please someone work on this.
It can cut crazy costs

**Comment by Tarolrr** [comment]
This issue was partially solved by the PR https://github.com/Significant-Gravitas/Auto-GPT/pull/2594 (it solves the OP's example).
Furthermore, it is already mentioned in #25, having long discussion on that topic. I would suggest to close this one as duplicate.
