### ISSUE TITLE
Implement Bing AI token for free use of Auto-GPT

### ISSUE THREAD

**Issue by infinit-X** [Significant-Gravitas/AutoGPT#3105]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

We can use auto GPT for free if we could use bing AI instead of openai api key. There are number of projects which are using reverse engineered bing AI so i would suggest to look on that.

**Comment by AndresCdo** [comment]
Please provide more information about it.

**Comment by DULPALAMAKUMBURA** [comment]
> Please provide more information about it.

Sure. Auto=GPT basically use GPT 4 for test generation, 3.5 for summarization and DAll-E for image generation but there are projects which are using Bing AI which is also based on GPT 4 for text generation and summarization, and they also use Bing image creator for image generation. But as Auto-GPT use openAI api key for all above, it uses tokens hence cost money.

You can refer these projects to have a more clearer idea. 

https://github.com/danny-avila/chatgpt-clone
https://github.com/acheong08/EdgeGPT

THX.

**Comment by xianzhisheng** [comment]
That's a great idea! For example, if I already have permission to use Bing Chat, can I use Bing as an interface in AutoGPT？
However, at present, Bing Chat does not provide an API interface, even if we reverse call the web page to carry out the conversation, it is difficult to achieve the effect of the OpenAI interface, and Bing also has a limit on the number of conversations.

**Comment by DULPALAMAKUMBURA** [comment]
> That's a great idea! For example, if I already have permission to use Bing Chat, can I use Bing as an interface in AutoGPT？ However, at present, Bing Chat does not provide an API interface, even if we reverse call the web page to carry out the conversation, it is difficult to achieve the effect of the OpenAI interface, and Bing also has a limit on the number of conversations.

There is a workaround for this actually, we can use the Bing _U cookie value to connect and take Bing AI response and chatgpt-clone project above I cited has a jailbroken mode for BingAI chat which disables the chat limit and Microsoft limitations as well. Also we can use Chatgpt browser client which is free and also using GPT 3.5 turbo model with the same reverse engineering using access token from https://chat.openai.com/api/auth/session

**Comment by arikw** [comment]
Just found out about https://github.com/gravelBridge/AutoGPT-BingAI
Haven't tried it yet.

**Comment by anonhostpi** [comment]
Be wary when automating GPT through 3rd party tools. This feature would very likely violate _Bing's ToS_.

With that said, this would probably be better as a plugin, but even then, that's a liability risk.

You have to remember that actual businesses are looking to use this tool.

Make sure your feature requests are legal.

**Comment by albertony-ustc** [comment]
> 刚知道https://github.com/gravelBridge/AutoGPT-BingAI 还没试过。

刚知道+1，朋友有测试过吗

**Comment by cowwoc** [comment]
We need a way to run AutoGPT without an OpenAI API key, just using Bing Chat. Do you plan to provide such an override?

**Comment by katmai** [comment]
> We need a way to run AutoGPT without an OpenAI API key, just using Bing Chat. Do you plan to provide such an override?

bing is based on openAI.

**Comment by cowwoc** [comment]
@katmai Sure, but it does not require an API key. I expect to be able to use https://github.com/gravelBridge/AutoGPT-BingAI without an OpenAI API key.
