### ISSUE TITLE
Separate the Plugin interface into multiple different interfaces for different types of plugins 

### ISSUE THREAD

**Issue by ntindle** [Significant-Gravitas/AutoGPT#3652]
Some plugins should only support swapping the Memory, LLM, or UI out. Others may only want to add commands. 

We should support these plugins in a way that doesn't require them to update constantly, saying they do or don't support x, y, or z. 

The following steps  need to be taken to do this:
- [ ] Split the Plugin interface into logical sections of (at minimum)
    - [x] #3650
    - [x] #3655
    - [ ] Commands
    - [ ] prompt generator
    - [ ] Embeddings
    - [ ] Experience Interfaces
    - [ ] Text to Speech

	Longer term:
    - [ ] Plugin Manager
    - [ ] The workspace -> Exists
    - [ ] Config manager
    - [ ] resource manager

- [ ] Publish these updates to the Plugin Template
- [ ] Update all plugins to use these new structures
- [x] #3654

**Comment by Boostrix** [comment]
regarding commands: it would be useful if there was support for an optional step to prepare commands, but also another step to review the prepared command before it's getting executed. Some users keep seeing nano/vim being used, despite "non-interactive" being a part of their constraints/description.
And in fact, a number of constraints seem to be regularly violated. Thus, splitting command execution into two more stages would help streamline the process:

- preparing the actual command to provide surrounding context, as per: https://github.com/Significant-Gravitas/Auto-GPT/issues/2987#issuecomment-1531131136
- retrieving the prepared command for review (to check for constraint violations)
- actually executing the command

**Comment by Wladastic** [comment]
As a web gui is also being built, we could try adding a setup section where you could also just click and toggle the plugins

**Comment by Boostrix** [comment]
this seems to be work in progress, according to the logs, commands are going to be moved into plugins and there are going to be ways to enable/disable those individually. 

And let's keep in mind that plugin support is a fairly recent addition: https://github.com/Significant-Gravitas/Auto-GPT/pull/757

What seems to be missing in right now is a capabiility for plugins to provide hooks so that these can be separately configured/set up using a holistic interface - at the very least, we need some form get/set interface for key/value pairs, analogous to git.

Apart from dealing with plugin dependencies (#3068), recent efforts are seemingly focused on providing means to explicitly enable/disable individual commands and plugins: #3461

- #3688
- #3667
- #3707

**Comment by anonhostpi** [comment]
This should definitely be implemented. Inversion of Control is always a good practice. This would allow the community/end-user to hotswap parts of the codebase with their own implementations. I think the repository should aim to try to achieve this with every part of AutoGPT that is hard-coded into it.

**Comment by anonhostpi** [comment]
I absolutely love this idea @ntindle

**Comment by p-i-** [comment]
References PR #2642

**Comment by anonhostpi** [comment]
So, I've been reviewing all of the repositories Issues and PRs, as well as tracking some of the progress of the re-arch, and I think this PR addresses issues with this repository's IoC. I started a discussion in GH discussions that addresses poor IoC. Given what I've seen on the 200+ issues I've reviewed over the last 2 days, I think the repo could benefit from the conversation: https://github.com/Significant-Gravitas/Auto-GPT/discussions/3856

**Comment by anonhostpi** [comment]
needs the https://github.com/Significant-Gravitas/Auto-GPT/labels/re-arch label

**Comment by SalesforceBobLightning** [comment]
You mentioned updating the plugins, I assume this is 1st party ones, are you also going to update the 3rd party ones too?

**Comment by Wladastic** [comment]
> You mentioned updating the plugins, I assume this is 1st party ones, are you also going to update the 3rd party ones too?

third party plugins are out of our reach, each first party plugin is mostly edited by the original creators and they are mostly responsible, otherwise the plugins are removed from first party.

**Comment by Pwuts** [comment]
Let's say this is more or less completed by #7054
