### ISSUE TITLE
Make Installing Plugins Easier

### ISSUE THREAD

**Issue by ntindle** [Significant-Gravitas/AutoGPT#3654]
Plugins currently need to be in a zip file to load. 

That experience is terrible.

We should make the plugins repo a git submodule of this one and allow only that repo to load without being zipped. 
We should still require outside plugins to be zipped so that the behavior may not change for the user without their expectation.

We also considered loading plugins from Pypi by name, but we deemed that too dangerous for end users.

Tasks:
- [ ] Update plugin loading script to support loading plugins from a file
- [ ] Update `--install-plugin-deps` to also install a `requirements.txt` from the submodule
- [ ] Update the repo to have the plugins repo as a submodule
- [ ] Update the plugin loading script to only load the folder if it is from our repo (maybe)
- [ ] Setup a pipeline to support updating the submodule every release (maybe)
- [ ] Update the documentation to show this in the 
    - Install guide
    - plugin guide
    - plugin repo
    - wiki

**Comment by h4ck3rk3y** [comment]
Hey @ntindle! I empathize with this issue. I am the maintainer of https://github.com/kurtosis-tech/kurtosis/autogpt-package that makes getting started with plugins and custom backends a lot easier than the current README. For now adding `ALLOWLISTED_PLUGINS=plugin_name` will download and install the right plugin automatically!

~Note for the plugin flow I am currently using a self hosted image of AutoGPT as I was waiting for a new release~ I see the new release is out. Will move towards using the 0.3.0 image.

I see you have already ⭐ our project! Let me know what you can think and if you are open to make `Kurtosis` a native way to launch AutoGPT in the README.

Great work with this project :-)

**Comment by katmai** [comment]
i know this may be a stupid idea but i'm gonna write it anyway. any chance we can get a sort of template for a simple plugin that demonstrates a little of the functionality? like a hello world or something basic that we can clone and try to extend if we're really really at the beginning with this.

**Comment by VPelt** [comment]
https://github.com/Significant-Gravitas/Auto-GPT/pull/4546

If anyone wants to provide feedback please let me know what i can do to get this merged

**Comment by erik-megarad** [comment]
I totally missed this issue, I apologize. Here is my implementation https://github.com/Significant-Gravitas/Auto-GPT/pull/4548/files

**Comment by Metashipx** [comment]
> Hey @ntindle! I empathize with this issue. I am the maintainer of https://github.com/kurtosis-tech/kurtosis/autogpt-package that makes getting started with plugins and custom backends a lot easier than the current README. For now adding `ALLOWLISTED_PLUGINS=plugin_name` will download and install the right plugin automatically!
> 
> ~Note for the plugin flow I am currently using a self hosted image of AutoGPT as I was waiting for a new release~ I see the new release is out. Will move towards using the 0.3.0 image.
> 
> I see you have already ⭐'d our project! Let me know what you can think and if you are open to make `Kurtosis` a native way to launch AutoGPT in the README.
> 
> Great work with this project :-)


Hi!  Total newb here, 
I have installed the plugins a few weeks ago, returned today and reinstalled the latest Auto GPT 0.4.3 just now. 
Just created a .yml file for the plugins because it wasn't created. I entered the .env file and added the plugins that 
i want in the allow list... but still nothing is working properly. 

I still get prompted to install the plugins when I run.bat and I am not sure how to fix this issue yet. 
I would appreciate any help
thank you!!
p.s 
The link to the repo you suggested is broken

**Comment by h4ck3rk3y** [comment]
@Metashipx good find - here's the actual link https://github.com/kurtosis-tech/autogpt-package. Let me know how it goes!
