### ISSUE TITLE
Github hook for non-code PRs ?

### ISSUE THREAD

**Issue by Boostrix** [Significant-Gravitas/AutoGPT#3834]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

There are a few non-code PRs (usually documentation or config file changes). 

These can probably be labelled automatically by using a whitelist of file names / paths and label those as "non-code", to make reviewing those a little easier. 

A bunch of PRs are merely documenting existing options by adding new/better comments.
Obviously, in the case of config changes, having a unit test in place to run different configs and compare the output, would make sense

But overall, that would probably make it easier to get non-code PRs reviewed/committed...

There is probably no need to treat those with the same caution as PRs that touch actual code, as long as they don't change any defaults ?

What do you think ?

**Comment by Boostrix** [comment]
I am aware of the ongoing re-arch effort, but labels will help categorize PRs into code vs. non-code - to review/integrate and approve a non-code PR, you don't exactly need the same sort of skills (aka the devs), which is the whole point.

There are a bunch of non-code PRs that should conceptually not require the "core team" to review those (again, docs + config files).
If in doubt, these could be committed to a separate branch by reviewers to help the core team while they're busy.
Once they're "back", the corresponding branch could be looked at next.

The nature of non-code changes makes it easier to integrate those afterwards with actual code changes.

**Comment by Pwuts** [comment]
Going to add `project management` to the label whitelist so it doesn't get staled
