### ISSUE TITLE
Networking binding issue with auto_gpt_default

### ISSUE THREAD

**Issue by Demon-tk** [Significant-Gravitas/AutoGPT#3975]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of Auto-GPT are you using?

Stable (branch)

### GPT-3 or GPT-4?

GPT-4

### Steps to reproduce 🕹

Documented install steps.

Have tried either Portainer and cmd, have not tried building from git

### Current behavior 😯

failed to deploy a stack: Network auto_gpt_default Creating Network auto_gpt_default Created Container auto_gpt-redis-1 Creating Container auto_gpt-redis-1 Created Container auto_gpt-redis-1 Starting Error response from daemon: failed to create endpoint auto_gpt-redis-1 on network auto_gpt_default: failed to add the host (veth88f056b) <=> sandbox (vethba97931) pair interfaces: operation not supported 

### Expected behavior 🤔

Would be able to bridge the network adapters and access internet. 

### Your prompt 📝

N/a

### Your Logs 📒

```
failed to deploy a stack: Network auto_gpt_default Creating Network auto_gpt_default Created Container auto_gpt-redis-1 Creating Container auto_gpt-redis-1 Created Container auto_gpt-redis-1 Starting Error response from daemon: failed to create endpoint auto_gpt-redis-1 on network auto_gpt_default: failed to add the host (veth88f056b) <=> sandbox (vethba97931) pair interfaces: operation not supported 
```

```
❯ sudo docker version
Client:
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.20.4
 Git commit:        bc4487a59e
 Built:             Tue May  2 21:53:09 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       94d3ad69cc
  Built:            Tue May  2 21:53:09 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.0
  GitCommit:        1fbd70374134b891f97ce19c70b6e50c7b9f4e0d.m
 runc:
  Version:          1.1.7
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```
❯ uname -r
6.2.13-arch1-1
```

**Comment by Git-Discord** [comment]
ntindle: can you tell us more about your setup?

 - Posted By Discord User: ntindle Using The Git-Discord Bot From AutoGPT's Discord Server
