### ISSUE TITLE
How to customize the request URL? Because my GPT-4 key must use the URL of a third-party reverse proxy, otherwise it cannot be used.

### ISSUE THREAD

**Issue by SunnyGPT** [Significant-Gravitas/AutoGPT#4071]
How to customize the request URL? Because my GPT-4 key must use the URL of a third-party reverse proxy, otherwise it cannot be used, for example:

original: https://api.openai.com/v1/chat/completions
Now: https://api.openai-365pro.com/v1/chat/completions

But I only saw in the configuration file that the API Key can be modified, and I didn't find how to modify the URL.

**Comment by 14790897** [comment]
Can you tell me what file I should modify to change the URL?

**Comment by SunnyGPT** [comment]
> Can you tell me what file I should modify to change the URL?

$10. ok?
