### ISSUE TITLE
Command browse_website returned: Error: unknown error: Chrome failed to start: exited abnormally.

### ISSUE THREAD

**Issue by claytoncohn** [Significant-Gravitas/AutoGPT#4342]
I'm currently using the Docker Auto-GPT implementation, but every time it tries to access the web, I get the following error:

```SYSTEM:  Command browse_website returned: Error: unknown error: Chrome failed to start: exited abnormally.```

Pursuant to the docs, I have both my Google Search Engine ID and Google API keys in the .env file and headers are set to default (false).

I'm running it from the command line via the following command:

```docker-compose run --rm  auto-gpt --gpt3only```

**Comment by pdennis33** [comment]
I'm seeing the same behavior on mine, running in docker

**Comment by echinelli** [comment]
same error here

**Comment by tiangao88** [comment]
same error and I tried all 3 browsers. Also running docker.

**Comment by martinpacesa** [comment]
Same error on Mac

**Comment by echinelli** [comment]
worked with firefox. Max os

**Comment by KlnCdc** [comment]
> I'm currently using the Docker Auto-GPT implementation, but every time it tries to access the web, I get the following error:
> 
> `SYSTEM: Command browse_website returned: Error: unknown error: Chrome failed to start: exited abnormally.`
> 
> Pursuant to the docs, I have both my Google Search Engine ID and Google API keys in the .env file and headers are set to default (false).
> 
> I'm running it from the command line via the following command:
> 
> `docker-compose run --rm auto-gpt --gpt3only`

Hello,

I have the same problem but according to the doc you must HEADLESS_BROWSER=True (https://docs.agpt.co/setup/#run-with-docker) :

"Docker only supports headless browsing

Auto-GPT uses a browser in headless mode by default: HEADLESS_BROWSER=True. Please do not change this setting in combination with Docker, or Auto-GPT will crash."

<img width="707" alt="Capture d’écran 2023-05-27 à 21 12 57" src="https://github.com/Significant-Gravitas/Auto-GPT/assets/22118583/c99c7eb4-e731-4003-b4aa-875fa9220531">


Problen resolved ?

Ced

**Comment by claytoncohn** [comment]
Not for me. My headless browsing part is still commented out, so it is defaulting to true and still not working. I also tried uncommenting if for both true and false and still no luck.

**Comment by justinsane** [comment]
I'm experiencing this issue. Docker Auto-GPT, MacOS.

.env:

HEADLESS_BROWSER=True
USE_WEB_BROWSER=chrome

**Comment by justinsane** [comment]
I had a similar issue. Double check that your Chrome is updated and works.

**Comment by bhardwaj-priyank** [comment]
This has been a constant issue for days. tried multiple things as suggested [here](https://github.com/Significant-Gravitas/Auto-GPT/issues/1788) but nothing seems to work.

**Comment by x6888** [comment]
Please use the command: .\run.bat --browser-name firefox --continuous. Firefox is a fine choice. 运行的时候指定firefox浏览器就挺好的，我解决了。

**Comment by sreeshan90** [comment]
Had the same issue. Used the command below, seemed to work
`docker compose run --rm auto-gpt --gpt3only --browser-name firefox`

**Comment by hahacharlie** [comment]
Changed the `USE_WEB_BROWSER` option to `firefox` and appears to be working right now.

**Comment by teddybrine** [comment]
On MacOS and using Docker, chrome didn't work, will try firefox now

**Comment by AlmousaM** [comment]
> firefox

setting the browser to firefox in .env file solved the issue
<img width="902" alt="Screenshot 2023-10-04 at 2 40 20 PM" src="https://github.com/Significant-Gravitas/AutoGPT/assets/58348642/098f6699-8e4e-405f-9f5a-4756395e6b2a">

**Comment by guosoun** [comment]
I encountered the same error when using docker on MacOS.
