### ISSUE TITLE
Unexpected Hanged during execute_shell due to execute server daemon like 'uvicorn'!

### ISSUE THREAD

**Issue by seonghobae** [Significant-Gravitas/AutoGPT#4774]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Commands

### Describe your issue.

I put the prompt as `[Task] Using the system command git clone https://github.com/princeton-nlp/tree-of-thought-llm.git, develop a plan for creating a Python library in REST API format using FastAPI and Uvicorn to perform a Tree of Thought (ToT) initiated by Princeton University, and create the Python library according to the plan. [Note] To obtain a comprehensive and efficient solution to your planning process and development requirements, use Google and BingAI to obtain your solution in each iteration as much as possible.` in Auto-GPT with continuous mode. Auto-GPT runs with good conditions; however, Auto-GPT goes to hang because uvicorn is server daemon.

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/8172694/9340a4b4-ecf4-45bf-9049-9349f951701e)

**Comment by JoshJarabek7** [comment]
Mine as well, I've tried to remind it that it has to cancel twice with Uvicorn, but it fails to remember lol.
