### ISSUE TITLE
Run Auto-GPT Error 

### ISSUE THREAD

**Issue by GeorgevanGoethem** [Significant-Gravitas/AutoGPT#4800]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Hi, after following the steps of the youtube video 'How to Use AutoGPT - Complete Tutorial' from youtuber 'Howfinity' I came to a problem at the last step (I'm on windows btw). 

The video follows the exact same steps as this URL: 'https://docs.agpt.co/setup/#configuration'
The last step 'Run Auto-GPT'; if I put the command in powershell, I get the following error: 
'

't_module_details(mod_name, _Error)'

It says this at the end: 
 'ModuleNotFoundError: No module named 'autogpt.memory_item'

Can someone help me with this?

**Comment by GeorgevanGoethem** [comment]
I get this error: 


ModuleNotFoundError: No module named 'autogpt.memory_item'


Why does it say I don't have this autogpt.memory item

**Comment by bhushanxd25** [comment]
Same error i faced
