### ISSUE TITLE
Command read_file returned: Error: read file  failed: no such file or directory

### ISSUE THREAD

**Issue by thedreamakeem** [Significant-Gravitas/AutoGPT#4864]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Commands

### Describe your issue.

Currently running a prompt to generate lyrics for performing certain tasks.  after browsing web i get the response "CODEFLOWGPT THOUGHTS:  I should use the 'read_file' command to access the lyrics of 'Codiene' by Baby Mane that I previously saved to a file.
REASONING:  I saved the lyrics to a file, so I can use the 'read_file' command to retrieve them."

i don't think that the Agent actually saved/created to file, but it tries to read file anyways and it fails.
<img width="1439" alt="Screen Shot 2023-07-01 at 10 58 05 AM" src="https://github.com/Significant-Gravitas/Auto-GPT/assets/137110217/9c95325f-a42a-46b3-90fd-ee9080822d5a">

**Comment by PDGIII** [comment]
Having a similar issue using docker.

**Comment by Natsu-Dragneel-Aka** [comment]
Not sure havent checked the code yet but i think its not related to code but gpt response, rite now oly way to add restriction in promt like 'be sure to run command write file before read file.

**Comment by abdhass** [comment]
change the volume in docker to  - ./auto_gpt_workspace:/app/autogpt/workspace/auto_gpt_workspace (notice the addition of the directory workspace).

**Comment by eddyplural** [comment]
I had the same issue, this could do with being updated in the docker-compose.yml template on the setup.md file
