### ISSUE TITLE
Base url not working

### ISSUE THREAD

**Issue by TheNicolasDeveloper** [Significant-Gravitas/AutoGPT#4869]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I'm attempting to use an custom base url but it still connects to openai, throwing an error because the key is not valid for OpenAI.

### Upload Activity Log Content

2023-07-02 22:26:20,316 INFO Continuous Mode:  ENABLED 2023-07-02 22:26:20,423 INFO WARNING:  Continuous mode is not recommended. It is potentially dangerous and may cause your AI to run forever or carry out actions you would not usually authorise. Use at your own risk.

**Comment by JHubi1** [comment]
I have the same problem

**Comment by VectorZhao** [comment]
same

**Comment by TheNicolasDeveloper** [comment]
was this fixed yet?
