### ISSUE TITLE
Failed to update API costs: KeyError: 'gpt-3.5-turbo-0613'

### ISSUE THREAD

**Issue by thinkfuture** [Significant-Gravitas/AutoGPT#4887]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Commands

### Describe your issue.

Used to work fine - now I get this error and I can't figure out how to fix. Tried regen a new key and everything.

**Comment by Pwuts** [comment]
* When did you start having this issue?
* What version of Auto-GPT are you running?
* Can you post a log? Without a log or a stack trace, it's near impossible to debug an error.

**Comment by Bar-ship-it** [comment]
> I had the same issue when using docker environment.
> 
> Fixed it using `docker pull significantgravitas/auto-gpt` to have the latest image.

I'm having the exact same problem, and i'm not sure how to fix it

**Comment by cyrus-hawk** [comment]
> 

Have you run the command I mentioned in your terminal?

**Comment by cyrus-hawk** [comment]
> I'm having the exact same problem, and i'm not sure how to fix it

Have you run the command I mentioned in your terminal?

**Comment by Bar-ship-it** [comment]
No, I'm not sure how to implement it. I followed a couple of online guides for installing Auto-GPT on Windows 11 back in June, and I didn't get back to it until now due to work.

**Comment by cyrus-hawk** [comment]
> No, I'm not sure how to implement it. I followed a couple of online guides for installing Auto-GPT on Windows 11 back in June, and I didn't get back to it until now due to work.

There you are, things change fast. I am assuming you used the version that works with docker. If that's the case for you, you need to enter the following command in your terminal:
```
docker pull significantgravitas/auto-gpt
```

This should resolve the problem for you, hopefully.

**Comment by Bar-ship-it** [comment]
So I did not do it through docker, I had to install docker. IT seemed to run fine, but I received this error at the end:

TypeError: MessageHistory.per_cycle() missing 1 required positional argument: 'config'
