### ISSUE TITLE
browse_website command returns error 

### ISSUE THREAD

**Issue by Hotch-C** [Significant-Gravitas/AutoGPT#5073]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Commands

### Describe your issue.

Windows11 Home, running inside VertualBox.

When Auto-GPT tries the COMMAND = 'browse_website' ARGUEMENT = {url ...,
It returns the Error: expected string or byte-like object, got 'NoneType'
Both commands 'Google' and 'web_search' work correctly.

**Comment by Georgeroa73** [comment]
I am having the same issue!

**Comment by Georgeroa73** [comment]
NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://www.zillow.com/zebulon-nc/sold/', 'question': 'Can you provide recently sold homes in Zebulon, NC?'}
  Enter 'y' to authorise command, 'y -N' to run N continuous commands, 'n' to exit program, or enter feedback for RealEstateGPT...
  Asking user via keyboard...
Input:y
-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-=
SYSTEM:  Command browse_website returned: Error: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790

**Comment by Wiser2001** [comment]
Same issue here. Windows 10 running in PowerShell, both 3.5 and 4 (I have paid API)

**Comment by VectorZhao** [comment]
```
CRITICISM:  I should ensure that I thoroughly review each study and extract the most relevant information to provide accurate and concise summaries.
SPEAK:  To gather more detailed information and analyze the key findings, methodologies, and limitations of the identified studies on atmosphere retrieval of exoplanets, I will use the 'browse_website' command to access the websites of the papers.

NEXT ACTION:  COMMAND = browse_website ARGUMENTS = {'url': 'https://link.springer.com/article/10.1007/s10686-021-09791-z', 'question': ''}

SYSTEM:  Command browse_website returned: Error: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790
```

**Comment by gabeturner06** [comment]
I have the same issue, only I'm running MacOS, with OpenAI GPT-3.5. "Input:-=-=-=-=-=-=-= COMMAND AUTHORISED BY USER -=-=-=-=-=-=-= 
SYSTEM:  Command browse_website returned: Error: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790"

**Comment by otteb** [comment]
Any ideas on how to fix this? I have the same error on my MacOS M1 chip

**Comment by frenchdevartist** [comment]
It is the same for me with my Mac M1. No way to use Auto-GPT without fixing this issue.

**Comment by syrsteven** [comment]
The problem is in the file 'Auto-GPT/autogpt/commands/web_selenium.py' 
`
116        chromium_driver_path = Path("/usr/bin/chromedriver") 
`
Change ** "/usr/bin/chromedriver" ** to the path where you store your chromedriver.
However there is no chromedriver for version >114 on the official website, you can search for chromedriver115, chromedriver116 on Google.
Here is the download address of [chromedriver116](https://googlechromelabs.github.io/chrome-for-testing/#stable).

**Comment by Hotch-C** [comment]
> The problem is in the file 'Auto-GPT/autogpt/commands/web_selenium.py' `116 chromium_driver_path = Path("/usr/bin/chromedriver") ` Change ** "/usr/bin/chromedriver" ** to the path where you store your chromedriver. However there is no chromedriver for version >114 on the official website, you can search for chromedriver115, chromedriver116 on Google. Here is the download address of [chromedriver116](https://googlechromelabs.github.io/chrome-for-testing/#stable).

I like this answer, it was helpful and clearly explained for my layman brain to understand. But it didn't work for me.  GPT kept saying driver 116.0.5845.97 didn't exist, even though I changed the path to the driver location.  It seems that I've fixed my problem by changing the browser to Edge.  We'll see if that causes issues down the road.  It's pulling website info correctly so far.
