### ISSUE TITLE
pip install -r requirements.txt  error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by VASILEIOS1997** [Significant-Gravitas/AutoGPT#5083]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Can someone help my with that?

C:\Users\ΒΑΣΙΛΗΣ\autogpt\Auto-GPT>pip install -r requirements.txt
Collecting en-core-web-sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl (from -r requirements.txt (line 30))
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 12.8/12.8 MB 831.3 kB/s eta 0:00:00
Collecting auto-gpt-plugin-template@ git+https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template@0.1.0 (from -r requirements.txt (line 49))
  Cloning https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template (to revision 0.1.0) to c:\users\βασιλησ\appdata\local\temp\pip-install-n9j45xkp\auto-gpt-plugin-template_047467a1a51943f7ad1efd02200fdd73
  Running command git clone --filter=blob:none --quiet https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template 'C:\Users\ΒΑΣΙΛΗΣ\AppData\Local\Temp\pip-install-n9j45xkp\auto-gpt-plugin-template_047467a1a51943f7ad1efd02200fdd73'
  Running command git checkout -q 7612a14c629dc64ad870eee4d05850d60e1dd9ce
  Resolved https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template to commit 7612a14c629dc64ad870eee4d05850d60e1dd9ce
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting vcrpy@ git+https://github.com/Significant-Gravitas/vcrpy.git@master (from -r requirements.txt (line 71))
  Cloning https://github.com/Significant-Gravitas/vcrpy.git (to revision master) to c:\users\βασιλησ\appdata\local\temp\pip-install-n9j45xkp\vcrpy_59f7b04409ba466f8f705c15fd5c6754
  Running command git clone --filter=blob:none --quiet https://github.com/Significant-Gravitas/vcrpy.git 'C:\Users\ΒΑΣΙΛΗΣ\AppData\Local\Temp\pip-install-n9j45xkp\vcrpy_59f7b04409ba466f8f705c15fd5c6754'
  Resolved https://github.com/Significant-Gravitas/vcrpy.git to commit 2f6fa05ae3518b1c0e92e63c3d12ecf5cf82cd48
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "C:\Users\ΒΑΣΙΛΗΣ\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\ΒΑΣΙΛΗΣ\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ΒΑΣΙΛΗΣ\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ΒΑΣΙΛΗΣ\AppData\Local\Temp\pip-build-env-77z0a6_2\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ΒΑΣΙΛΗΣ\AppData\Local\Temp\pip-build-env-77z0a6_2\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\ΒΑΣΙΛΗΣ\AppData\Local\Temp\pip-build-env-77z0a6_2\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ΒΑΣΙΛΗΣ\AppData\Local\Temp\pip-build-env-77z0a6_2\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
        File "C:\Users\ΒΑΣΙΛΗΣ\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1253.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9f in position 23: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by MrMoshkovitz** [comment]
I have the exact same issue

**Comment by whale901004** [comment]
I have the exact same issue too!

**Comment by zjyhlrc** [comment]
have the same issue and can not solve it yet
