### ISSUE TITLE
# pip install -r requirements.txt......UnicodeDecodeError: 'cp949'

### ISSUE THREAD

**Issue by nameCDI** [Significant-Gravitas/AutoGPT#5086]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Anaconda3:

1) Create a virtual environment with Python version 3.11.4 and then execute the following commands:
   `git clone -b stable https://github.com/Significant-Gravitas/Auto-GPT.git`
   `cd Auto-GPT`
   `pip install -r requirements.txt`

2) Create a virtual environment with Python version 3.10.10 and follow the same steps as above.

In both cases, the same error occurred.

Also, I tried the following #4595, but the issue still persists:
  `pip install python-docx`
  `pip install docx`
[https://github.com/Significant-Gravitas/Auto-GPT/issues/4595#issuecomment-1581823548](url)

### Upload Error Log Content

(autogpt) PS C:\Auto-GPT> pip install -r .\requirements.txt
Collecting en-core-web-sm@ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl (from -r .\requirements.txt (line 30))
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 12.8/12.8 MB 6.0 MB/s eta 0:00:00
Collecting auto-gpt-plugin-template@ git+https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template@0.1.0 (from -r .\requirements.txt (line 47))
  Cloning https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template (to revision 0.1.0) to c:\users\master\appdata\local\temp\pip-install-bjtf0v_n\auto-gpt-plugin-template_1096e86631474123b56725fb685f5c5d
  Running command git clone --filter=blob:none --quiet https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template 'C:\Users\Master\AppData\Local\Temp\pip-install-bjtf0v_n\auto-gpt-plugin-template_1096e86631474123b56725fb685f5c5d'
  Running command git checkout -q 7612a14c629dc64ad870eee4d05850d60e1dd9ce
  Resolved https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template to commit 7612a14c629dc64ad870eee4d05850d60e1dd9ce
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting vcrpy@ git+https://github.com/Significant-Gravitas/vcrpy.git@master (from -r .\requirements.txt (line 69))
  Cloning https://github.com/Significant-Gravitas/vcrpy.git (to revision master) to c:\users\master\appdata\local\temp\pip-install-bjtf0v_n\vcrpy_3427cd82338f4c15a2f7a3213e2b4c16
  Running command git clone --filter=blob:none --quiet https://github.com/Significant-Gravitas/vcrpy.git 'C:\Users\Master\AppData\Local\Temp\pip-install-bjtf0v_n\vcrpy_3427cd82338f4c15a2f7a3213e2b4c16'
  Resolved https://github.com/Significant-Gravitas/vcrpy.git to commit 2f6fa05ae3518b1c0e92e63c3d12ecf5cf82cd48
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Master\anaconda3\envs\autogpt\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Master\anaconda3\envs\autogpt\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Master\anaconda3\envs\autogpt\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Master\AppData\Local\Temp\pip-build-env-0q_z35yk\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Master\AppData\Local\Temp\pip-build-env-0q_z35yk\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Master\AppData\Local\Temp\pip-build-env-0q_z35yk\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Master\AppData\Local\Temp\pip-build-env-0q_z35yk\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
      UnicodeDecodeError: 'cp949' codec can't decode byte 0xf0 in position 22: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by hodaya1995** [comment]
Try to go to control panel -> clock&region -> region -> adminastrtive tab -> change system locale -> change it to english and restart your computer.

**Comment by postmrtm** [comment]
same error as above after installing the latest release 0.47
tried installing requirements and getting the above.
my locale is english
