### ISSUE TITLE
 plugins_config.yaml 

### ISSUE THREAD

**Issue by adamwaks** [Significant-Gravitas/AutoGPT#5105]
### ⚠️ Search for existing issues first ⚠️

- [x] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

 plugins_config.yaml does not exist, creating base config.

**Comment by darkb0ts** [comment]
command  - `python -m autogpt --install-plugin-deps  `
`plugins_config.yaml` file located in the root directory of Auto-GPT

**Comment by Croie** [comment]
> 命令 -`python -m autogpt --install-plugin-deps ` `plugins_config.yaml`位于 Auto-GPT 根目录中的文件

This file is not seen in the auto-gpt root directory, and executing this command is invalid. python -m autogpt --install-plugin-deps does not have this command.
