### ISSUE TITLE
<div align="center"><img src="https://raw.githubusercontent.com/sindresorhus/refined-github/master/media/icon.svg" width="128"> </div>

### ISSUE THREAD

**Issue by DXv-3** [Significant-Gravitas/AutoGPT#5123]
<div align="center"><img src="https://raw.githubusercontent.com/sindresorhus/refined-github/master/media/icon.svg" width="128"> </div>

## 🌍 Enabling API-based features

Create and add a **Personal Access Token** in the [](#rgh-linkify-welcome-issue)extension’s options[](#rgh-linkify-welcome-issue) to ensure every feature works correctly.

## 🔔 Updates

You can follow this repository to know what each new release includes. Click "Watch" and then select "Releases"

## 🐛 Debugging

If any feature isn't working, [open the web console](https://documentation.concrete5.org/tutorials/how-open-browser-console-view-errors) and look for Refined GitHub-related errors.

## 🤝 Contributing

Help welcome! Have a look at the [open issues](https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+sort%3Areactions-%2B1-desc), especially [the easy ones](https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+sort%3Areactions-%2B1-desc). Check out [contributing.md](https://github.com/refined-github/refined-github/blob/main/contributing.md) for more info!

## 🥰 Giving thanks

If you enjoy Refined GitHub, you can sponsor its maintainer: [@fregante](https://github.com/sponsors/fregante).

## 🏢 GitHub Enterprise

If you're a GitHub Enterprise user, visit your Enterprise site, right-click on Refined GitHub's icon in the toolbar and select **Enable Refined GitHub on this domain.**

<img src="https://user-images.githubusercontent.com/1402241/32874388-e0c64150-cacc-11e7-9a50-eae3727fd3c2.png" width="331">

_Originally posted by @fregante in https://github.com/refined-github/refined-github/issues/3543_

**Comment by fregante** [comment]
this is spam

**Comment by Bentlybro** [comment]
Closed by bentlybro. Reason: due to spam
