### ISSUE TITLE
Bedrock support

### ISSUE THREAD

**Issue by maltaro88** [Significant-Gravitas/AutoGPT#5134]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Is somebody already working on Bedrock support?  Would be happy to contribute or start from scratch.

**Comment by ntindle** [comment]
Can you clarify “Bedrock”

**Comment by maltaro88** [comment]
https://aws.amazon.com/bedrock/

**Comment by zhangqibupt** [comment]
Would like to see that happen. 👍

**Comment by KoStard** [comment]
+1 on this

**Comment by jc1518** [comment]
+1
