### ISSUE TITLE
Docker file has missing gcc. Hence failed with errors when building psutil etc.

### ISSUE THREAD

**Issue by fr33wi11** [Significant-Gravitas/AutoGPT#5140]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

when running docker compose build auto-gpt results in error 
`{gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=595 -DPy_LIMITED_API=0x03060000 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -DPSUTIL_LINUX=1 -I/usr/local/include/python3.10 -c psutil/_psutil_common.c -o build/temp.linux-aarch64-cpython-310/psutil/_psutilcommon.o
50.73       psutil could not be installed from sources because gcc is not installed. Try running:
50.73         sudo apt-get install gcc python3-dev
50.73       error: command 'gcc' failed: No such file or directory
50.73       [end of output]
50.73
50.73   note: This error originates from a subprocess, and is likely not a problem with pip.
50.73   ERROR: Failed building wheel for psutil
50.73   Building wheel for readtime (setup.py): started
51.51   Building wheel for readtime (setup.py): finished with status 'done'
51.52   Created wheel for readtime: filename=readtime-3.0.0-py3-none-any.whl size=6775 sha256=16486b68aadb790690a8de84ee281c8b5b3e03f167f54e5e4dfb7569f2212763
51.52   Stored in directory: /tmp/pip-ephem-wheel-cache-6ijehq6/wheels/7f/7f/fd/3ad5a2ac4aff28279c36445a67b8033441a2bfa89fa57b5718
51.52 Successfully built python-docx pylatexenc auto-gpt-plugin-template vcrpy paginate readtime
51.52 Failed to build psutil
51.52 ERROR: Could not build wheels for psutil, which is required to install pyproject.toml-based projects
51.69 
51.69 [notice] A new release of pip is available: 23.0.1 -> 23.2.1
51.69 [notice] To update, run: pip install --upgrade pip}.

`

### Upload Activity Log Content

I have fixed this issue by updating docker file as below , by adding gcc

`# Install gcc and python3-dev for building certain Python packages
RUN apt-get update && apt-get install -y \
    gcc python3-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*`

Now if you guys are okay I can PR and provide my update. 

### Upload Error Log Content

[issue fix autogpt.txt](https://github.com/Significant-Gravitas/Auto-GPT/files/12424507/issue.fix.autogpt.txt)

**Comment by pharsi** [comment]
I can confirm this is happening, did you add this above line 41 (above sed related stuff)?

**Comment by SebastianP23** [comment]
exact same error for me but your file doenst seem to fix it on m end

**Comment by pharsi** [comment]
Where are you placing the changes in the Dockerfile exactly? The suggested fix works for me, can confirm

**Comment by SebastianP23** [comment]
My issue was from installing new OS too early. only took 3 days to figure that out.

**Comment by jdenson** [comment]
Had the same issue and this solution worked for me as well.

**Comment by spaceleafio** [comment]
needed this also on a mac M1 - thank you

**Comment by kverbeeck** [comment]
I updated the Dockerfile like below and that worked for me on a MacBook Air M1 >>>

`# 'dev' or 'release' container build
ARG BUILD_TYPE=dev

# Use an official Python base image from the Docker Hub
FROM python:3.10-slim AS autogpt-base

# Install browsers
RUN apt-get update && apt-get install -y \
    chromium-driver firefox-esr ca-certificates \
    && apt-get clean && rm -r /var/lib/apt/lists/*

# Install utilities
RUN apt-get update && apt-get install -y \
    curl jq wget git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install gcc and python3-dev for building certain Python packages
RUN apt-get update && apt-get install -y \
    gcc python3-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV PIP_NO_CACHE_DIR=yes \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

# Install the required python packages globally
ENV PATH="$PATH:/root/.local/bin"
COPY requirements.txt .

# Set the entrypoint
ENTRYPOINT ["python", "-m", "autogpt", "--install-plugin-deps"]

# dev build -> include everything
FROM autogpt-base as autogpt-dev
RUN pip install --no-cache-dir -r requirements.txt
WORKDIR /app
ONBUILD COPY . ./

# release build -> include bare minimum
FROM autogpt-base as autogpt-release
RUN sed -i '/Items below this point will not be included in the Docker Image/,$d' requirements.txt && \
	pip install --no-cache-dir -r requirements.txt
WORKDIR /app
ONBUILD COPY autogpt/ ./autogpt
ONBUILD COPY scripts/ ./scripts
ONBUILD COPY plugins/ ./plugins
ONBUILD COPY prompt_settings.yaml ./prompt_settings.yaml
ONBUILD RUN mkdir ./data

FROM autogpt-${BUILD_TYPE} AS auto-gpt`

Best regards
