### ISSUE TITLE
I have setup Google search API and Search ID, but I always get error.

### ISSUE THREAD

**Issue by cumtliang** [Significant-Gravitas/AutoGPT#5153]
### ⚠️ Search for existing issues first ⚠️

- [ ] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I have setup Google search API and Search ID, but I always get:
  Error: Reached rate limit
can read more here: https://docs.agpt.co/setup/#getting-an-api-key
  Waiting 8.0 seconds...
  Error: Reached rate limit

**Comment by frankwalter1301** [comment]
Me too. Credit card added, high limit, etc...  It is very annoying.

**Comment by allelive** [comment]
ma non ce piu il periodo di prova oppure un alternativa opensource
