### ISSUE TITLE
 Error parsing JSON response

### ISSUE THREAD

**Issue by f200ten** [Significant-Gravitas/AutoGPT#5154]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Performance

### Describe your issue.

 Error parsing JSON response with literal_eval unterminated string literal (detected at line 7) (<unknown>, line 7)

### Upload Activity Log Content

写一篇关于强化学习玩王者荣耀项目的总结报告

### Upload Error Log Content

2023-09-03 13:19:46,121 INFO  Error parsing JSON response with literal_eval unterminated string literal (detected at line 7) (<unknown>, line 7)
2023-09-03 13:19:46,125 WARNING  The agent's thoughts could not be parsed: Validation of response failed:
  'thoughts' is a required property

Failed validating 'required' in schema:
    {'$schema': 'http://json-schema.org/draft-07/schema#',
     'additionalProperties': False,
     'properties': {'command': {'additionalProperties': False,
                                'properties': {'args': {'type': 'object'},
                                               'name': {'type': 'string'}},
                                'required': ['name', 'args'],
                                'type': 'object'},
                    'thoughts': {'additionalProperties': False,
                                 'properties': {'criticism': {'description': 'constructive '
                                                                             'self-criticism',
                                                              'type': 'string'},
                                                'plan': {'description': '- '
                                                                        'short '
                                                                        'bulleted\n'
                                                                        '- '
                                                                        'list '
                                                                        'that '
                                                                        'conveys\n'
                                                                        '- '
                                                                        'long-term '
                                                                        'plan',
                                                         'type': 'string'},
                                                'reasoning': {'type': 'string'},
                                                'speak': {'description': 'thoughts '
                                                                         'summary '
                                                                         'to '
                                                                         'say '
                                                                         'to '
                                                                         'user',
                                                          'type': 'string'},
                                                'text': {'description': 'thoughts',
                                                         'type': 'string'}},
                                 'required': ['text',
                                              'reasoning',
                                              'plan',
                                              'criticism',
                                              'speak'],
                                 'type': 'object'}},
     'required': ['thoughts', 'command'],
     'type': 'object'}

On instance:
    {};
  'command' is a required property

Failed validating 'required' in schema:
    {'$schema': 'http://json-schema.org/draft-07/schema#',
     'additionalProperties': False,
     'properties': {'command': {'additionalProperties': False,
                                'properties': {'args': {'type': 'object'},
                                               'name': {'type': 'string'}},
                                'required': ['name', 'args'],
                                'type': 'object'},
                    'thoughts': {'additionalProperties': False,
                                 'properties': {'criticism': {'description': 'constructive '
                                                                             'self-criticism',
                                                              'type': 'string'},
                                                'plan': {'description': '- '
                                                                        'short '
                                                                        'bulleted\n'
                                                                        '- '
                                                                        'list '
                                                                        'that '
                                                                        'conveys\n'
                                                                        '- '
                                                                        'long-term '
                                                                        'plan',
                                                         'type': 'string'},
                                                'reasoning': {'type': 'string'},
                                                'speak': {'description': 'thoughts '
                                                                         'summary '
                                                                         'to '
                                                                         'say '
                                                                         'to '
                                                                         'user',
                                                          'type': 'string'},
                                                'text': {'description': 'thoughts',
                                                         'type': 'string'}},
                                 'required': ['text',
                                              'reasoning',
                                              'plan',
                                              'criticism',
                                              'speak'],
                                 'type': 'object'}},
     'required': ['thoughts', 'command'],
     'type': 'object'}

On instance:
    {}
2023-09-03 13:19:55,068 INFO  Error parsing JSON response with literal_eval unterminated string literal (detected at line 7) (<unknown>, line 7)
2023-09-03 13:19:55,073 WARNING  The agent's thoughts could not be parsed: Validation of response failed:
  'thoughts' is a required property

Failed validating 'required' in schema:
    {'$schema': 'http://json-schema.org/draft-07/schema#',
     'additionalProperties': False,
     'properties': {'command': {'additionalProperties': False,
                                'properties': {'args': {'type': 'object'},
                                               'name': {'type': 'string'}},
                                'required': ['name', 'args'],
                                'type': 'object'},
                    'thoughts': {'additionalProperties': False,
                                 'properties': {'criticism': {'description': 'constructive '
                                                                             'self-criticism',
                                                              'type': 'string'},
                                                'plan': {'description': '- '
                                                                        'short '
                                                                        'bulleted\n'
                                                                        '- '
                                                                        'list '
                                                                        'that '
                                                                        'conveys\n'
                                                                        '- '
                                                                        'long-term '
                                                                        'plan',
                                                         'type': 'string'},
                                                'reasoning': {'type': 'string'},
                                                'speak': {'description': 'thoughts '
                                                                         'summary '
                                                                         'to '
                                                                         'say '
                                                                         'to '
                                                                         'user',
                                                          'type': 'string'},
                                                'text': {'description': 'thoughts',
                                                         'type': 'string'}},
                                 'required': ['text',
                                              'reasoning',
                                              'plan',
                                              'criticism',
                                              'speak'],
                                 'type': 'object'}},
     'required': ['thoughts', 'command'],
     'type': 'object'}

On instance:
    {};
  'command' is a required property

Failed validating 'required' in schema:
    {'$schema': 'http://json-schema.org/draft-07/schema#',
     'additionalProperties': False,
     'properties': {'command': {'additionalProperties': False,
                                'properties': {'args': {'type': 'object'},
                                               'name': {'type': 'string'}},
                                'required': ['name', 'args'],
                                'type': 'object'},
                    'thoughts': {'additionalProperties': False,
                                 'properties': {'criticism': {'description': 'constructive '
                                                                             'self-criticism',
                                                              'type': 'string'},
                                                'plan': {'description': '- '
                                                                        'short '
                                                                        'bulleted\n'
                                                                        '- '
                                                                        'list '
                                                                        'that '
                                                                        'conveys\n'
                                                                        '- '
                                                                        'long-term '
                                                                        'plan',
                                                         'type': 'string'},
                                                'reasoning': {'type': 'string'},
                                                'speak': {'description': 'thoughts '
                                                                         'summary '
                                                                         'to '
                                                                         'say '
                                                                         'to '
                                                                         'user',
                                                          'type': 'string'},
                                                'text': {'description': 'thoughts',
                                                         'type': 'string'}},
                                 'required': ['text',
                                              'reasoning',
                                              'plan',
                                              'criticism',
                                              'speak'],
                                 'type': 'object'}},
     'required': ['thoughts', 'command'],
     'type': 'object'}

On instance:
    {}
2023-09-03 13:20:04,014 INFO  Error parsing JSON response with literal_eval unterminated string literal (detected at line 7) (<unknown>, line 7)
2023-09-03 13:20:04,026 WARNING  The agent's thoughts could not be parsed: Validation of response failed:
  'thoughts' is a required property

Failed validating 'required' in schema:
    {'$schema': 'http://json-schema.org/draft-07/schema#',
     'additionalProperties': False,
     'properties': {'command': {'additionalProperties': False,
                                'properties': {'args': {'type': 'object'},
                                               'name': {'type': 'string'}},
                                'required': ['name', 'args'],
                                'type': 'object'},
                    'thoughts': {'additionalProperties': False,
                                 'properties': {'criticism': {'description': 'constructive '
                                                                             'self-criticism',
                                                              'type': 'string'},
                                                'plan': {'description': '- '
                                                                        'short '
                                                                        'bulleted\n'
                                                                        '- '
                                                                        'list '
                                                                        'that '
                                                                        'conveys\n'
                                                                        '- '
                                                                        'long-term '
                                                                        'plan',
                                                         'type': 'string'},
                                                'reasoning': {'type': 'string'},
                                                'speak': {'description': 'thoughts '
                                                                         'summary '
                                                                         'to '
                                                                         'say '
                                                                         'to '
                                                                         'user',
                                                          'type': 'string'},
                                                'text': {'description': 'thoughts',
                                                         'type': 'string'}},
                                 'required': ['text',
                                              'reasoning',
                                              'plan',
                                              'criticism',
                                              'speak'],
                                 'type': 'object'}},
     'required': ['thoughts', 'command'],
     'type': 'object'}

On instance:
    {};
  'command' is a required property

Failed validating 'required' in schema:
    {'$schema': 'http://json-schema.org/draft-07/schema#',
     'additionalProperties': False,
     'properties': {'command': {'additionalProperties': False,
                                'properties': {'args': {'type': 'object'},
                                               'name': {'type': 'string'}},
                                'required': ['name', 'args'],
                                'type': 'object'},
                    'thoughts': {'additionalProperties': False,
                                 'properties': {'criticism': {'description': 'constructive '
                                                                             'self-criticism',
                                                              'type': 'string'},
                                                'plan': {'description': '- '
                                                                        'short '
                                                                        'bulleted\n'
                                                                        '- '
                                                                        'list '
                                                                        'that '
                                                                        'conveys\n'
                                                                        '- '
                                                                        'long-term '
                                                                        'plan',
                                                         'type': 'string'},
                                                'reasoning': {'type': 'string'},
                                                'speak': {'description': 'thoughts '
                                                                         'summary '
                                                                         'to '
                                                                         'say '
                                                                         'to '
                                                                         'user',
                                                          'type': 'string'},
                                                'text': {'description': 'thoughts',
                                                         'type': 'string'}},
                                 'required': ['text',
                                              'reasoning',
                                              'plan',
                                              'criticism',
                                              'speak'],
                                 'type': 'object'}},
     'required': ['thoughts', 'command'],
     'type': 'object'}

On instance:
    {}
2023-09-03 13:20:04,026 ERROR  The agent failed to output valid thoughts 3 times in a row. Terminating...

**Comment by leodutra** [comment]
Same issue :+1: here

**Comment by AinzLimuru** [comment]
If you deprecate the JSON answer template and use a striped answer instead, and answer only one at a time,  AutoGPT can completely avoid formatting difficulties.

**Comment by leodutra** [comment]
OK, is that a code change or some config I can do? I still don't know AutoGPT internals

**Comment by matt-wortman** [comment]
Same error using v0.5.0

**Comment by imranomar** [comment]
same error
