### ISSUE TITLE
Dynamic expert spawning

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/AutoGPT#5181]
We know that a good match between the AI's given personality and its task can render better results.

## Proposal
A function that takes a `task: str` as input and returns an `AIConfig` (name, personality, best practices) tailored to the task

## Challenges
* 90% of this deliverable comes down to prompting. This will take time to tune and iterate.
  * 💡 There may be opportunities w.r.t. auto-tuning the prompt using an LLM-powered feedback loop.
* In tuning and optimizing the prompt, the risk of overfitting should be taken into account and mitigated (e.g. by using a medium-large varied set of test cases).

**Comment by Boostrix** [comment]
Wouldn't this be overlapping with/specialization of @merwanehamadi  idea about dynamic prompting #3937 

PS: Sorry if these issues are not meant to be discussed here, just let me know plz

**Comment by Pwuts** [comment]
I think you're right @Boostrix, thanks for cross-referencing! :)

**Comment by Pwuts** [comment]
Resolved in 36e2dae. This will need a follow-up to improve performance on specific verticals, but this issue can be closed.
