### ISSUE TITLE
Benchmarking for GPT-Pilot

### ISSUE THREAD

**Issue by nalbion** [Significant-Gravitas/AutoGPT#5185]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I've made an attempt at benchmarking GPT-Pilot, but need help:

https://github.com/Significant-Gravitas/Auto-GPT/pull/5184

**Comment by Swiftyos** [comment]
Hi @nalbion I'm working with @merwanehamadi and @SilenNaihin  to et the benchmark system working again

**Comment by nalbion** [comment]
I've made some changes in my draft-PR which get the benchmark working on your side
