### ISSUE TITLE
Restructure documentation website

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/AutoGPT#5188]
Now that `Auto-GPT-Benchmarks` and friends have been fused into the `Auto-GPT` repo, the documentation should be restructured to accommodate for chapters on the benchmark, forge, and front end.

## To do
- [ ] Move all specific documentation about Auto-GPT (the agent) into a subfolder
    - [ ] Update setup & usage instructions to match the new repo structure
- [ ] Create subfolders with main pages for benchmark, forge, and front end
- [ ] Create new main page

* Anything else..?

**Comment by Yash-Ambekar** [comment]
@Pwuts By creating a main page do you mean changing this section of the docs? as there is literally no explanation of what AutoGPT does.
![image](https://github.com/Significant-Gravitas/AutoGPT/assets/96481913/17bdf2ec-7bf7-4bc3-bc2a-f6e532167ff8)

**Comment by Pwuts** [comment]
@Yash-Ambekar yep!

**Comment by Yash-Ambekar** [comment]
@Pwuts Can I just add content to the main page and open a PR because I don't think I'll be able to do rest of the task in the to-do checklist.

**Comment by Bentlybro** [comment]
Hey @Yash-Ambekar are you in discord? we have this issue [open here](https://discord.com/channels/1092243196446249134/1150534100038463618) I did start work on this but need to continue, if you want we could work on it together?

**Comment by Yash-Ambekar** [comment]
@Bentlybro Yeah sure! ..... the `open here` link is not working.

**Comment by Bentlybro** [comment]
are you in the autogpt discord server? https://discord.com/invite/autogpt and try this link https://discord.com/channels/1092243196446249134/1150534100038463618

**Comment by Bentlybro** [comment]
Hey @sohamtembhurne if you join the discord we are talking about it in there

**Comment by Bentlybro** [comment]
test
