### ISSUE TITLE
Can't complete setup, trouble with 'docker compose build a'

### ISSUE THREAD

**Issue by IngRomo** [Significant-Gravitas/AutoGPT#5243]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

when I try to do:

docker compose build auto-gpt

I get this error:

failed to solve: process "/bin/sh -c poetry install --no-root" did not complete successfully: exit code: 1

**Comment by minifisk** [comment]
getting the same issue, any solution?

**Comment by Austinjporterfield** [comment]
Is there any update on this? It seems to be a recurring issue.
