### ISSUE TITLE
run

### ISSUE THREAD

**Issue by kittenvr** [Significant-Gravitas/AutoGPT#5302]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of Auto-GPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

![image](https://github.com/Significant-Gravitas/Auto-GPT/assets/103120356/1e6ec342-74c2-47ab-a919-02aad2af637e)
If I do ./run setup it asks me with which app I want to open, whit ehat should I run it

**Comment by pglombardo** [comment]
Hi @kittenvr - Did you follow [QUICKSTART.md](https://github.com/Significant-Gravitas/AutoGPT/blob/master/QUICKSTART.md)?  It states that you have to have the Windows Subsystem for Linux (WSL) installed.

> If you are using a Windows system, you will need to install WSL. You can find the installation instructions for WSL [here](https://learn.microsoft.com/en-us/windows/wsl/).

And then after that, execute the `run` script from a terminal.

Do you have the WSL installed?

**Comment by kittenvr** [comment]
> Hi @kittenvr - Did you follow [QUICKSTART.md](https://github.com/Significant-Gravitas/AutoGPT/blob/master/QUICKSTART.md)? It states that you have to have the Windows Subsystem for Linux (WSL) installed.
> 
> > If you are using a Windows system, you will need to install WSL. You can find the installation instructions for WSL [here](https://learn.microsoft.com/en-us/windows/wsl/).
> 
> And then after that, execute the `run` script from a terminal.
> 
> Do you have the WSL installed?

i dont see windows in the list 
![image](https://github.com/Significant-Gravitas/AutoGPT/assets/103120356/87dd5382-c050-4052-99ba-0cfff5c82309)

**Comment by codespearhead** [comment]
> > Hi @kittenvr - Did you follow [QUICKSTART.md](https://github.com/Significant-Gravitas/AutoGPT/blob/master/QUICKSTART.md)? It states that you have to have the Windows Subsystem for Linux (WSL) installed.
> > > If you are using a Windows system, you will need to install WSL. You can find the installation instructions for WSL [here](https://learn.microsoft.com/en-us/windows/wsl/).
> > 
> > 
> > And then after that, execute the `run` script from a terminal.
> > Do you have the WSL installed?
> 
> i dont see windows in the list ![image](https://user-images.githubusercontent.com/103120356/270116752-87dd5382-c050-4052-99ba-0cfff5c82309.png)

They meant you should run `./run setup` inside WSL. To log into WSL, just type `wsl` into the terminal and hit enter.

**Comment by kittenvr** [comment]
> > > Hi @kittenvr - Did you follow [QUICKSTART.md](https://github.com/Significant-Gravitas/AutoGPT/blob/master/QUICKSTART.md)? It states that you have to have the Windows Subsystem for Linux (WSL) installed.
> > > > If you are using a Windows system, you will need to install WSL. You can find the installation instructions for WSL [here](https://learn.microsoft.com/en-us/windows/wsl/).
> > > 
> > > 
> > > And then after that, execute the `run` script from a terminal.
> > > Do you have the WSL installed?
> > 
> > 
> > i dont see windows in the list ![image](https://user-images.githubusercontent.com/103120356/270116752-87dd5382-c050-4052-99ba-0cfff5c82309.png)
> 
> They meant you should run `./run setup` inside WSL. To log into WSL, just type `wsl` into the terminal and hit enter.

@codespearhead 
![image](https://github.com/Significant-Gravitas/AutoGPT/assets/103120356/6ca1606b-fa0a-40e3-a0f4-a3160402f691)

**Comment by codespearhead** [comment]
> > > > Hi @kittenvr - Did you follow [QUICKSTART.md](https://github.com/Significant-Gravitas/AutoGPT/blob/master/QUICKSTART.md)? It states that you have to have the Windows Subsystem for Linux (WSL) installed.
> > > > > If you are using a Windows system, you will need to install WSL. You can find the installation instructions for WSL [here](https://learn.microsoft.com/en-us/windows/wsl/).
> > > > 
> > > > 
> > > > And then after that, execute the `run` script from a terminal.
> > > > Do you have the WSL installed?
> > > 
> > > 
> > > i dont see windows in the list ![image](https://user-images.githubusercontent.com/103120356/270116752-87dd5382-c050-4052-99ba-0cfff5c82309.png)
> > 
> > 
> > They meant you should run `./run setup` inside WSL. To log into WSL, just type `wsl` into the terminal and hit enter.
> 
> @codespearhead ![image](https://user-images.githubusercontent.com/103120356/270384092-6ca1606b-fa0a-40e3-a0f4-a3160402f691.png)

Make sure `pip3 -V` and `python3 -V` doesn't return any errors. if they do, that means you don't have Python 3.x installed and its aliases properly configured on your machine.

**Comment by codespearhead** [comment]
Make sure `pip3 -V` and `python3 -V` don't throw any errors.

If they do, that means you don't have Python 3.x installed and its aliases properly configured on your machine.

**Comment by kittenvr** [comment]
> Make sure `pip3 -V` and `python3 -V` don't throw any errors.
> 
> If they do, that means you don't have Python 3.x installed and its aliases properly configured on your machine.

pip 3 is not installed and it tells me to run sudo apt install python3-pip

**Comment by codespearhead** [comment]
run `sudo apt update` and try again.

**Comment by kittenvr** [comment]
> run `sudo apt update` and try again.

worked until this step 
![image](https://github.com/Significant-Gravitas/AutoGPT/assets/103120356/aac41622-4953-4c91-9128-d0cba3e543b2)

**Comment by codespearhead** [comment]
Try doing [what the error message says](https://stackoverflow.com/a/74477623).

**Comment by Atimus7** [comment]
I am having the same issue and have followed the steps listed here as well. It seems the newest version of autogpt needs some other program not listed to launch the 'run' file. When trying to run setup.sh using the ./run command the same thing happens. Windows seem to be unable to automatically detect what program to use to run the shell script. I tried using PowerShell, which just sends it in a continuous loop. python and cmd prompt allow you to bash it, but an error occurs when attempting to mount the file. Launching it in docker just results in nothing happening. I'm not sure what to say. The QuickStart guide must be missing a key dependency that is not listed. I wish the 'requirements.txt' still existed. pip installing it always worked. There are tutorials for running shell scripts on windows, but it won't even mount properly. I'm not entire sure, but maybe there's an issue with the WSL. Perhaps a flashboot installation of windows professional edition, then a fresh clone of the repository and starting over will resolve the issue. I'm just thinking outside the box but this type of error is also common when attempting to run .sh scripts when WSL isn't properly installed, is corrupted/missing files, or did not get updated along with the previous system update.

**Comment by helloworld4774** [comment]
pip install click

> > Try doing [what the error message says](https://stackoverflow.com/a/74477623).
> 
> i do not understand

**Comment by ZahrizhalAli** [comment]
> I think this is caused in part by cloning the code to a none WSL directory.
> 
> Can you try cloning the code to your user directory in wsl and then trying again

Thanks This one works for mer.
