### ISSUE TITLE
Let the agent name be overridden by a plugin with promtps/generator.py

### ISSUE THREAD

**Issue by NeonN3mesis** [Significant-Gravitas/AutoGPT#5324]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

For my reddit plugin it would be very useful to be able to override the name in ai_settings.yaml. The preferred way is to be able to modify the agent name with a plugin using promtps/generator.py That way I can have the plugin pass the reddit username to the agent as the agent name when the plugin is in use. I could easily grab it from their .env variable for reddit username. The second way we could do is make it a .env variable that can override what is in ai_settings.yaml or replace it. That isn't ideal because I would prefer to be able to pass the name with u/ appended to the front.

### Motivation 🔦

It would be extremely useful for my case and probably others to be able to dynamically change the name of the agent with a plugin to help align the agent.

**Comment by Wladastic** [comment]
Sounds like a good idea actually, just took me a while to see the benefit after re-reading the code for the promptgeneration.
