### ISSUE TITLE
AttributeError: type object 'Schema' has no attribute 'model_rebuild'

### ISSUE THREAD

**Issue by tendaysaweek** [Significant-Gravitas/AutoGPT#5325]
hi guys, 
had the code running fine, then had not credits left and it stopped.
on next run I get this error and cannot seem to find a fix, can you please assist?

**Comment by jmikedupont2** [comment]
same here I think it is a version problem, looking

**Comment by MehdiGASMIMomentum** [comment]
Same with me

**Comment by BennyTMT** [comment]
same with me

**Comment by Swiftyos** [comment]
Hi guys any more context, what are you running? The Forge or AutoGPT agent?

**Comment by SetarehSamami** [comment]
I faced the same issue and found that it was due to the version of the pydantic package I was using. Updating from pydantic==1.10.5 to pydantic==2.10.4 solved the problem for me.
