### ISSUE TITLE
Missing Tutorials

### ISSUE THREAD

**Issue by juanma666** [Significant-Gravitas/AutoGPT#5357]
From the benchmarking tutorial I can only see titles and subtitles. Where is the description of each part?

**Comment by pjw1** [comment]
Work in progress. I think these tutorials should have been completed before the hackathon.
Does anyone know any example of a working forge agent for reference?

**Comment by Swiftyos** [comment]
@pjw1 and @juanma666 [here is the tutorial ](https://medium.com/@aiedge/autogpt-forge-interacting-with-your-agent-1214561b06b) you are looking for. 

I have not had time to copy it over to the git repo just yet. 

I will be working on the memory one today too 👍
