### ISSUE TITLE
Continuous looping of the same instruction

### ISSUE THREAD

**Issue by rotarrares** [Significant-Gravitas/AutoGPT#5405]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of AutoGPT are you using?

Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

After giving the first instruction, autoGPT loops recursively on the first web search, or system throwing an error of append to file, or json memory throwing a format error.

**Comment by Boostrix** [comment]
#3668
