### ISSUE TITLE
agbenchmark - challenge scrape 5_get_information twitter handles are not case sensitive

### ISSUE THREAD

**Issue by pplonski** [Significant-Gravitas/AutoGPT#5416]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I'm checking challenges for Auto-GPT hackaton, and in one of challenges `scrape/5_get_information` the task is `Write the twitter handle of the two hosts of Latent Space to a file called output.txt` to check if the answer is correct the output file should contain

https://github.com/Significant-Gravitas/AutoGPT/blob/a0fba5d1f13d35a1c4a8b7718550677bf62b5101/benchmark/agbenchmark/challenges/verticals/scrape/5_get_information/data.json#L19-L22

The issue: Twitter handles are not case sensitive, output in small letters should be treated as correct as well.

**Comment by hisandan** [comment]
Hi @pplonski , I am not part of the core team, but checking Twitter it seems that it mantain handles with specific cases. In this image you can see that the result of the search is case sensitive: 

![image](https://github.com/Significant-Gravitas/AutoGPT/assets/95585487/63014057-9029-49fc-b7db-c1d795a6315e)

**Comment by pplonski** [comment]
Hi @hisandan, the issue is that both responses are correct. It can be fanahova or FanaHOVA. Both are ok, thats why test should be corrected.
