### ISSUE TITLE
Where files should be written to pass benchmark test?

### ISSUE THREAD

**Issue by pplonski** [Significant-Gravitas/AutoGPT#5418]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Challenges

### Describe your issue.

I'm trying to run my agent that was created by coping `forge` - I'm following the Arena Auto-GPT tutorial. I'm working on the first challenge `WriteFile` https://github.com/Significant-Gravitas/AutoGPT/blob/master/benchmark/agbenchmark/challenges/abilities/write_file/data.json

My agent is creating a correct file in the current directory, but test is not passing. Probably file should be saved in the correct directory ... Where should be output files stored? Do I need to create artifacts to every created file?

**Comment by ntindle** [comment]
@merwanehamadi

**Comment by Swiftyos** [comment]
if you use the workspace class, an instance of which is already part of the agent class, to write files, they will be written in the correct place.

In the example code of the forge, you can see this line - which takes care of writing files to the correct location

`self.workspace.write(task_id=task_id, path="output.txt", data=b"Washington D.C")`
