### ISSUE TITLE
How to run only selected test in benchmark UI?

### ISSUE THREAD

**Issue by pplonski** [Significant-Gravitas/AutoGPT#5419]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I would like to run only selected test in UI. For example, I would like to check agent on ReadFile test, but to run it, I need to run WriteFile as well. I'm aware that there is dependency between tests, however I would like to force execution of only ReadFile. How to do this? 

![image](https://github.com/Significant-Gravitas/AutoGPT/assets/6959032/668086d2-fd8a-4986-8848-827d06e4321b)

**Comment by ntindle** [comment]
@hunteraraujo

**Comment by pplonski** [comment]
It was added :) thank you!
