### ISSUE TITLE
Support for oobabogga 

### ISSUE THREAD

**Issue by mezafits** [Significant-Gravitas/AutoGPT#5518]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I have searched your bugs/features and most of what I found was support for Local Infrence,
However this could be done much simpler, by writing a provider that supports 
https://github.com/oobabooga/text-generation-webui

and while oobabooga has an OpenAI api emulation , there are many bugs with integrating it into AutoGPT. 

I started modding the code and ultimately got to the point where I was getting blocked by the built in permissions access flags that are returned by open ai. 

I'm trying to work on it, however I'm a C# engineer and python is not exactly my cup of tea. 

Open AI is a great platform, and i see that originally an intent was created to have multiple providers.  However it appears that OpenAI specific implementation is spread out in the code in places that make it difficult to write  a new provider.  It would be nice if work would be done to improve the adaptability of this. 

Open AI is one of the best models but it's costly. Other models may be able to do great work running locally for much cheaper.

**Comment by chymian** [comment]
+1 for ooba and/or litellm is an API-proxy, works great
https://github.com/BerriAI/litellm/issues
