### ISSUE TITLE
AttributeError: cython_sources - cannot complete the installation of AutoGPT :(

### ISSUE THREAD

**Issue by liamcbenson** [Significant-Gravitas/AutoGPT#5519]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I keep getting an error when attempting to install AutoGPT. 

I have been searching on GitHub as to what the actual problem is but seems no one else Is having this issue. I get a "AttributeError: cython_srouces" and then pip installer fails with a subprocess-excited-with-error

        File "<string>", line 204, in get_source_files
        File "C:\Users\AutoGPT\AppData\Local\Temp\pip-build-env-lyj30tbw\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

### Upload Activity Log Content

File "<string>", line 204, in get_source_files
        File "C:\Users\AutoGPT\AppData\Local\Temp\pip-build-env-lyj30tbw\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Upload Error Log Content

File "<string>", line 204, in get_source_files
        File "C:\Users\AutoGPT\AppData\Local\Temp\pip-build-env-lyj30tbw\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ntindle** [comment]
I've never seen this error before. How are you attempting to install?

**Comment by liamcbenson** [comment]
I am attempting to install via an elevated powershell session and I also get this same error if I try and run the AutoGPT run.bat in command line. 

UAC is disabled, User is a local admin and both CMD and Powershell are executing as system.

**Comment by Nogdoia** [comment]
Having the same issue
