### ISSUE TITLE
Flutter front-end loop

### ISSUE THREAD

**Issue by neilmartindev** [Significant-Gravitas/AutoGPT#5537]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Other

### Describe your issue.

Login loop with Google and GitHub as auth when trying to log into the Flutter front end via http://localhost:8000. I've added the 3rd party provider to my GitHub and also tried to sign in through Google which show as a 200 code in the web tools on Firefox but it doesn't let me go any further beyond this point.

It installs fine and runs fine in the terminal as shown by the screenshot:
https://i.imgur.com/3HnzJqO.png

**Comment by neilmartindev** [comment]
Tried to rm -rf frontend/ and pull it back with no luck, emptied the cache to see if that was the case but still not had any success.

**Comment by mattsinnock** [comment]
I'm having the same issue having just followed instructions to create and run my first agent. Only difference to my environment is I'm running on mac. 
1. I run the agent
2. I navigate to `http://localhost:8000/app/index.html`
3. After selecting my google account for oauth:
<img width="1148" alt="Screenshot 2023-10-05 at 2 36 56 PM" src="https://github.com/Significant-Gravitas/AutoGPT/assets/9924589/956402a6-5d1c-4861-85ae-2dd5f9cc92fa">
4. The page reverts to the signin page without the chat section:
<img width="1148" alt="Screenshot 2023-10-05 at 2 36 56 PM" src="https://github.com/Significant-Gravitas/AutoGPT/assets/9924589/a1f2c699-5785-45f2-a8d2-e2e7ec919a93">

**Comment by hunteraraujo** [comment]
@neilmartindev @mattsinnock are you guys using Github Codespaces? Or are you booting this up from your terminal?

**Comment by neilmartindev** [comment]
> @neilmartindev @mattsinnock are you guys using Github Codespaces? Or are you booting this up from your terminal?

Just from terminal :)

**Comment by debin2025** [comment]
> I'm having the same issue having just followed instructions to create and run my first agent. Only difference to my environment is I'm running on mac.
> 
>     1. I run the agent
> 
>     2. I navigate to `http://localhost:8000/app/index.html`
> 
>     3. After selecting my google account for oauth:
> 
> 
> <img alt="Screenshot 2023-10-05 at 2 36 56 PM" width="1148" src="https://user-images.githubusercontent.com/9924589/272755546-956402a6-5d1c-4861-85ae-2dd5f9cc92fa.png"> 4. The page reverts to the signin page without the chat section: <img alt="Screenshot 2023-10-05 at 2 36 01 PM" width="1148" src="https://user-images.githubusercontent.com/9924589/272756044-11354cbc-cba1-45ac-882f-6453ca9dd781.png">

I was able to fix this loop by unblocking cross-site cookies in firefox settings. lmk if that works for you!

**Comment by hunteraraujo** [comment]
Can you guys try to rebase your project form master and see if the issue persists?

**Comment by hunteraraujo** [comment]
@neilmartindev @mattsinnock @debin2025

**Comment by neilmartindev** [comment]
> @neilmartindev @mattsinnock @debin2025 

Hey, I'll try tonight and reply back. Appreciated!

**Comment by neilmartindev** [comment]
Looks like it is fixed, can't replicate the issue. Is there any chance this can be closed with the hacktoberfest label?
