### ISSUE TITLE
config.chat_messages_enabled

### ISSUE THREAD

**Issue by jmikedupont2** [Significant-Gravitas/AutoGPT#5546]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Other

### Describe your issue.

https://github.com/Significant-Gravitas/AutoGPT/blob/7f89b8aae8748bc88b29ca94c3604ba540bbef94/autogpts/autogpt/autogpt/app/main.py#L478
this line prompts the user after you tell it not to. 
```        if config.chat_messages_enabled: 
             console_input = await clean_input(config, "Waiting for your response...") 
         else: 
             console_input = await clean_input( 
                 config, Fore.MAGENTA + "Input: " + Style.RESET_ALL 
             )```
In both cases it prompts the user


### Upload Activity Log Content

_No response_

### Upload Error Log Content

_No response_

**Comment by Pwuts** [comment]
Not a bug

**Comment by jmikedupont2** [comment]
This behaviour cost me many hours of debugging. Why is it calling clean when then user requested no chats to be displayed? This is the second issue you closed on the same topic and there is very little said here in git.  can you please document how to prevent the app from asking questions ?

**Comment by jmikedupont2** [comment]
so my goal here is to have autogpt work out of the box in cicd without monkey patches and using documented methods. Can you help me?

**Comment by Pwuts** [comment]
Let me cross-post the explanation that I gave [on discord](https://discord.com/channels/1092243196446249134/1095817829405704305/1159294398903877693) yesterday:
> `clean_input` will either prompt the user through the terminal or, `if config.chat_messages_enabled`, through a chat message to/from a plugin. The code does exactly what it's supposed to do afaics. The `if` statement is there to adjust the message based on where it's being shown.

> in CI, to run challenges, the `clean_input` function is monkeypatched to return `y`

We also have the user-facing "continuous mode", which is documented, and which will let the agent run without user approval.
