### ISSUE TITLE
ModuleNotFoundError: No module named 'click'

### ISSUE THREAD

**Issue by Shatter6** [Significant-Gravitas/AutoGPT#5604]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

ModuleNotFoundError: No module named 'click'

### Upload Activity Log Content

PS E:\Users\Owner\Desktop\AutoGPT-agbenchmark-v0.0.10> pip3 install click
Requirement already satisfied: click in c:\python311\lib\site-packages (8.1.7)
Requirement already satisfied: colorama in c:\python311\lib\site-packages (from click) (0.4.6)
PS E:\Users\Owner\Desktop\AutoGPT-agbenchmark-v0.0.10> & C:/Users/Owner/AppData/Local/Programs/Python/Python312/python.exe e:/Users/Owner/Desktop/AutoGPT-agbenchmark-v0.0.10/cli.py
Requirement already satisfied: click in c:\python311\lib\site-packages (8.1.7)
Requirement already satisfied: colorama in c:\python311\lib\site-packages (from click) (0.4.6)
Requirement already satisfied: PyGithub in c:\python311\lib\site-packages (2.1.1)
Requirement already satisfied: pynacl>=1.4.0 in c:\python311\lib\site-packages (from PyGithub) (1.5.0)
Requirement already satisfied: python-dateutil in c:\python311\lib\site-packages (from PyGithub) (2.8.2)
Requirement already satisfied: requests>=2.14.0 in c:\python311\lib\site-packages (from PyGithub) (2.31.0)
Requirement already satisfied: pyjwt[crypto]>=2.4.0 in c:\python311\lib\site-packages (from PyGithub) (2.8.0)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\python311\lib\site-packages (from PyGithub) (4.8.0)
Requirement already satisfied: urllib3>=1.26.0 in c:\python311\lib\site-packages (from PyGithub) (2.0.6)
Requirement already satisfied: Deprecated in c:\python311\lib\site-packages (from PyGithub) (1.2.14)
Requirement already satisfied: cryptography>=3.4.0 in c:\python311\lib\site-packages (from pyjwt[crypto]>=2.4.0->PyGithub) (41.0.4)
Requirement already satisfied: cffi>=1.4.1 in c:\python311\lib\site-packages (from pynacl>=1.4.0->PyGithub) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python311\lib\site-packages (from requests>=2.14.0->PyGithub) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in c:\python311\lib\site-packages (from requests>=2.14.0->PyGithub) (3.4)        
Requirement already satisfied: certifi>=2017.4.17 in c:\python311\lib\site-packages (from requests>=2.14.0->PyGithub) (2023.7.22)
Requirement already satisfied: wrapt<2,>=1.10 in c:\python311\lib\site-packages (from Deprecated->PyGithub) (1.15.0)
Requirement already satisfied: six>=1.5 in c:\python311\lib\site-packages (from python-dateutil->PyGithub) (1.16.0)
Requirement already satisfied: pycparser in c:\python311\lib\site-packages (from cffi>=1.4.1->pynacl>=1.4.0->PyGithub) (2.21)Traceback (most recent call last):
  File "e:\Users\Owner\Desktop\AutoGPT-agbenchmark-v0.0.10\cli.py", line 8, in <module>
    import click
ModuleNotFoundError: No module named 'click'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\Users\Owner\Desktop\AutoGPT-agbenchmark-v0.0.10\cli.py", line 15, in <module>
    import click
ModuleNotFoundError: No module named 'click'

### Upload Error Log Content

This one has me stumped... it says 'Click" is installed and I even ran pip3 install click just to make sure I wasn't losing my mind. However keeps saying it is not found... is this some kind of 'Path' issue or something else I am missing. 

Thanks for your assistance

**Comment by donvito** [comment]
same here, using Mac OS

**Comment by donvito** [comment]
I was able to overcome this by installing requirements.txt as mentioned [here](https://github.com/Significant-Gravitas/AutoGPT/issues/2472).

**Comment by amabelleS** [comment]
Same here:
```$ pip3 install click
Requirement already satisfied: click in c:\python311\lib\site-packages (8.1.7)
Requirement already satisfied: colorama in c:\python311\lib\site-packages (from click) (0.4.6)

[notice] A new release of pip available: 22.3.1 -> 23.3
[notice] To update, run: python.exe -m pip install --upgrade pip```

**Comment by moona3k** [comment]
Try updating the run file from `python3 cli.py` to `python3.9 cli.py`. This resolved the issue for me.

**Comment by AurganicSubstance** [comment]
I have the same issue; tried this but still doesnt work

> Try updating the run file from `python3 cli.py` to `python3.9 cli.py`. This resolved the issue for me.

**Comment by AurganicSubstance** [comment]
I solved the issue eventually by specifying python version to 3.10 (locally i only have 3.9or 3.11, hence this should have came with the repository with AutoGPT). And in this virtual base environment i didnt have pip... hence needed to apt install it first
