### ISSUE TITLE
Update the Quickstart.md to help new users setup for master branch

### ISSUE THREAD

**Issue by SVJayanthi** [Significant-Gravitas/AutoGPT#5670]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

The Quickstart.md docs have to be updated for the latest master branch. There are several issues raised already (https://github.com/Significant-Gravitas/AutoGPT/issues/5193, https://github.com/Significant-Gravitas/AutoGPT/issues/5631) related to this. 
1. Ask the user to create a `.github_access_token` and create a Classic Personal Access token and store it in that file
2. Ask the user to create a `.env` file and set `OPENAI_API_KEY=<api_key>`
3. On first creation of agent, as the user to run `./run agent start <YOUR_AGENT_NAME> --setup` instead of  `./run agent start <YOUR_AGENT_NAME>`
4. Make it clear to the user that only the first write_txt task will complete on the user interface

Provide links to starting guides to help user create an agent:
Official AutoGPT guide : https://aiedge.medium.com/autogpt-forge-crafting-intelligent-agent-logic-bc5197b14cb4
LabLab guide: https://lablab.ai/t/autogpt-tutorial-creating-a-research-assistant-with-auto-gpt-forge

**Comment by zedatrix** [comment]
Pwuts recently updated the docs, try giving that a whirl?
https://docs.agpt.co/autogpt/setup/
