### ISSUE TITLE
why I have a error when run "pip3 install open-interpreter" on Mac

### ISSUE THREAD

**Issue by Zcc1234567890** [Significant-Gravitas/AutoGPT#5681]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

it has a error shows
 note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
Failed to build tiktoken aiohttp
ERROR: Could not build wheels for tiktoken, aiohttp, which is required to install pyproject.toml-based projects

**Comment by AntonenkoArtem** [comment]
[Zcc1234567890](https://github.com/Zcc1234567890) which python version you`re using? 
I see https://github.com/openai/openai-python/issues/645 in openai which is look similar to what you have. Looks like can be related to python 3.12

also similar https://github.com/psf/black/issues/3483
