### ISSUE TITLE
Unclear Forge Tutorial Documentation

### ISSUE THREAD

**Issue by galinafendi** [Significant-Gravitas/AutoGPT#5756]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Documentation

### Describe your issue.

Hi all,

I was going through the Forge [tutorial]([https://github.com/Significant-Gravitas/AutoGPT/blob/master/autogpts/forge/tutorials/001_getting_started.md]) as part of the B3 Hackathon that the team ran and had a hard time making progress through it. Here are the things that tripped me up:

- There are no instructions on configuring the .env file
- No clarity in how to configure the github access token, the only instructions appeared in the terminal after a few failed tries
- The content does not clearly spell out “steps on building your first agent”, the tutorials sound like they give background and educational info but not actionable steps
- Unclear on how to build an agent, lack of chronological step by step of which files either need to be created or edited and what goes into the file(s). If it’s in there, then it’s lost amongst all the other background and contextual and educational material
- Agent.py template is buried in a folder, had to refer to the screenshot many times to find it
- Unsure if I’m supposed to edit the existing agent.py file or copy it into my agent’s folder
- Had no clue that the ai_profile.py file held the promptengine so I could follow along in the docs
- Only the final version of a function is given, I want the entire file
- After the first step when the instruction was to run start the agent, I expected it to work with  some basic general instructions, not the Washington DC example which was unclear to me 

Hope this helps, happy to provide additional info.

**Comment by Bentlybro** [comment]
Thank you for this i have brought this up with the relevant people working on the tutorials and will see what we can do about getting this improved 🙏  Cc: <@698489167281127474>

**Comment by galinafendi** [comment]
Cool thanks!

**Comment by oliverlwang** [comment]
what is the difference between forge and autogpt itself?
which one should i use to create my own agent?

**Comment by galinafendi** [comment]
Forge provides a nice UI for you to run your experiments
