### ISSUE TITLE
Quickstart Agents created without webdriver-manager

### ISSUE THREAD

**Issue by D0rkKnight** [Significant-Gravitas/AutoGPT#5760]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I follow the quickstart guide and create an agent. When I start the agent, uvicorn reports me the following:

INFO:     Started server process [2749]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
Error occurred while registering abilities: No module named 'webdriver_manager'

I fixed this by going into the agent's root folder and installing webdriver_manager to Poetry.
The same issue occurred when starting the template forge agent.

**Comment by dayronmiranda** [comment]
I have the same issues

**Comment by seven4233** [comment]
I have the same issues

**Comment by Umar-Azam** [comment]
Same issue, I am using a devcontainer for development on linux.

**Comment by DoNotSwallow** [comment]
Same on MacOS

**Comment by DG1202** [comment]
Same on macOS

**Comment by AgentService** [comment]
same linux

**Comment by entrustgabri** [comment]
Same issue on Ubuntu, I have tried installing the webdriver-manager package but the error still showing

**Comment by lokidaibel** [comment]
Fresh install of auto-gpt : https://github.com/Significant-Gravitas/AutoGPT
followed this instruktion : https://github.com/Significant-Gravitas/AutoGPT/blob/master/autogpts/forge/tutorials/001_getting_started.md

on: PRETTY_NAME="Ubuntu 22.04.2 LTS"

will run into:
[2023-10-27 08:30:09,158] [__main__       ] [INFO]      📝  Agent server starting on http://localhost:8000
Error occurred while registering abilities: No module named 'webdriver_manager'

This is a showstopper.
