### ISSUE TITLE
Forge Web Frontend Google Cloud OAuth does not accept 127.0.0.1 loopback address

### ISSUE THREAD

**Issue by D0rkKnight** [Significant-Gravitas/AutoGPT#5761]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I followed the Quickstart guide on Windows in WSL.

When trying to log into the web frontend using Google OAuth, the process worked with localhost:8000 but not 127.0.0.1:8000
I ran into this issue because I use VSCode which converts localhost to 127.0.0.1 when clicking through links.

I met somebody on the AutoGPT discord who had a similar issue, leading me to think that this may be somewhat common.

**Comment by jihun-im** [comment]
Accessing `http://localhost:8000` not `http://0.0.0.0:8000` solved the problem in my case

**Comment by zhangwzhang** [comment]
I also encountered the same problem，Why hasn't anyone answered？

**Comment by zhqsdhr** [comment]
me too why

**Comment by zhqsdhr** [comment]
> 我面临着同样的问题，但我将 uvicorn 更改为在 0.0.0.0:8000 Github 弹出窗口上运行，以非常快地登录 disappers。 出现 Google 弹出窗口，但出现错误：访问被阻止：此应用程序的请求无效 - 错误 400：redirect_uri_mismatch
> 
> 在控制台中，我看到：
> 
> > 信息：当前域未获得 OAuth 操作授权。这将阻止signInWithPopup、signInWithRedirect、linkWithPopup 和linkWithRedirect 工作。将您的域 (xxx.local) 添加到 Firebase 控制台 -> 身份验证 -> 设置 -> 授权域选项卡中的 OAuth 重定向域列表。
> > 不确定绕过它的投注方法。

How to set the UVICORN address

**Comment by ozyurterdem** [comment]
same problem

**Comment by yechoua** [comment]
exactly the same problem for me, it's like the authentication part is keeping me stuck of using the web interface only on the same machine as the server, i would have prefered to be able to have autogpt running in one server and access it from various remote computer. the url mismatch is like the permission for the autogpt application are locked on the localhost and then can't apply to any other uri, I guess the only way to "correct" it is by creating a google app with permission of authentication, setting it to return to the domain/uri you want it to point back and then you'll be able to use another uri than localhost but again it's just a guess, if anyone already did it please give the walkthrought and the files to edit

**Comment by ntindle** [comment]
We do this because the front end was designed for local use only. There aren’t security considerations or verifications that would need to be done if it was quickly hostable

**Comment by ntindle** [comment]
> > We do this because the front end was designed for local use only. There aren’t security considerations or verifications that would need to be done if it was quickly hostable
> 
> I understand but a lot of windows users activate their wsl2 only for this project and then they are stuck to alway keep an rdp page open without having all the favs etc inside, that's the only reason most of the users are looking for local access from same network, for thoses looking for a saas solution i guess they are aware of what can be dangerous for them plus i added a little reminder specially for those who don't know what they are doing

Fair, I'll put it in the good first issue category
