### ISSUE TITLE
/usr/local/bin/python: No module named autogpt

### ISSUE THREAD

**Issue by lihui123456** [Significant-Gravitas/AutoGPT#5762]
docker部署autogpt报错 /usr/local/bin/python: No module named autogpt
[完全按照](https://autogpt.cn/setup) 这个来的
docker 镜像版本V0.4.7
docker-compose.yml
version: "3.9"
services:
  auto-gpt:
    image: significantgravitas/auto-gpt
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      MEMORY_BACKEND: ${MEMORY_BACKEND:-redis}
      REDIS_HOST: ${REDIS_HOST:-redis}
    volumes:
      - ./:/app
    profiles: ["exclude-from-up"]
  redis:
    image: "redis/redis-stack-server:latest"

**Comment by yhyu13** [comment]
docker-compose up是在哪个目录运行的？autogpt根目录吗

**Comment by lihui123456** [comment]
> docker-compose up是在哪个目录运行的？autogpt根目录吗
> 
> docker compose yml里写了这个volume mapping
> 
> ```
> volumes:
> - ./:/app
> ```

是在autogpt根目录运行的
