### ISSUE TITLE
AutoGPT setup cannont complete because "GitHub account is not configured." but it is, in fact configured.

### ISSUE THREAD

**Issue by Tex6298** [Significant-Gravitas/AutoGPT#5786]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows Subsystem for Linux (WSL)

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

AutoGPT setup cannont complete because "GitHub account is not configured." but it is, in fact configured.

Have followed the instructions given and confirmed in CLI that they have worked.

**Comment by LitoS3** [comment]
Hello, i have the same problem in wsl

⚠️ Git user is not configured.
To configure Git with your user info, use the following commands:
  git config --global user.name "Your (user)name"
  git config --global user.email "Your email"
✅ GitHub access token loaded successfully.
✅ GitHub access token has the required permissions.

But user and mail are configured in ~/.gitconfig
