### ISSUE TITLE
Frontend: Support Markdown formatting for step output

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/AutoGPT#5787]
Supporting Markdown formatting for the step output of agents would be a huge UX improvement. Specifically, the content of the `output` response attribute of [`/ap/v1/agent/tasks/<task_id>/steps`](https://agentprotocol.ai/endpoints#execute-agent-task-step) should be interpreted as Markdown.

![image](https://github.com/Significant-Gravitas/AutoGPT/assets/12185583/9dd3533d-706a-4fa1-a172-63c7d182489e)

**Comment by NamanAarzoo** [comment]
Hi, can you please describe more about the issue?

**Comment by Pwuts** [comment]
@NamanAarzoo I've added some more info and an image indicating the UI elements that this issue relates to.

@hunteraraujo indicated he might be tackling this today, so make sure to coordinate with him if you want to work on this.
