### ISSUE TITLE
 start error by tip 'no module named 'uvicorn' ' and was run on gitpod

### ISSUE THREAD

**Issue by coderxingzhe** [Significant-Gravitas/AutoGPT#5809]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS, and run with a online IDE named gitpod,it's websit is "https://www.gitpod.io/"

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

when i running agent by command ‘./run agent start YOUR_AGENT_NAME’，the terminal stoped ,and tips 'ModuleNotFoundError: No module named 'uvicorn''

### Upload Error Log Content

![32271697656541_ pic](https://github.com/Significant-Gravitas/AutoGPT/assets/15308808/dddda709-daf2-4ab8-993e-986b2d91bb7d)

**Comment by chymian** [comment]
that also happen on a clean ubu22.04 install on new created agent.

**Comment by Sn-one** [comment]
experiencing the same issue , any help ?

**Comment by abmallick** [comment]
Looks like https://github.com/Significant-Gravitas/AutoGPT/issues/5901 and this one are duplicates. Take a look at my answer [here](https://github.com/Significant-Gravitas/AutoGPT/issues/5901#issuecomment-1797884511)

**Comment by liuqiyuan** [comment]
Seriously the homepage doc should contain at least a recommended py version to run the application.

**Comment by liuqiyuan** [comment]
> > Seriously the homepage doc should contain at least a recommended py version to run the application.
> 
> Oh im sorry i thought that was mentioned, ill get this sorted, we mainly use python11+

No worries, please help do so. With py 11+ the problem is solved.
