### ISSUE TITLE
ModuleNotFoundError: No module named 'forge.sdk'

### ISSUE THREAD

**Issue by seven4233** [Significant-Gravitas/AutoGPT#5810]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

ModuleNotFoundError: No module named 'forge.sdk'

**Comment by ATaylorAerospace** [comment]
I ran into this issue with an install a couple of weeks back and solved it by reinstalling requirements.txt

pip install -r requirements.txt

**Comment by testost** [comment]
I have the same issue. There is no requirements.txt?

**Comment by burythehatchet** [comment]
i had same issue and then grabbed requirements.txt from older release and install it via pip install -r requirement.txt

after this forge.sdk error gone but i had another one. it was while building wheel for lxml installation. so i had to update python to 3.11 and now everything seems works fine.

hope it will help. btw i have mac m1 with sonoma

**Comment by benjblack** [comment]
Same issue on Windows, python 3.11. Tried this but didn't work:

pip install -r ../../docs/requirements.txt

**Comment by burythehatchet** [comment]
updates: it seems like 3.11 is not a good one to use with autogpt. so i got back to 3.10 and same error. which fixed now pretty easy with pip install autogpt-forge

**Comment by Kremeni** [comment]
To those who is still facing this issue - consider installing through docker. Worked for me.

**Comment by olariuromeo** [comment]
the some Error occurred while registering abilities: No module named 'forge.sdk.abilities'
 [2023-12-15 01:06:52,027] [__main__       ] [INFO]	📝  Agent server starting on http://localhost:8000
INFO:     Started server process [90586]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
[2023-12-15 01:06:53,382] [watchfiles.main] [INFO]	📝  10 changes detected
[2023-12-15 01:06:53,733] [watchfiles.main] [INFO]	📝  4 changes detected
Error occurred while registering abilities: No module named 'forge.sdk.abilities'
Error occurred while registering abilities: No module named 'forge.sdk.abilities'
Error occurred while registering abilities: No module named 'forge.sdk.abilities'
Error occurred while registering abilities: No module named 'forge.sdk.abilities'
[2023-12-15 01:06:54,083] [watchfiles.main] [INFO]	📝  4 changes detected
