### ISSUE TITLE
python run setup returns invalid syntax

### ISSUE THREAD

**Issue by i-ScriptALot** [Significant-Gravitas/AutoGPT#5914]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

C:\Users\217216X\AutoGPT>python run setup
  File "C:\Users\217216X713089\AutoGPT\run", line 3
    python3 cli.py "$@"
            ^^^
SyntaxError: invalid syntax

### Upload Error Log Content

C:\Users\217216X\AutoGPT>python run setup
  File "C:\Users\217216X713089\AutoGPT\run", line 3
    python3 cli.py "$@"
            ^^^
SyntaxError: invalid syntax

**Comment by ryanrudd** [comment]
According to the quick start, if you are using Windows you need to install WSL and run the setup that way:

https://github.com/Significant-Gravitas/AutoGPT/blob/master/QUICKSTART.md#for-windows-users

**Comment by javableu** [comment]
It did not work for me with wsl, I had to run dos2unix setup.sh and dos2unix run to have everything in order.

**Comment by Slowly-Grokking** [comment]
git needs to be setup to fix the line endings.
https://stackoverflow.com/questions/60638285/run-shell-script-in-wsl-with-r-n
https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace
