### ISSUE TITLE
 "TypeError: argument of type 'NoneType' is not iterable" encountered during setup using "./run setup" command

### ISSUE THREAD

**Issue by maljefairi** [Significant-Gravitas/AutoGPT#5928]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Stable (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

While executing the `./run setup` command after configuring the GitHub access token, I encountered a Python TypeError. The error message was `TypeError: argument of type 'NoneType' is not iterable`. This occurred after the message `✅ GitHub access token loaded successfully.` Here's the relevant portion of the traceback:

```plaintext
File "autoGPT/AutoGPT/cli.py", line 129, in setup
    if "public_repo" in scopes or "repo" in scopes:
       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

This halted the setup process and I'm unsure how to proceed. Any help or guidance on how to resolve this issue would be appreciated.

### Upload Activity Log Content

Skyfall-Gem :: autoGPT/AutoGPT ‹master*› » ./run setup                          1 ↵

       d8888          888             .d8888b.  8888888b. 88888888888 
      d88888          888            d88P  Y88b 888   Y88b    888     
     d88P888          888            888    888 888    888    888     
    d88P 888 888  888 888888 .d88b.  888        888   d88P    888     
   d88P  888 888  888 888   d88""88b 888  88888 8888888P"     888     
  d88P   888 888  888 888   888  888 888    888 888           888     
 d8888888888 Y88b 888 Y88b. Y88..88P Y88b  d88P 888           888     
d88P     888  "Y88888  "Y888 "Y88P"   "Y8888P88 888           888     
                                                                                                                                       

🚀 Setup initiated...

poetry could not be found
Installing poetry...
Retrieving Poetry metadata

The latest version (1.6.1) is already installed.
✅ GitHub account is configured with username: 
✅ GitHub access token loaded successfully.
Traceback (most recent call last):
  File "/autoGPT/AutoGPT/cli.py", line 891, in <module>
    cli()
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/autoGPT/AutoGPT/cli.py", line 129, in setup
    if "public_repo" in scopes or "repo" in scopes:
       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by beaTejakulator** [comment]
@maljefairi Did you take a token (classic) ? And did you check "repo" under "Select scopes" ?

**Comment by wmsimpson** [comment]
@beaTejakulator Ran into the same error when using the beta tokens. Switching to classic fixed the issue, thanks!
