### ISSUE TITLE
Error 404 in RUN and Python3 urllib3 not supported

### ISSUE THREAD

**Issue by testdrivecheck** [Significant-Gravitas/AutoGPT#6081]
Hello everyone, I thank your community for the great work done and the incredible sharing. I did the setup step-by-step as directed. However, in the last step I get the 404 error, like this:

**An error occurred: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/repos/repos#get-a-repository"}**

to be precise, this error is raised when I launch the command "./run arena enter MYAGENTNAME", and the result is

/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.7) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
  
How can I solve it?

Thank you

**Comment by xiaobi625** [comment]
me too
