### ISSUE TITLE
setup new agent, issue if folder $HOME/.local/bin did not exist/poetry setup

### ISSUE THREAD

**Issue by shuther** [Significant-Gravitas/AutoGPT#6089]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

while following the steps: [forge tutorial](https://github.com/Significant-Gravitas/AutoGPT/blob/master/autogpts/forge/tutorials/001_getting_started.md)
the setup installed poetry, but at the step 4 (./run agent start) failed 'unable to locate poetry'.
poetry was properly installed and I was able to root the issue from the .profile file (at least in Ubuntu):
```
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

```
I had to force the reload of the .profile file so the PATH could be set properly.

maybe it should be a recommandation in the setup phase (step 1)?

**Comment by AbstractEyes** [comment]
Thanks that worked.

**Comment by colemvnio** [comment]
This seems to also be a problem on M1 Pro following the Forge tutorial.

I've reinstalled everything, confirmed Poetry is detectable in my global terminal and even tried with a Poetry environment in Pycharm and it will not detect my Poetry installation.
