### ISSUE TITLE
Missing "deployment_id" when using Azure credentials

### ISSUE THREAD

**Issue by hargunmujral** [Significant-Gravitas/AutoGPT#6097]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I've set up my azure token and the deployment ids correctly in the `azure.yaml` file. But when I run the run script for AutoGPT, I get a missing deployment_id error from OpenAI. I did some debugging and investigating, and the config is correctly being set in the AutoGPT code (the fast_llm, deployment_id, smart_llm attributes are being set). For some reason, however, this deployment_id doesn't reach the OpenAI API call. 

### Upload Error Log Content

openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.chat_completion.ChatCompletion'>

**Comment by hargunmujral** [comment]
To clarify, the `run` script works and spins up a server, but when I create a task, that's when the error occurs

**Comment by Dorado1987A** [comment]
Happening for me too, managed to find a solution @hargunmujral ?

**Comment by hargunmujral** [comment]
Nope, if I get a chance in thr next few days, I'll see if I can make a patch
