### ISSUE TITLE
./run agent create not working

### ISSUE THREAD

**Issue by CodeZeno** [Significant-Gravitas/AutoGPT#6106]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows Subsystem for Linux (WSL)

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

~/Susan$ ./run agent create Susan
😞 Agent name 'Susan' is not valid. It should not contain spaces or special characters other than -_

Have tried other names and typing the command manually.

I believe this commit broke it: https://github.com/Significant-Gravitas/AutoGPT/commit/aef512e49ea04c0718437986fbb81e9ac316673d

### Upload Activity Log Content

N/A

### Upload Error Log Content

N/A

**Comment by Bentlybro** [comment]
where you able to get this to work as it seems your agent was able to join the arena? #6107

**Comment by rummsi1337** [comment]
It seems there was an issue with a recent change to the agent_name regex. I proposed a fix here: https://github.com/Significant-Gravitas/AutoGPT/pull/6108

**Comment by CodeZeno** [comment]
> where you able to get this to work as it seems your agent was able to join the arena? #6107

I updated my code to the original code before the regex update and it worked.

**Comment by Bentlybro** [comment]
CC: @Swiftyos think this needs checking out

**Comment by paegelow** [comment]
Same here
