### ISSUE TITLE
Error when naming agent

### ISSUE THREAD

**Issue by sublimejoey** [Significant-Gravitas/AutoGPT#6126]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I am getting an arbitrary error when trying to name the agent. I don't have any special characters or issues with the name chosen, but it still gives me the error.

### Upload Activity Log Content

sublimeaquatics@Josephs-iMac Auto-GPT % ./run setup

       d8888          888             .d8888b.  8888888b. 88888888888 
      d88888          888            d88P  Y88b 888   Y88b    888     
     d88P888          888            888    888 888    888    888     
    d88P 888 888  888 888888 .d88b.  888        888   d88P    888     
   d88P  888 888  888 888   d88""88b 888  88888 8888888P"     888     
  d88P   888 888  888 888   888  888 888    888 888           888     
 d8888888888 Y88b 888 Y88b. Y88..88P Y88b  d88P 888           888     
d88P     888  "Y88888  "Y888 "Y88P"   "Y8888P88 888           888     
                                                                                                                                       

🚀 Setup initiated...

✅ GitHub account is configured with username: sublimejoey and email: sublimeaquaticsmgmt@gmail.com
❌ GitHub access token file is empty. Please follow the instructions below to set up your GitHub access token.
❌ To configure your GitHub access token, follow these steps:
	1. Ensure you are logged into your GitHub account
	2. Navigate to https://github.com/settings/tokens
	3. Click on 'Generate new token'.
	4. Click on 'Generate new token (classic)'.
	5. Fill out the form to generate a new token. Ensure you select the 'repo' scope.
	6. Open the '.github_access_token' file in the same directory as this script and paste the token into this file.
	7. Save the file and run the setup command again.

🔴 If you need help, please raise a ticket on GitHub at https://github.com/Significant-Gravitas/AutoGPT/issues

sublimeaquatics@Josephs-iMac Auto-GPT % ./run
Usage: cli.py [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  agent      Commands to create, start and stop agents
  arena      Commands to enter the arena
  benchmark  Commands to start the benchmark and list tests and categories
  setup      Installs dependencies needed for your system.
sublimeaquatics@Josephs-iMac Auto-GPT % setup
zsh: command not found: setup
sublimeaquatics@Josephs-iMac Auto-GPT % ./run agent create YOUR_AGENT_NAME
😞 Agent name 'YOUR_AGENT_NAME' is not valid. It should not contain spaces or special characters other than -_
sublimeaquatics@Josephs-iMac Auto-GPT % ./run agent create _              
😞 Agent name '_' is not valid. It should not contain spaces or special characters other than -_
sublimeaquatics@Josephs-iMac Auto-GPT %

**Comment by wangyf456** [comment]
I have a same issue.

**Comment by Mousasan97** [comment]
Same since last Friday

**Comment by Bentlybro** [comment]
I believe this has since been fixed in #6108 which was added today, id recommend updating and trying again

**Comment by Bentlybro** [comment]
Hey has there been any update to this after it was fixed? if everything works we can close this Issue if not please come back and let me know
