### ISSUE TITLE
Provide support for gpt-4 turbo (gpt-4-1106-preview)

### ISSUE THREAD

**Issue by gitthub89** [Significant-Gravitas/AutoGPT#6135]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

The option to set gpt-4-1106-preview in the .env should be allowed and thus set the gpt4 model of autogpt to this gpt-4-1106-preview (or any other available one).
Then combined with --gpt4only will let the user use only this model.

### Examples 🌈

![image](https://github.com/Significant-Gravitas/AutoGPT/assets/39517943/33046f12-765c-4cde-8116-784f2632ecc8)

### Motivation 🔦

Use the newest model available, and save money because it's cheaper as described here:
https://openai.com/blog/new-models-and-developer-products-announced-at-devday

**Comment by Bentlybro** [comment]
the new model was only just released a few hours ago, we already plan to add it some time today/tomorrow

**Comment by ph-ausseil** [comment]
The real change is actually that AutoGPT uses ChatCompletion API & a new API (Assistant API) is available & it will need a new ModelProvider such as AssistantModelProvider to benefit from this new model. Assistant API from my understanding is should be optimized for function calling (Which has to be benchmarked against ChatCompletion API).

Also this new model could or would (depends of the way you want to implement it) implements new functions such as Thread.

**Comment by abhawan888** [comment]
Waiting on this as well.


![image](https://github.com/Significant-Gravitas/AutoGPT/assets/110977698/8ffb7d80-7050-407f-ada0-c4dc3a4e188e)

**Comment by Pwuts** [comment]
Resolved in #6147

**Comment by sfxworks** [comment]
Can you put this in the stable branch please?

**Comment by jackchang1025** [comment]
Although it is supported, it still cannot be used in the docker environment I built. I found that the image did not follow the new code.

This is my docker-compose.yml file
![image](https://github.com/Significant-Gravitas/AutoGPT/assets/71494064/5797f5ac-072b-4a21-a075-755ec3ffb7ae)

Error when running
![image](https://github.com/Significant-Gravitas/AutoGPT/assets/71494064/f1dcd212-0e40-43d7-bce6-4a95b3915878)

I checked the built image file and it doesn't seem to update the code
![image](https://github.com/Significant-Gravitas/AutoGPT/assets/71494064/84bff02f-e4e1-41b4-b8a7-808e7c98ea1e)

Can the complete dokefile be displayed?
