### ISSUE TITLE
Docker CI Pipeline broken. 

### ISSUE THREAD

**Issue by Keridos** [Significant-Gravitas/AutoGPT#6191]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Docker

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Docker Images are not updated because CI builds fail. See here: https://github.com/Significant-Gravitas/AutoGPT/actions/workflows/autogpt-docker-ci.yml
The latest tag is rather outdated now.

**Comment by Bentlybro** [comment]
The issue with Docker and Poetry is known and is being looked into here https://github.com/python-poetry/poetry/issues/8548 and here https://github.com/python-poetry/poetry/pull/8549

**Comment by Pwuts** [comment]
Fixed in #6274
