### ISSUE TITLE
Meeting Error when“./run agent start …”

### ISSUE THREAD

**Issue by liangzhenbin1992** [Significant-Gravitas/AutoGPT#6200]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows Subsystem for Linux (WSL)

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

when I enter the arena，it turns out Error
~$ ./run arena enter LZB
Switched to a new branch 'arena_submission_LZB'
[arena_submission_LZB 925f63ae] LZB entering the arena
 1 file changed, 6 insertions(+)
 create mode 100644 arena/LZB.json
fatal: unable to access 'https://github.com/liangzhenbin1992/AutoGPT.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
❌ An error occurred: Command '['git', 'push', 'origin', 'arena_submission_LZB']' returned non-zero exit status 128.
M       .flake8
M       .gitattributes
M       .github/CODEOWNERS
M       .github/ISSUE_TEMPLATE/1.bug.yml
M       .github/ISSUE_TEMPLATE/2.feature.yml
M       .github/PULL_REQUEST_TEMPLATE.md
M       .github/workflows/autogpt-ci.yml
M       .github/workflows/autogpt-docker-cache-clean.yml
M       .github/workflows/autogpt-docker-ci.yml

### Upload Activity Log Content

:~$ ./run arena enter LZB
⚠️  The agent 'LZB' has already entered the arena.To update your submission, follow these steps:
1. Get the git hash of your submission by running 'git rev-parse HEAD' on the branch you want to submit to the arena.
2. Change the branch to 'arena_submission_LZB' by running 'git checkout arena_submission_LZB'.
3. Modify the 'arena/LZB.json' to include the new commit hash of your submission (the hash you got from step 1) and an up-to-date timestamp by running './run arena update LZB hash --branch x'.
Note: The '--branch' option is only needed if you want to change the branch that will be used.
     :~$ ./run agent start LZB
Traceback (most recent call last):
  File "cli.py", line 892, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "cli.py", line 276, in start
    setup_process = subprocess.Popen(["./setup"], cwd=agent_dir)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './setup'

what should I do？

**Comment by Hepburnsunsir** [comment]
I have same question
