### ISSUE TITLE
ModuleNotFoundError: No module named 'auto_gpt_plugin_template'

### ISSUE THREAD

**Issue by AliZaminShah** [Significant-Gravitas/AutoGPT#6275]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

ModuleNotFoundError: No module named 'auto_gpt_plugin_template' I am getting this error during install and I don't get any fix for this I even got other many issues but I able to fixed but this remain please fix it I am using windows 11 and python 3.11 version

### Upload Activity Log Content

ModuleNotFoundError: No module named 'auto_gpt_plugin_template'

**Comment by Pwuts** [comment]
How did you set up AutoGPT before you encountered this error?

**Comment by AliZaminShah** [comment]
I downloaded AutoGpt from github then unzip that folder with winrar after that I opened unzip folder in Visual Code and put api key in env folder then I open setup and it give me multiple errors and I able to fix them one by one but the error I mentioned on that error I unable to fix it

**Comment by bharath063** [comment]
After navigating to autogpts/autogpt folder in terminal, do the following
``` BASH
pip install poetry
poetry export -f requirements.txt -o requirements.txt --without-hashes
pip install -r requirements.txt
```

**Comment by AliZaminShah** [comment]
![autogpt1](https://github.com/Significant-Gravitas/AutoGPT/assets/54979644/bb12f97b-76ea-43e8-879f-16b2ce6deb30)
![autogpt2](https://github.com/Significant-Gravitas/AutoGPT/assets/54979644/81cf24c3-355b-46d0-8b96-138fd3af6047)

Check these screenshots I tried to install powershell and I am getting this issue.

**Comment by huaji23** [comment]
+1

**Comment by bharath063** [comment]
Sorry. I do not work on Windows.

**Comment by mtrabelsi** [comment]
this type of issues will never end, we NEED an official docker file so that it runs fine in every env

**Comment by rodrigolopezguerra** [comment]
Follow those , and having 

 docker compose run --rm auto-gpt
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/autogpt/app/cli.py", line 8, in <module>
    from autogpt.logs.config import LogFormatName
  File "/app/autogpt/logs/__init__.py", line 1, in <module>
    from .config import configure_chat_plugins, configure_logging
  File "/app/autogpt/logs/config.py", line 11, in <module>
    from auto_gpt_plugin_template import AutoGPTPluginTemplate
ModuleNotFoundError: No module named 'auto_gpt_plugin_template'

**Comment by Bentlybro** [comment]
This is being fixed as we have found the reason this is happening - https://github.com/Significant-Gravitas/AutoGPT/commit/21d4ce8d4b6251d582a81a0b2e167559c904b965

**Comment by Pwuts** [comment]
This has been fixed for all angles afaik:
* In 21d4ce8, `auto-gpt-plugin-template` was changed to a regular dependency (instead of a dev dependency), which fixes the issue for the Docker release image
* Since 6743636, `autogpt.sh` (formerly known as `run.sh`) launches the application inside the Poetry environment in which all dependencies are installed

So: I'm closing this issue as *fixed*. Please do let us know if you're having similar issues with the newest version.
