### ISSUE TITLE
Venv deleted during setup

### ISSUE THREAD

**Issue by sfxworks** [Significant-Gravitas/AutoGPT#6283]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

https://asciinema.org/a/621777

Running through the setup, it seems that somewhere in the setup process my venv is deleted, and autogpt can't run correctly.

I cannot let this run system wide. Manjaro also says,

```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
```

So I would like to use a venv here without autogpt deleting it.

**Comment by mattw0110** [comment]
I am running into this issue also

./run agent start MattAssist
Removed the poetry environment at /home/mattwhite/Documents/Projects/mGPT/venv.

[Errno 2] No such file or directory: 'python'
Setup completed successfully.
Benchmark Server starting please wait...
Agent 'MattAssist' starting please wait...

**Comment by yw5aj** [comment]
Same issue for me. Did you find a solution?

**Comment by SunwonHong96** [comment]
same here!

**Comment by ova1900** [comment]
same here
