### ISSUE TITLE
  error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by Evi233** [Significant-Gravitas/AutoGPT#6291]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

  × git clone --filter=blob:none --quiet https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template 'C:\Users\Administrator\AppData\Local\Temp\pip-install-ivqu45ka\auto-gpt-plugin-template_15441251726a494f975a4cb6b19d2fa9' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template 'C:\Users\Administrator\AppData\Local\Temp\pip-install-ivqu45ka\auto-gpt-plugin-template_15441251726a494f975a4cb6b19d2fa9' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Upload Error Log Content

  × git clone --filter=blob:none --quiet https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template 'C:\Users\Administrator\AppData\Local\Temp\pip-install-ivqu45ka\auto-gpt-plugin-template_15441251726a494f975a4cb6b19d2fa9' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/Significant-Gravitas/Auto-GPT-Plugin-Template 'C:\Users\Administrator\AppData\Local\Temp\pip-install-ivqu45ka\auto-gpt-plugin-template_15441251726a494f975a4cb6b19d2fa9' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Brianants** [comment]
相同

**Comment by ntindle** [comment]
Hey the current plug-in system is broken, there’s work in progress to fix :)
