### ISSUE TITLE
Doing No Git/Docker-setup error extracting files- cant create symlink

### ISSUE THREAD

**Issue by kangarooo** [Significant-Gravitas/AutoGPT#6353]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

![image](https://github.com/Significant-Gravitas/AutoGPT/assets/73187/2952a4db-1cb1-4b11-b842-4dd5b2424763)

**Comment by Bentlybro** [comment]
Hey are you in the discord server? discord.gg/autogpt

you ended up making 5 issues so I think its a good idea to talk in discord over this, contact me @Bentlyro in the discord
#6349 #6350 #6351 #6352 #6353
