### ISSUE TITLE
Poetry Config

### ISSUE THREAD

**Issue by hoolswelsh** [Significant-Gravitas/AutoGPT#6386]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows Subsystem for Linux (WSL)

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

 RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
    - [dependencies.agbenchmark] {'git': 'https://github.com/Significant-Gravitas/AutoGPT.git', 'subdirectory': 'benchmark', 'optional': True} is not valid under any of the given schemas
    - [dependencies.autogpt-forge] {'git': 'https://github.com/Significant-Gravitas/AutoGPT.git', 'subdirectory': 'autogpts/forge'} is not valid under any of the given schemas

  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
Setup completed successfully.
Benchmark Server starting please wait...
Agent 'autogpt' starting please wait...
user@PC:/mnt/c/Users/user/AutoGPT$ ./run: 3: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
cp: cannot stat '.env.example': No such file or directory
Please add your api keys to the .env file.

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
    - [dependencies.agbenchmark] {'git': 'https://github.com/Significant-Gravitas/AutoGPT.git', 'subdirectory': 'benchmark', 'optional': True} is not valid under any of the given schemas
    - [dependencies.autogpt-forge] {'git': 'https://github.com/Significant-Gravitas/AutoGPT.git', 'subdirectory': 'autogpts/forge'} is not valid under any of the given schemas

  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
    - [dependencies.agbenchmark] {'git': 'https://github.com/Significant-Gravitas/AutoGPT.git', 'subdirectory': 'benchmark', 'optional': True} is not valid under any of the given schemas
    - [dependencies.autogpt-forge] {'git': 'https://github.com/Significant-Gravitas/AutoGPT.git', 'subdirectory': 'autogpts/forge'} is not valid under any of the given schemas

  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]

I am currently getting this issue and I'm not sure what to do with it.

**Comment by hoolswelsh** [comment]
I have seen the entry in the trouble shoot file but I have no idea where the files are to remove.

**Comment by zedatrix** [comment]
Did you go through all the setup? did it install poetry and it's dependencies?
Also, what version of python, poetry, ubuntu, autogpt etc are you using?

**Comment by hoolswelsh** [comment]
I ended up having to install poetry myself through PIP as the set up script didnt work but now the setup script is all green anyway.

**Comment by zedatrix** [comment]
so did you get it working then or you just saying the setup went fine and you still can't start your agent?

**Comment by hoolswelsh** [comment]
Yeah sorry I should have specified that this error occurs when running ./run agent start autogpt

**Comment by zedatrix** [comment]
looks like you don't have .env file

**Comment by hoolswelsh** [comment]
How am I meant to get one, do I right it myself or should one have been auto generated?

**Comment by zedatrix** [comment]
not sure, but just copy the env.example and add your openai key and stuff

**Comment by hoolswelsh** [comment]
In that case do I have to remove the .example part from the end of the file name?

**Comment by zedatrix** [comment]
yes

**Comment by Bentlybro** [comment]
```cp: cannot stat '.env.example': No such file or directory
Please add your api keys to the .env file.```

you need to remove the ".example" from the end of the env file and make sure you add your openai api key inside

**Comment by hoolswelsh** [comment]
user@PC:/mnt/c/Users/user/AutoGPT$ ./run: 3: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
    - [dependencies.agbenchmark] {'git': 'https://github.com/Significant-Gravitas/AutoGPT.git', 'subdirectory': 'benchmark', 'optional': True} is not valid under any of the given schemas
    - [dependencies.autogpt-forge] {'git': 'https://github.com/Significant-Gravitas/AutoGPT.git', 'subdirectory': 'autogpts/forge'} is not valid under any of the given schemas



  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
    - [dependencies.agbenchmark] {'git': 'https://github.com/Significant-Gravitas/AutoGPT.git', 'subdirectory': 'benchmark', 'optional': True} is not valid under any of the given schemas
    - [dependencies.autogpt-forge] {'git': 'https://github.com/Significant-Gravitas/AutoGPT.git', 'subdirectory': 'autogpts/forge'} is not valid under any of the given schemas


  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       39│             message = ""
       41│                 message += "  - {}\n".format(error)
       42│
       40│             for error in check_result["errors"]:
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       41│                 message += "  - {}\n".format(error)
       44│
       45│         # Load package
       42│
       46│         name = local_config["name"]
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│
       45│         # Load package
       47│         version = local_config["version"]
       46│         name = local_config["name"]
       47│         version = local_config["version"]



Still get this

**Comment by Bentlybro** [comment]
did you run "./run setup" ?

**Comment by hoolswelsh** [comment]
yep runs clear 

       d8888          888             .d8888b.  8888888b. 88888888888
      d88888          888            d88P  Y88b 888   Y88b    888
     d88P888          888            888    888 888    888    888
    d88P 888 888  888 888888 .d88b.  888        888   d88P    888
   d88P  888 888  888 888   d88""88b 888  88888 8888888P"     888
  d88P   888 888  888 888   888  888 888    888 888           888
 d8888888888 Y88b 888 Y88b. Y88..88P Y88b  d88P 888           888
d88P     888  "Y88888  "Y888 "Y88P"   "Y8888P88 888           888


🚀 Setup initiated...

✅ Git is configured with name 'hoolswelsh' and email 'hoolswelsh@email.com'
✅ GitHub access token loaded successfully.
✅ GitHub access token has the required permissions.

**Comment by Bentlybro** [comment]
so if you want to make your own agent using the forge stuff you can do "./run agent create YOUR_AGENT_NAME"
and to run it, its "./run agent start YOUR_AGENT_NAME`" 

Or if you want to run AutoGPT its self id recommend checking here https://docs.agpt.co/autogpt/usage/ as it has all the latest up to date info on how to run the agent its self

**Comment by hoolswelsh** [comment]
Ok so trying to do `./run agent start autogpt` to run the autogpt supplied with the repo is wrong then?

**Comment by Bentlybro** [comment]
so it looks like you want to run the actual AutoGPT agent, to do so you need to make sure you are in the "autogpts/autogpt" dir then you run "./autogpt.sh run" and it should let you run the agent its self, all the forge stuff is for making your own agent from scratch

**Comment by zedatrix** [comment]
did you get it running?

**Comment by Bentlybro** [comment]
lil test

**Comment by atoy101** [comment]
`No poetry environment found.

  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
    - [dependencies.agbenchmark] {'git': 'https://github.com/Significant-Gravitas/AutoGPT.git', 'subdirectory': 'benchmark', 'optional': True} is not valid under any of the given schemas
  

  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       42│
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│
       45│         # Load package
       46│         name = local_config["name"]
       47│         version = local_config["version"]
Setup completed successfully.
Benchmark Server starting please wait...
Agent 'AlexsButlerBot' starting please wait...
alex@Alex-PC:/mnt/c/Users/Alex/Desktop/AutoGPT/AlexsButlerBOT$ kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]

  RuntimeError


  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
    - [dependencies.agbenchmark] {'git': 'https://github.com/Significant-Gravitas/AutoGPT.git', 'subdirectory': 'benchmark', 'optional': True} is not valid under any of the given schemas
  
  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
    - [dependencies.agbenchmark] {'git': 'https://github.com/Significant-Gravitas/AutoGPT.git', 'subdirectory': 'benchmark', 'optional': True} is not valid under any of the given schemas
  


  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
  at /usr/lib/python3/dist-packages/poetry/core/factory.py:43 in create_poetry
       39│             message = ""
       39│             message = ""
       40│             for error in check_result["errors"]:
       40│             for error in check_result["errors"]:
       41│                 message += "  - {}\n".format(error)
       41│                 message += "  - {}\n".format(error)
       42│
       42│
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│
    →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
       44│
       45│         # Load package
       45│         # Load package
       46│         name = local_config["name"]
       46│         name = local_config["name"]
       47│         version = local_config["version"]
       47│         version = local_config["version"]

`

I have this same error.  
python 3.10.12
python3-poetry is already the newest version (1.1.12+dfsg-1ubuntu1).

**Comment by kong-hana01** [comment]
I also met this problem in WSL. All versions are the same as yours.
I was trying to solve this problem, but I can't.

**Comment by Bentlybro** [comment]
I found after installing poetry it offers a command to run to set poetry as a env var so then it can be used later on, if you guys are still having this issue let me know and be sure to join the discord if you arnt already in there and we can get this fixed!

**Comment by kyza222** [comment]
@Bentlybro hey man, I could use some help please! :) still facing the poetry issue too

**Comment by kyza222** [comment]
Yeah I am sitting in one of the DEV channels and also posted to help :)

**Comment by scrip20** [comment]
I can find the solution, I still have the same problem ?

**Comment by linushahs** [comment]
@scrip20 @kyza222 I was facing the same poetry issue. I solved it by installing poetry using pipx. You can install pipx easily through terminal : sudo apt install pipx

**Comment by weiyonggang1** [comment]
> @scrip20 @kyza222 I was facing the same poetry issue. I solved it by installing poetry using pipx. You can install pipx easily through terminal : sudo apt install pipx

I tried this method, but it didn't work

**Comment by josephsctan** [comment]
I had this problem as well. The issue seems to be that poetry when installed using `sudo apt get`  is 1.1.12, and it goes into `/usr/bin/poetry`.  What you want is Poetry 1.7.xxx.

You can either install poetry 1.7.xx  with `pipx` or as follows

`curl -sSL https://install.python-poetry.org | python3` 

What that does is put poetry into your own folder *~


export PATH="/home/joseph/.local/bin:$PATH"

curl -sSL https://install.python-poetry.org | python3 -

**Comment by FalseGenius** [comment]
I had the same issue, but the following works! After creating Agent, go into virtualenv, install poetry, deactivate it and start your agent! Sounds silly, but it works. After that, you don't need to go into virtualenv to start the agent. That process is just for installing poetry.

git clone https://github.com/Significant-Gravitas/Auto-GPT.git
cd Auto-GPT
./run setup
./run agent create YOUR_AGENT_NAME

**python3 -m venv openvino_env
source openvino_env/bin/activate
pip install poetry
deactivate**
./run agent start YOUR_AGENT_NAME

**Comment by ntindle** [comment]
^

**Comment by mrbeandev** [comment]
fixed for me the actuall installation of poetry said to do this command which was wrong : 
`export PATH="/home/joseph/.local/bin:$PATH"`
the correct path was 
`/bin/`

so i copied the poetry binary to `/bin/` folder and it worked for me 👌🏻 

My os : Ubuntu 22.04.3 LTS (WSL system installed on Windows 11)
