### ISSUE TITLE
No requirements.txt

### ISSUE THREAD

**Issue by deeomnjobs** [Significant-Gravitas/AutoGPT#6432]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Where is requirements.txt?????

### Upload Activity Log Content

No such file

### Upload Error Log Content

No such file

**Comment by kangarooo** [comment]
I also am tring to follow instructions and they dont work
Reinstalled python with executable variables enabled and now another problem- file requirements.txt not found

**Comment by zedatrix** [comment]
we use poetry so requirements.txt is not going to work
