### ISSUE TITLE
python.exe: No module named autogpt 

### ISSUE THREAD

**Issue by kangarooo** [Significant-Gravitas/AutoGPT#6434]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Installed following https://agi-sphere.com/auto-gpt-install-windows/
Also did cd /docs
AutoGPTp/Auto-GPT/docs (master)
$ python -m pip install -r requirements.txt

python -m autogpt --gpt3only
C:\Users\Sir\AppData\Local\Programs\Python\Python312\python.exe: No module named autogpt

**Comment by zedatrix** [comment]
windows is not recommended. see this guide for instructions: https://docs.agpt.co/autogpt/setup/ also note - there is no requirements.txt since we use poetry
