### ISSUE TITLE
poetry install  Poetry could not find a pyproject.toml file in C:\Users\Sir\AutoGPTp\Auto-GPT or its parents

### ISSUE THREAD

**Issue by kangarooo** [Significant-Gravitas/AutoGPT#6435]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

poetry install
gives error
Poetry could not find a pyproject.toml file in C:\Users\Sir\AutoGPTp\Auto-GPT or its parents

**Comment by zedatrix** [comment]
windows is not recommended. see this guide for instructions: https://docs.agpt.co/autogpt/setup/
