### ISSUE TITLE
RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.

### ISSUE THREAD

**Issue by katmai** [Significant-Gravitas/AutoGPT#6438]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

when trying to start the agent i'm getting this.
i've already upgraded sqlite3 but it doesn't look like it's getting the right one

atlas@chia01:~/atlas_v2$ sqlite3 --version
3.44.2 2023-11-24 11:41:44 ebead0e7230cd33bcec9f95d2183069565b9e709bf745c9b5db65cc0cbf92c0f (64-bit)

And the warning is kinda correct, but not sure why it's not trying to use the system installed sqlite3 which is updated

![image](https://github.com/Significant-Gravitas/AutoGPT/assets/1245160/7325fa54-9a78-4b2a-96dc-4085f232fc7a)

i've compiled statically pysqlite3 but still no dice.

![image](https://github.com/Significant-Gravitas/AutoGPT/assets/1245160/3c75e07b-6ecd-4f19-b21f-8509f5b1c020)

so any ideas how can i get everything to use pysqlite3 with the updated sqlite3 ?

thanks.

### Upload Activity Log Content

atlas@chia01:~/atlas_v2$ ./run agent start ATLAS
Removed the poetry environment at /home/atlas/.cache/pypoetry/virtualenvs/autogpt-forge-5PJbbM74-py3.11.
Creating virtualenv autogpt-forge-5PJbbM74-py3.11 in /home/atlas/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 156 installs, 0 updates, 0 removals

  • Installing attrs (23.1.0)
  • Installing frozenlist (1.4.0)
  • Installing idna (3.4)
  • Installing multidict (6.0.4)
  • Installing six (1.16.0)
  • Installing aiosignal (1.3.1)
  • Installing asttokens (2.4.0): Installing...
  • Installing async-timeout (4.0.3)
Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
  • Installing asttokens (2.4.0)
  • Installing async-timeout (4.0.3)
  • Installing certifi (2023.7.22): Installing...
Connection pool is full, discarding connection: pypi.org. Connection pool size: 10
  • Installing charset-normalizer (3.3.0): Installing...
  • Installing certifi (2023.7.22)
  • Installing charset-normalizer (3.3.0)
  • Installing executing (2.0.0)
  • Installing h11 (0.14.0)
  • Installing outcome (1.2.0)
  • Installing parso (0.8.3)
  • Installing ptyprocess (0.7.0)
  • Installing pure-eval (0.2.2)
  • Installing sniffio (1.3.0)
  • Installing sortedcontainers (2.4.0)
  • Installing traitlets (5.11.2)
  • Installing urllib3 (2.0.7)
  • Installing wcwidth (0.2.8)
  • Installing yarl (1.9.2)
  • Installing aiohttp (3.8.6): Pending...
  • Installing anyio (4.0.0): Pending...
  • Installing backcall (0.2.0): Installing...
  • Installing decorator (5.1.1): Installing...
  • Installing filelock (3.12.4): Pending...
  • Installing backcall (0.2.0): Installing...
  • Installing anyio (4.0.0): Installing...
  • Installing backcall (0.2.0): Installing...
  • Installing decorator (5.1.1): Installing...
  • Installing filelock (3.12.4): Installing...
  • Installing aiohttp (3.8.6)
  • Installing anyio (4.0.0)
  • Installing backcall (0.2.0)
  • Installing decorator (5.1.1)
  • Installing filelock (3.12.4)
  • Installing fsspec (2023.9.2)
  • Installing hpack (4.0.0)
  • Installing humanfriendly (10.0)
  • Installing hyperframe (6.0.1)
  • Installing iniconfig (2.0.0)
  • Installing jedi (0.19.1)
  • Installing markupsafe (2.1.3)
  • Installing matplotlib-inline (0.1.6)
  • Installing mpmath (1.3.0)
  • Installing numpy (1.26.2)
  • Installing packaging (23.2)
  • Installing pexpect (4.8.0)
  • Installing pickleshare (0.7.5)
  • Installing pluggy (1.3.0)
  • Installing prompt-toolkit (3.0.39)
  • Installing pygments (2.16.1)
  • Installing pysocks (1.7.1)
  • Installing pyyaml (6.0.1)
  • Installing requests (2.31.0)
  • Installing smmap (5.0.1)
  • Installing stack-data (0.6.3)
  • Installing tqdm (4.66.1)
  • Installing trio (0.22.2)
  • Installing typing-extensions (4.8.0)
  • Installing wsproto (1.2.0)
  • Installing backoff (2.2.1): Pending...
  • Installing brotli (1.1.0): Pending...
  • Installing click (8.1.7): Pending...
  • Installing coloredlogs (15.0.1): Pending...
  • Installing contourpy (1.1.1): Pending...
  • Installing cycler (0.12.1): Pending...
  • Installing backoff (2.2.1): Installing...
  • Installing backoff (2.2.1)
  • Installing brotli (1.1.0)
  • Installing click (8.1.7)
  • Installing coloredlogs (15.0.1)
  • Installing contourpy (1.1.1)
  • Installing cycler (0.12.1)
  • Installing distlib (0.3.7)
  • Installing flatbuffers (23.5.26)
  • Installing fonttools (4.43.1)
  • Installing gitdb (4.0.10)
  • Installing h2 (4.1.0)
  • Installing httpcore (0.17.3)
  • Installing httptools (0.6.1)
  • Installing huggingface-hub (0.17.3)
  • Installing ipython (8.16.1)
  • Installing jinja2 (3.1.2)
  • Installing jsonpickle (3.0.2)
  • Installing kiwisolver (1.4.5)
  • Installing lockfile (0.12.2)
  • Installing monotonic (1.6)
  • Installing networkx (3.1)
  • Installing openai (0.27.10)
  • Installing pillow (10.1.0)
  • Installing platformdirs (3.11.0)
  • Installing protobuf (4.24.4)
  • Installing pydantic (1.10.13)
  • Installing pyhumps (3.8.0)
  • Installing pyparsing (3.1.1)
  • Installing pytest (7.4.2)
  • Installing python-dateutil (2.8.2)
  • Installing python-dotenv (1.0.0)
  • Installing pytz (2023.3.post1)
  • Installing regex (2023.10.3)
  • Installing setuptools-scm (8.0.4)
  • Installing socksio (1.0.0)
  • Installing soupsieve (2.5)
  • Installing starlette (0.27.0)
  • Installing sympy (1.12)
  • Installing trio-websocket (0.11.1)
  • Installing tzdata (2023.3)
  • Installing uvloop (0.18.0)
  • Installing watchfiles (0.21.0)
  • Installing websockets (11.0.3)
  • Installing zipp (3.17.0)
  • Installing aiofiles (23.2.1): Installing...
  • Installing appdirs (1.4.4): Installing...
  • Installing bcrypt (4.0.1): Pending...
  • Installing beautifulsoup4 (4.12.2): Pending...
  • Installing aiofiles (23.2.1)
  • Installing appdirs (1.4.4)
  • Installing bcrypt (4.0.1)
  • Installing beautifulsoup4 (4.12.2)
  • Installing cfgv (3.4.0)
  • Installing chroma-hnswlib (0.7.3)
  • Installing colorama (0.4.6)
  • Installing fastapi (0.99.1)
  • Installing gitpython (3.1.38)
  • Installing greenlet (3.0.0)
  • Installing grpcio (1.59.0)
  • Installing helicone (1.0.12)
  • Installing httpx (0.24.1)
  • Installing identify (2.5.30)
  • Installing importlib-metadata (6.8.0)
  • Installing importlib-resources (6.1.0)
  • Installing lxml (4.9.3)
  • Installing matplotlib (3.8.0)
  • Installing mccabe (0.7.0)
  • Installing mypy-extensions (1.0.0)
  • Installing nodeenv (1.8.0)
  • Installing onnxruntime (1.16.1)
  • Installing overrides (7.4.0)
  • Installing pandas (2.1.1)
  • Installing pathspec (0.11.2)
  • Installing posthog (3.0.2)
  • Installing psutil (5.9.6)
  • Installing pulsar-client (3.3.0)
  • Installing pycodestyle (2.11.1)
  • Installing pyflakes (3.1.0)
  • Installing pypika (0.48.9)
  • Installing pytest-asyncio (0.21.1)
  • Installing python-multipart (0.0.6)
  • Installing pyvis (0.3.2)
  • Installing selenium (4.14.0)
  • Installing tokenizers (0.14.1)
  • Installing tiktoken (0.5.1)
  • Installing toml (0.10.2)
  • Installing typer (0.9.0)
  • Installing types-requests (2.31.0.9)
  • Installing uvicorn (0.23.2)
  • Installing virtualenv (20.24.5)
  • Installing agbenchmark (0.0.10 8740006): Installing...
  • Installing autoflake (2.2.1): Installing...
  • Installing black (23.10.0): Pending...
  • Installing bs4 (0.0.1): Installing...
  • Installing agbenchmark (0.0.10 8740006)
  • Installing autoflake (2.2.1)
  • Installing black (23.10.0)
  • Installing bs4 (0.0.1)
  • Installing chromadb (0.4.14)
  • Installing colorlog (6.7.0)
  • Installing duckduckgo-search (3.8.5)
  • Installing flake8 (6.1.0)
  • Installing isort (5.12.0)
  • Installing litellm (0.1.824)
  • Installing mock (5.1.0)
  • Installing mypy (1.6.0)
  • Installing pre-commit (3.5.0)
  • Installing pydevd-pycharm (233.9802.6)
  • Installing sqlalchemy (2.0.22)
  • Installing tenacity (8.2.3)
  • Installing watchdog (3.0.0)
  • Installing webdriver-manager (4.0.1)
Warning: The file chosen for install of executing 2.0.0 (executing-2.0.0-py2.py3-none-any.whl) is yanked. Reason for being yanked: Released 2.0.1 which is equivalent but added 'python_requires = >=3.5' so that pip install with Python 2 uses the previous version 1.2.0.

Installing the current project: AutoGPT-Forge (0.1.0)
Setup completed successfully.
Benchmark Server starting please wait...
Agent 'ATLAS' starting please wait...

### Upload Error Log Content

atlas@chia01:~/atlas_v2$ 2430190
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [2430190]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/atlas/atlas_v2/autogpts/ATLAS/forge/__main__.py", line 6, in <module>
    import forge.sdk.forge_log
  File "/home/atlas/atlas_v2/autogpts/ATLAS/forge/sdk/__init__.py", line 26, in <module>
    from .memory.chroma_memstore import ChromaMemStore
  File "/home/atlas/atlas_v2/autogpts/ATLAS/forge/sdk/memory/__init__.py", line 1, in <module>
    from .memstore import MemStore
  File "/home/atlas/atlas_v2/autogpts/ATLAS/forge/sdk/memory/memstore.py", line 4, in <module>
    import chromadb
  File "/home/atlas/.cache/pypoetry/virtualenvs/autogpt-forge-5PJbbM74-py3.11/lib/python3.11/site-packages/chromadb/__init__.py", line 77, in <module>
    raise RuntimeError(
RuntimeError: Your system has an unsupported version of sqlite3. Chroma requires sqlite3 >= 3.35.0.
Please visit https://docs.trychroma.com/troubleshooting#sqlite to learn how to upgrade.
INFO:     Started server process [2431055]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)

**Comment by zedatrix** [comment]
i had similar issues. i was running on wsl, you wrote linux as the os.. but what distro? for me, installing the latest ubuntu for wsl made this issue go away

**Comment by katmai** [comment]
> i had similar issues. i was running on wsl, you wrote linux as the os.. but what distro? for me, installing the latest ubuntu for wsl made this issue go away

im running ubuntu 20.04 but it's my standalone home server. im not in the mood for upgrading the whole thing to ubuntu 22 to get this going. there surely must be an easier way :)) especially when the sqlite3 is there and it's updated.

**Comment by zedatrix** [comment]
idk maybe someone else can you help you, i had 20.04 too and had to install latest.. certain libraries are locked to certain os versions and distros...

**Comment by katmai** [comment]
i've started upgrading my server to ubuntu 22 
the things i do for science ...

**Comment by katmai** [comment]
We are back in business. On Ubuntu 22 it works, but it would be nice if the OS version didn't matter.

Of course things didn't work as expected, apparently on upgrade from Ubuntu 20 to 22 the network goes out, but i documented all the fixes in here: https://www.darkstarnetwork.net/no-network-after-upgrading-to-ubuntu-22-04/

**Comment by zedatrix** [comment]
told ya, just needed the latest version. i hear your frustration about needing it to work on older distros.. perhaps you can make a PR for it?

**Comment by katmai** [comment]
i don't need it to work on older versions. the code seems to try to use the updated pysqlite3 if available but for some reason it doesn't and my python ain't that good, otherwise i'd have fixed it already without needing to upgrade :)))

i mean i can always try to practice more Python: SssssssssssssssssSSSSSSSSSSSsSssSSSSSSSSSSSSSSssSSSSSSSSSSSSSSSSSsssssssssss

**Comment by zedatrix** [comment]
hahaha yep
