### ISSUE TITLE
API Key not found

### ISSUE THREAD

**Issue by DevLenn** [Significant-Gravitas/AutoGPT#6458]
### Discussed in https://github.com/Significant-Gravitas/AutoGPT/discussions/6451

<div type='discussions-op-text'>

<sup>Originally posted by **DevLenn** November 30, 2023</sup>
Hey,
i put my API Key into the .env file but AutoGPT doesn't find it. What have i've done wrong?

![image](https://github.com/Significant-Gravitas/AutoGPT/assets/138329707/3d214625-2e75-41e5-8ca1-d9b9bcefdf20)
![image](https://github.com/Significant-Gravitas/AutoGPT/assets/138329707/052dae1e-9c49-43fd-af3a-c7656ad7c206)

Ty in advance
Lenn</div>

**Comment by Bentlybro** [comment]
under the "view" dropdown, do you have "file name extensions" ticked, it will show you the fill file name as i think the ".env" is still called ".env.template"

![image](https://github.com/Significant-Gravitas/AutoGPT/assets/27962737/2ec30320-cd94-4424-9ab6-fc09a5bb6ee9)

**Comment by DevLenn** [comment]
oh yeah, ur right was using it in a VM and forgot to turn it on. As soon as my VM is back up 'n' running i'll tell you if it worked.
Ty :)
