### ISSUE TITLE
No response with a commend

### ISSUE THREAD

**Issue by CZW0042** [Significant-Gravitas/AutoGPT#6478]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

After installation, I typed .\autogpt.bat, but nothing happened.

D:\AutoGPT\AutoGPT-master (1)\AutoGPT-master\autogpts\autogpt>autogpt.sh run --help

D:\AutoGPT\AutoGPT-master (1)\AutoGPT-master\autogpts\autogpt>autogpt.bat

D:\AutoGPT\AutoGPT-master (1)\AutoGPT-master\autogpts\autogpt>autogpt.sh run --help

D:\AutoGPT\AutoGPT-master (1)\AutoGPT-master\autogpts\autogpt>.\autogpt.bat

D:\AutoGPT\AutoGPT-master (1)\AutoGPT-master\autogpts\autogpt>

**Comment by zedatrix** [comment]
Yes. Get the one from the store that doesn't have a version
