### ISSUE TITLE
我在输入pip install -r requirements.txt后 报错：Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by AganFY** [Significant-Gravitas/AutoGPT#6505]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

我在输入pip install -r requirements.txt后 报错：Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by AganFY** [comment]
1

**Comment by qnlbnsl** [comment]
project uses poetry. Use 'poetry install'

**Comment by omarshak** [comment]
Hi!
requirements.txt is inside the docs directory.

Try cd docs
Then pip install -r requirements.txt

=)
