### ISSUE TITLE
是必须使用OpenAI官网的API吗？我能使用其他标准的OpenAI的API地址和sk吗？如何修改？

### ISSUE THREAD

**Issue by itq5** [Significant-Gravitas/AutoGPT#6507]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

是必须使用OpenAI官网的API吗？我能使用其他标准的OpenAI的API地址和sk吗？如何修改？

### Upload Activity Log Content

是必须使用OpenAI官网的API吗？我能使用其他标准的OpenAI的API地址和sk吗？如何修改？

**Comment by ljc2266** [comment]
别费劲了，其他模型我试了一遍，效果都不怎么样
