### ISSUE TITLE
No module named 'autogpts'

### ISSUE THREAD

**Issue by olariuromeo** [Significant-Gravitas/AutoGPT#6520]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

ubuntu 22.04 after clone the repo and download ./run setup

       d8888          888             .d8888b.  8888888b. 88888888888 
      d88888          888            d88P  Y88b 888   Y88b    888     
     d88P888          888            888    888 888    888    888     
    d88P 888 888  888 888888 .d88b.  888        888   d88P    888     
   d88P  888 888  888 888   d88""88b 888  88888 8888888P"     888     
  d88P   888 888  888 888   888  888 888    888 888           888     
 d8888888888 Y88b 888 Y88b. Y88..88P Y88b  d88P 888           888     
d88P     888  "Y88888  "Y888 "Y88P"   "Y8888P88 888           888     
                                                                                                                                       

🚀 Setup initiated...

✅ Git is configured with name 'test' and email 'test@mail.com'
✅ GitHub access token loaded successfully.
✅ GitHub access token has the required permissions.
test@office:~/apps/test$ ./run agent create test
🎉 New agent 'test' created. The code for your new agent is in: autogpts/test
test@office:~/apps/test$ ./run agent start test
Removed the poetry environment at /home/test/.cache/pypoetry/virtualenvs/autogpt-forge-toaPsjvO-py3.10.
Creating virtualenv autogpt-forge-toaPsjvO-py3.10 in /home/test/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 169 installs, 1 update, 0 removals

  • Installing attrs (23.1.0)
  • Installing frozenlist (1.4.0)
  • Installing idna (3.4)
  • Installing multidict (6.0.4)
  • Installing pyasn1 (0.5.1)
  • Installing six (1.16.0)
  • Installing aiosignal (1.3.1)
  • Installing asttokens (2.4.0)
  • Installing async-timeout (4.0.3)
  • Installing cachetools (5.3.2)
  • Installing certifi (2023.7.22)
  • Installing charset-normalizer (3.3.0)
  • Installing exceptiongroup (1.1.3)
  • Installing executing (2.0.0)
  • Installing h11 (0.14.0)
  • Installing outcome (1.2.0)
  • Installing parso (0.8.3)
  • Installing protobuf (4.24.4)
  • Installing ptyprocess (0.7.0)
  • Installing pure-eval (0.2.2)
  • Installing pyasn1-modules (0.3.0)
  • Installing rsa (4.9)
  • Installing sortedcontainers (2.4.0)
  • Installing sniffio (1.3.0)
  • Installing traitlets (5.11.2)
  • Installing urllib3 (2.0.7)
  • Installing wcwidth (0.2.8)
  • Installing yarl (1.9.2)
  • Installing aiohttp (3.8.6)
  • Installing anyio (4.0.0)
  • Installing backcall (0.2.0)
  • Installing decorator (5.1.1)
  • Installing filelock (3.12.4)
  • Installing fsspec (2023.9.2)
  • Installing google-auth (2.25.1)
  • Installing googleapis-common-protos (1.61.0)
  • Installing hpack (4.0.0)
  • Installing humanfriendly (10.0)
  • Installing hyperframe (6.0.1)
  • Installing iniconfig (2.0.0)
  • Installing jedi (0.19.1)
  • Installing markupsafe (2.1.3)
  • Installing matplotlib-inline (0.1.6)
  • Installing mpmath (1.3.0)
  • Installing numpy (1.26.2)
  • Installing packaging (23.2)
  • Installing pexpect (4.8.0)
  • Installing pickleshare (0.7.5)
  • Installing pluggy (1.3.0)
  • Installing prompt-toolkit (3.0.39)
  • Installing pygments (2.16.1)
  • Installing pysocks (1.7.1)
  • Installing pyyaml (6.0.1)
  • Installing requests (2.31.0)
  • Downgrading setuptools (69.0.2 -> 68.2.2)
  • Installing smmap (5.0.1)
  • Installing stack-data (0.6.3)
  • Installing tomli (2.0.1)
  • Installing tqdm (4.66.1)
  • Installing trio (0.22.2)
  • Installing typing-extensions (4.8.0)
  • Installing wsproto (1.2.0)
  • Installing backoff (2.2.1)
  • Installing brotli (1.1.0)
  • Installing click (8.1.7)
  • Installing coloredlogs (15.0.1)
  • Installing contourpy (1.1.1)
  • Installing cycler (0.12.1)
  • Installing distlib (0.3.7)
  • Installing flatbuffers (23.5.26)
  • Installing fonttools (4.43.1)
  • Installing gitdb (4.0.10)
  • Installing google-api-core (2.14.0)
  • Installing google-crc32c (1.5.0)
  • Installing h2 (4.1.0)
  • Installing httpcore (0.17.3)
  • Installing httptools (0.6.1)
  • Installing huggingface-hub (0.17.3)
  • Installing ipython (8.16.1)
  • Installing jinja2 (3.1.2)
  • Installing jsonpickle (3.0.2)
  • Installing kiwisolver (1.4.5)
  • Installing lockfile (0.12.2)
  • Installing monotonic (1.6)
  • Installing networkx (3.1)
  • Installing openai (0.27.10)
  • Installing pillow (10.1.0)
  • Installing platformdirs (3.11.0)
  • Installing pydantic (1.10.13)
  • Installing pyhumps (3.8.0)
  • Installing pyparsing (3.1.1)
  • Installing pytest (7.4.2)
  • Installing python-dateutil (2.8.2)
  • Installing python-dotenv (1.0.0)
  • Installing pytz (2023.3.post1)
  • Installing regex (2023.10.3)
  • Installing setuptools-scm (8.0.4)
  • Installing socksio (1.0.0)
  • Installing soupsieve (2.5)
  • Installing starlette (0.27.0)
  • Installing sympy (1.12)
  • Installing trio-websocket (0.11.1)
  • Installing tzdata (2023.3)
  • Installing uvloop (0.18.0)
  • Installing watchfiles (0.21.0)
  • Installing websockets (11.0.3)
  • Installing zipp (3.17.0)
  • Installing aiofiles (23.2.1)
  • Installing appdirs (1.4.4)
  • Installing bcrypt (4.0.1)
  • Installing beautifulsoup4 (4.12.2)
  • Installing cfgv (3.4.0)
  • Installing chroma-hnswlib (0.7.3)
  • Installing colorama (0.4.6)
  • Installing fastapi (0.99.1)
  • Installing gitpython (3.1.38)
  • Installing google-cloud-core (2.3.3)
  • Installing google-resumable-media (2.6.0)
  • Installing greenlet (3.0.0)
  • Installing grpcio (1.59.0)
  • Installing helicone (1.0.12)
  • Installing httpx (0.24.1)
  • Installing identify (2.5.30)
  • Installing importlib-metadata (6.8.0)
  • Installing importlib-resources (6.1.0)
  • Installing lxml (4.9.3)
  • Installing matplotlib (3.8.0)
  • Installing mccabe (0.7.0)
  • Installing mypy-extensions (1.0.0)
  • Installing nodeenv (1.8.0)
  • Installing onnxruntime (1.16.1)
  • Installing overrides (7.4.0)
  • Installing pandas (2.1.1)
  • Installing pathspec (0.11.2)
  • Installing posthog (3.0.2)
  • Installing psutil (5.9.6)
  • Installing pulsar-client (3.3.0)
  • Installing pycodestyle (2.11.1)
  • Installing pyflakes (3.1.0)
  • Installing pypika (0.48.9)
  • Installing pytest-asyncio (0.21.1)
  • Installing python-multipart (0.0.6)
  • Installing pyvis (0.3.2)
  • Installing selenium (4.14.0)
  • Installing tiktoken (0.5.1)
  • Installing tokenizers (0.14.1)
  • Installing toml (0.10.2)
  • Installing typer (0.9.0)
  • Installing types-requests (2.31.0.9)
  • Installing uvicorn (0.23.2)
  • Installing virtualenv (20.24.5)
  • Installing agbenchmark (0.0.10 8740006)
  • Installing autoflake (2.2.1)
  • Installing black (23.10.0)
  • Installing bs4 (0.0.1)
  • Installing chromadb (0.4.14)
  • Installing colorlog (6.7.0)
  • Installing duckduckgo-search (3.8.5)
  • Installing flake8 (6.1.0)
  • Installing google-cloud-storage (2.13.0)
  • Installing isort (5.12.0)
  • Installing litellm (0.1.824)
  • Installing mock (5.1.0)
  • Installing mypy (1.6.0)
  • Installing pre-commit (3.5.0)
  • Installing pydevd-pycharm (233.9802.6)
  • Installing sqlalchemy (2.0.22)
  • Installing tenacity (8.2.3)
  • Installing watchdog (3.0.0)
  • Installing webdriver-manager (4.0.1)
Warning: The file chosen for install of executing 2.0.0 (executing-2.0.0-py2.py3-none-any.whl) is yanked. Reason for being yanked: Released 2.0.1 which is equivalent but added 'python_requires = >=3.5' so that pip install with Python 2 uses the previous version 1.2.0.

Installing the current project: AutoGPT-Forge (0.1.0)
Setup completed successfully.
Benchmark Server starting please wait...
Agent 'test' starting please wait...
test@office:~/apps/test$ 39925
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
Please add your api keys to the .env file.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [39925]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/test/apps/test/autogpts/test/forge/__main__.py", line 6, in <module>
    import forge.sdk.forge_log
  File "/home/test/apps/test/autogpts/test/forge/sdk/__init__.py", line 5, in <module>
    from .agent import Agent
  File "/home/test/apps/test/autogpts/test/forge/sdk/agent.py", line 16, in <module>
    from .routes.agent_protocol import base_router
  File "/home/test/apps/test/autogpts/test/forge/sdk/routes/agent_protocol.py", line 33, in <module>
    from autogpts.forge.forge.sdk.model import *
ModuleNotFoundError: No module named 'autogpts'
INFO:     Started server process [40164]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)

### Upload Activity Log Content

no exist logs folder or logs files in main AutoGPT

### Upload Error Log Content

no logs filder in the main AutoGPT folder,

**Comment by heaversm** [comment]
Ran into similar issue with `sqlalchemy`

**Comment by Morriz** [comment]
bump

**Comment by Morriz** [comment]
;p
