### ISSUE TITLE
Error occurred while registering abilities: No module named 'forge.sdk.abilities'

### ISSUE THREAD

**Issue by Vibrat** [Significant-Gravitas/AutoGPT#6537]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Agents

### Describe your issue.

I ran into the following errors when starting forge instance.

```
Vibrat@Localhost ~ % ./run agent start forge
...
[2023-12-09 22:25:45,032] [watchfiles.main] [INFO]	📝  4 changes detected
Error occurred while registering abilities: No module named 'forge.sdk.abilities
...
```

After some debugging time, I think the issue is located in **ActionRegister** when it tries to import the `missing` **abilities** module. This currently prevent the forge model to have abilities.

```
module = importlib.import_module(
        f".{action[:-3]}", package="forge.sdk.abilities"
)
```

**Comment by heishen666** [comment]
I also have this problem, is there a solution?

**Comment by magfrump** [comment]
Looks like it's coming from [this commit](https://github.com/Significant-Gravitas/AutoGPT/commit/78f5ff17e695f2e5b8ed31f729fa47ae05c19822); a couple of imports have broken.

in `registry.py`, `forge.sdk.abilities` needs to be replaced with `forge.actions`. Then in `finish.py` in the same folder the first import needs to be changed from `from sdk.forge_log import ForgeLogger` to `from forge.sdk.forge_log import ForgeLogger`

This has moved me on to a delightful new error that seems to have been introduced by the same commit.

**Comment by klsdjft** [comment]
> Looks like it's coming from [this commit](https://github.com/Significant-Gravitas/AutoGPT/commit/78f5ff17e695f2e5b8ed31f729fa47ae05c19822); a couple of imports have broken.
> 
> in `registry.py`, `forge.sdk.abilities` needs to be replaced with `forge.actions`. Then in `finish.py` in the same folder the first import needs to be changed from `from sdk.forge_log import ForgeLogger` to `from forge.sdk.forge_log import ForgeLogger`
> 
> This has moved me on to a delightful new error that seems to have been introduced by the same commit.

It works for me, Thx!

**Comment by klsdjft** [comment]
> Looks like it's coming from [this commit](https://github.com/Significant-Gravitas/AutoGPT/commit/78f5ff17e695f2e5b8ed31f729fa47ae05c19822); a couple of imports have broken.
> 
> in `registry.py`, `forge.sdk.abilities` needs to be replaced with `forge.actions`. Then in `finish.py` in the same folder the first import needs to be changed from `from sdk.forge_log import ForgeLogger` to `from forge.sdk.forge_log import ForgeLogger`
> 
> This has moved me on to a delightful new error that seems to have been introduced by the same commit.

It works for me, appreciation~

**Comment by dek4dron** [comment]
It works for me too, appreciation~

**Comment by dek4dron** [comment]
klsdjft



> > Looks like it's coming from [this commit](https://github.com/Significant-Gravitas/AutoGPT/commit/78f5ff17e695f2e5b8ed31f729fa47ae05c19822); a couple of imports have broken.
> > in `registry.py`, `forge.sdk.abilities` needs to be replaced with `forge.actions`. Then in `finish.py` in the same folder the first import needs to be changed from `from sdk.forge_log import ForgeLogger` to `from forge.sdk.forge_log import ForgeLogger`
> > This has moved me on to a delightful new error that seems to have been introduced by the same commit.
> 
> It works for me, appreciation~

Notice that it has 2 finish.py files
registry there are also 2 but there is only need to change in 1 registry.
As for the finish, it has to be changed

**Comment by curtisblackwell** [comment]
> Looks like it's coming from [this commit](https://github.com/Significant-Gravitas/AutoGPT/commit/78f5ff17e695f2e5b8ed31f729fa47ae05c19822); a couple of imports have broken.
> 
> in `registry.py`, `forge.sdk.abilities` needs to be replaced with `forge.actions`. Then in `finish.py` in the same folder the first import needs to be changed from `from sdk.forge_log import ForgeLogger` to `from forge.sdk.forge_log import ForgeLogger`
> 
> This has moved me on to a delightful new error that seems to have been introduced by the same commit.

Is this the new error others are seeing?

```
NameError: name 'PromptEngine' is not defined
```

**Comment by mansurmetocrm** [comment]
why thoe docs aren't updated ?
