### ISSUE TITLE
web_search command always returns [] in AutoGPT v0.4.7

### ISSUE THREAD

**Issue by TechnicalParadox** [Significant-Gravitas/AutoGPT#6553]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Commands

### Describe your issue.

Any attempt to use the web_search command returns []

I used the run.bat which installed all dependencies but the web_search command will simply not work.

**Comment by zedatrix** [comment]
this is a dependency version issue. fix should be soon: https://github.com/Significant-Gravitas/AutoGPT/pull/6557
