### ISSUE TITLE
You'll need to modify execute_step to include LLM behavior.  Follow the tutorial if confused.

### ISSUE THREAD

**Issue by heishen666** [Significant-Gravitas/AutoGPT#6556]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

You'll need to
modify execute_step to include LLM behavior.  Follow the tutorial if confused.

### Upload Error Log Content

You'll need to
modify execute_step to include LLM behavior.  Follow the tutorial if confused.

**Comment by se4ai4se** [comment]
Having the same issue and don't see no tutorial.

**Comment by mforoozandeh** [comment]
Output should be placeholder text Washington D.C. You'll need to 
modify execute_step to include LLM behavior. Follow the tutorial if confused.
