### ISSUE TITLE
github_access_token 

### ISSUE THREAD

**Issue by asilvy90** [Significant-Gravitas/AutoGPT#6606]
How do i input my github access token ? IDK how to Open the '.github_access_token' file in the same directory as this script and paste the token into this file.

**Comment by Bentlybro** [comment]
Just open the `.github_access_token` file in a text editor like notepad or vs code and paste it in

**Comment by asilvy90** [comment]
i saved it in vs code in the autogpt file. however it is still not recognizing, and also I am having issues configuring my username and email. can you please show me an example of how it should be written in terminal?

**Comment by asilvy90** [comment]
i managed to get my username and email configured. but i am still trying to figure out how the github access token

**Comment by asilvy90** [comment]
figured it out. tysm :)

**Comment by asilvy90** [comment]
figured it out. tysm :)
