### ISSUE TITLE
Error with auto-gpt installation

### ISSUE THREAD

**Issue by asilvy90** [Significant-Gravitas/AutoGPT#6617]
I am following the instructions to install auto-gpt, however it is saying that there is an issue with the installation:

❌ There was an issue with the installation.
✅ Git is configured with name 'Judah' and email 'asilvy@outlook.com'
✅ GitHub access token loaded successfully.
✅ GitHub access token has the required permissions.

What can i do?

**Comment by yanksyoon** [comment]
You should attach any logs that are output from the cli.
