### ISSUE TITLE
express-openai-validator Not found Error

### ISSUE THREAD

**Issue by aibysid** [Significant-Gravitas/AutoGPT#6627]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

While trying to run Evo.ninja agent there is an issue when you try to hit localhost:8000 , the issue comes after following all the steps correctly to run evo.ninja agent . Below are the details:

Not Found: not found
    at /workspaces/AutoGPT/autogpts/evo.ninja/node_modules/express-openapi-validator/dist/middlewares/openapi.metadata.js:49:19
    at /workspaces/AutoGPT/autogpts/evo.ninja/node_modules/express-openapi-validator/dist/openapi.validator.js:127:24
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

### Upload Error Log Content

Not Found: not found
    at /workspaces/AutoGPT/autogpts/evo.ninja/node_modules/express-openapi-validator/dist/middlewares/openapi.metadata.js:49:19
    at /workspaces/AutoGPT/autogpts/evo.ninja/node_modules/express-openapi-validator/dist/openapi.validator.js:127:24
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by ww185066** [comment]
Hi @aibysid did you ever find a fix for this?
