### ISSUE TITLE
I know how to install it, but I don't know how to uninstall it.

### ISSUE THREAD

**Issue by arstum** [Significant-Gravitas/AutoGPT#6633]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I know how to install it, but I don't know how to uninstall it.

**Comment by josh-ag** [comment]
What Linux distro was it you use?

**Comment by ntindle** [comment]
Delete the folder its in
