### ISSUE TITLE
怎么去登录呢？

### ISSUE THREAD

**Issue by zhangwzhang** [Significant-Gravitas/AutoGPT#6662]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I have found that there is no problem accessing from localhost, but from any IP outside of this, the following issues will occur: 1. Github login pop-up crashes; 2. Google login prompt 400: redirect_ Uri_ Mismatch

### Examples 🌈

Normal access to localhost: 8000,
Set localhost to 0.0.0.0, my IP is 192.168.106.132
However, although accessing 192.168.106.132 can open a webpage, clicking on Google or GitHub login will cause the above problem.

**Comment by l1k3beef** [comment]
I met same issues

**Comment by VajraK** [comment]
yes, same

**Comment by zhangwzhang** [comment]
> yes, same (I'm running it on a remote server btw)
Can you successfully run it?

**Comment by VajraK** [comment]
well I can run it, technically, but am stuck on that authorization of google/github, where it won't let me through...
god...
