### ISSUE TITLE
Add an option to run locally without authentication

### ISSUE THREAD

**Issue by lukolszewski** [Significant-Gravitas/AutoGPT#6676]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Have a config option to disable login.

### Examples 🌈

Any other web app.

### Motivation 🔦

Not everyone wants to set up oauth, generate github tokens etc for an app they just want to test briefly locally. IT would be much better to be able to use this without having to "sign up" to access a locally running app.

**Comment by rcastagno** [comment]
I second the request. There's no option to disable login, and no compelling reason for why it's needed in the first place.
