### ISSUE TITLE
Sign in with Google :  Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by taka11japan** [Significant-Gravitas/AutoGPT#6708]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows Subsystem for Linux (WSL)

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

[2024-01-13 16:41:48,209] [__main__       ] [INFO]      📝  Agent server starting on http://localhost:8000 

The setup is complete, and when I enter the command ./run agent start AgentName, the site at http://localhost:8000 opens. There are buttons for ‘Sign in with Google’ and ‘Sign in with GitHub’, but when I select the ‘Sign in with Google’ button, the following error is displayed and I cannot sign in. 
--Access blocked: The request from this app is invalid
-- Error 400: redirect_uri_mismatch

When I press the ‘Sign in with GitHub’ button, nothing is displayed and I cannot sign in.

 Is there something missing in the settings?

**Comment by taka11japan** [comment]
Terminal infomation.

Agent server starting on http://localhost:8000
INFO:     Started server process [93330]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:     127.0.0.1:35146 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:35150 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51066 - "GET / HTTP/1.1" 404 Not Found

**Comment by taka11japan** [comment]
IDE is Visual Studio Code.

**Comment by ReRubis** [comment]
I got the same issue when I was trying to do devcontainers on Mac.
Without the devcontainers it works fine.
I suppose it has to do something with the docker containers network and routing. 
But I might be wrong here.

**Comment by taka11japan** [comment]
I have docker installed, but the situation was the same after killing the process.

**Comment by Neatik** [comment]
The problem has not yet been resolved.

**Comment by Code-WSY** [comment]
The problem has not yet been resolved.
