### ISSUE TITLE
I can't configure git user: Git user is not configured 

### ISSUE THREAD

**Issue by LitoS3** [Significant-Gravitas/AutoGPT#6722]
Hello everyone. My problem is that I can't configure the Git user, I have tried in wsl and in a virtual machine but nothing changed

litos3@litos3-virtual-machine:~/MyAutoGPT$ ./run setup 

       d8888          888             .d8888b.  8888888b. 88888888888 
      d88888          888            d88P  Y88b 888   Y88b    888     
     d88P888          888            888    888 888    888    888     
    d88P 888 888  888 888888 .d88b.  888        888   d88P    888     
   d88P  888 888  888 888   d88""88b 888  88888 8888888P"     888     
  d88P   888 888  888 888   888  888 888    888 888           888     
 d8888888888 Y88b 888 Y88b. Y88..88P Y88b  d88P 888           888     
d88P     888  "Y88888  "Y888 "Y88P"   "Y8888P88 888           888     
                                                                                                                                       

🚀 Setup initiated...

⚠️ Git user is not configured.
To configure Git with your user info, use the following commands:
  git config --global user.name "Your (user)name"
  git config --global user.email "Your email"
✅ GitHub access token loaded successfully.
✅ GitHub access token has the required permissions.

🔴 If you need help, please raise a ticket on GitHub at https://github.com/Significant-Gravitas/AutoGPT/issues

litos3@litos3-virtual-machine:~/MyAutoGPT$ git config --global user.name
LitoS3
litos3@litos3-virtual-machine:~/MyAutoGPT$ git config --global user.mail
"my_github_mail"

If i modify cli.py directly then autogpt exit after git authenticate

litos3@litos3-virtual-machine:~/MyAutoGPT$ ./run setup 

       d8888          888             .d8888b.  8888888b. 88888888888 
      d88888          888            d88P  Y88b 888   Y88b    888     
     d88P888          888            888    888 888    888    888     
    d88P 888 888  888 888888 .d88b.  888        888   d88P    888     
   d88P  888 888  888 888   d88""88b 888  88888 8888888P"     888     
  d88P   888 888  888 888   888  888 888    888 888           888     
 d8888888888 Y88b 888 Y88b. Y88..88P Y88b  d88P 888           888     
d88P     888  "Y88888  "Y888 "Y88P"   "Y8888P88 888           888     
                                                                                                                                       

🚀 Setup initiated...

✅ Git is configured with name 'litos3' and email 'githubmail@gmail.com'
✅ GitHub access token loaded successfully.
✅ GitHub access token has the required permissions.
litos3@litos3-virtual-machine:~/MyAutoGPT$ 

Does anyone know where the problem could be or what I'm doing wrong?

Greetings and thank you

**Comment by Tirpitz-z** [comment]
+1

**Comment by acekingke** [comment]
+1

**Comment by elishalomhub** [comment]
Same for me, any solutions ?
