### ISSUE TITLE
Investigate and Fix issue with file upload for GCS File Backend

### ISSUE THREAD

**Issue by ntindle** [Significant-Gravitas/AutoGPT#6724]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Other

### Describe your issue.

The system is unable to upload files via Agent Protocol to GCS

**Comment by Pwuts** [comment]
Fixed in 797c5bbc13e861c19c727c4d35b139e4697310b5
