### ISSUE TITLE
Sign in with GitHUB error (also with Google)

### ISSUE THREAD

**Issue by taka11japan** [Significant-Gravitas/AutoGPT#6736]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows Subsystem for Linux (WSL)

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

[2024-01-13 16:41:48,209] [main ] [INFO] 📝 Agent server starting on http://localhost:8000/

The setup is complete, and when I enter the command ./run agent start AgentName, the site at http://localhost:8000/ opens. There are buttons for ‘Sign in with Google’ and ‘Sign in with GitHub’.

When I press the ‘Sign in with GitHub’ button, nothing is displayed and I cannot sign in. ( also with Google sign in)

Is there something missing in the settings?

**Comment by virtualmemorys** [comment]
same to me, " 400： redirect_uri_mismatch".
I have register a google auth2.0 for my domainname..........

**Comment by SamthinkGit** [comment]
For me worked removing fully the agent with:
```bash 
rm -rf <AutoGPT-dir>/autogpts/<youragent>
```
And then creating it again with
```bash
./run agent create <agent_name>
```

Note that in this time I filled the `.github_access_token` file in the root directory of AutoGPT with a new token of github. (Don't know if that was effective)

**Comment by ntindle** [comment]
We only have redirects setup on localhost. Fix is to use localhost instead of 127.0.0.1 is all. Closing issue

**Comment by taka11japan** [comment]
The problem was occured again.

**Comment by TomTolleson** [comment]
Still having this problem. I register or sign-in and the page reloads in the same state with no change.

Apple M2 - Sonoma 14.6.1
AutoGPT latest release
GPT 4
