### ISSUE TITLE
first and third party plugins not working/used by autogpt v0.5.0, even though configured.

### ISSUE THREAD

**Issue by Dewanik** [Significant-Gravitas/AutoGPT#6773]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Devcontainer / Codespace

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I have cloned some first party plugins from https://github.com/Significant-Gravitas/Auto-GPT-Plugins
and some third-party plugins, and enabled it through `plugins_config.yaml ` file the autogpt cli even though find the plugin well, and lets you know if plugins are not enabled even though are cloned in plugins folder autogpt doesn't utilize these plugins on any kind of prompts edit what so ever.

**Comment by rsindall** [comment]
I am having the same problem..

**Comment by SalesforceBobLightning** [comment]
If you use "latest-dev" docker image they work
