### ISSUE TITLE
'sdk' module not found.

### ISSUE THREAD

**Issue by MKdir98** [Significant-Gravitas/AutoGPT#6821]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

In running ./run agent start to forge I'm getting `'sdk' module not found` and it seems it's happened because of [here](https://github.com/Significant-Gravitas/AutoGPT/blob/fe0923ba6c9abb42ac4df79da580e8a4391e0418/autogpts/forge/forge/actions/finish.py#L1). after I add `forge` in the start of it, it gets fixed.

### Upload Error Log Content

no module found 'sdk'

**Comment by MKdir98** [comment]
https://github.com/Significant-Gravitas/AutoGPT/pull/6822

**Comment by Git-Discord** [comment]
millfields99: Hi Bently, resending again
When I run my agent I get an error 'Error occurred while registering abilities: No module named 'sdk' '.  User @MKdir98 (above) suggested the issue was thus and made this commit:
https://github.com/Significant-Gravitas/AutoGPT/commit/f26059d17c9dd8fa8b23377614c5a5e30b8222a0

This does not work for me.

 - Posted By Discord User: millfields99 Using The Git-Discord Bot From AutoGPT's Discord Server

**Comment by Git-Discord** [comment]
mk_dir98: did you create new agent? And this happen for your agent?

 - Posted By Discord User: mk_dir98 Using The Git-Discord Bot From AutoGPT's Discord Server

**Comment by cpabod** [comment]
Getting the same error after starting from scratch with the latest on master.  I am able to run `./run setup` and and create enter and start my agent successfully. 

Running with Python 3.11.5 on an M2 Mac

**Comment by MKdir98** [comment]
We talked about this one in discord. Could you check it? https://discord.com/channels/1092243196446249134/1205789219294027826/1206565360325627904

**Comment by MKdir98** [comment]
Could you check this PR? #6822
@Pwuts

**Comment by Pwuts** [comment]
Merged #6822 -> fixed! Thanks @MKdir98!

@Swiftyos FYI
