### ISSUE TITLE
Frontend on Docker

### ISSUE THREAD

**Issue by caevv** [Significant-Gravitas/AutoGPT#6858]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Can we include the frontend build on docker?

> Frontend not found. /frontend/build/web does not exist. The frontend will not be available.

I also tried including them myself, error disappears, but port 8000 will still return `404 page not found`.

**Comment by sassanix** [comment]
I have it on here https://hub.docker.com/r/sassan/opencustomgpt

**Comment by pe-dro** [comment]
Try run `docker pull significantgravitas/auto-gpt` in the project root folder, then run autogpt normally with `docker compose run --rm auto-gpt`.

**Comment by gyzerok** [comment]
@pe-dro your proposed solution seems to work. I am able to run the frontend, but auth seems to be broken. Is there any way to disable auth?

<img width="413" alt="image" src="https://github.com/Significant-Gravitas/AutoGPT/assets/1706020/76a0e776-5e8d-4610-8d98-8b0b977ad533">

**Comment by Pwuts** [comment]
Fixed in https://github.com/Significant-Gravitas/AutoGPT/pull/7164

**Comment by 2kinto** [comment]
Same question

**Comment by cheshir** [comment]
bump
I have the same problem. 
Image latest (sha256:8b6f64a4634ebb6292698306cfc00c5a0a40f0ef06a03f107e67c41212ff6713).
I've tried with docker-compose configuration from the documentation.

**Comment by cheshir** [comment]
Frontend starts with image [latest-dev](https://hub.docker.com/layers/significantgravitas/auto-gpt/latest-dev/images/sha256-1e57d41bef5d9ec1a35e97baaf36feaa3ffe345f23eb3fcf3fb9ccbe41c34154?context=explore)
