### ISSUE TITLE
change other api

### ISSUE THREAD

**Issue by vampeter** [Significant-Gravitas/AutoGPT#6869]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Currently, the establishment of autogpt requires api secret. Now I want to change it to the company's gateway interface. How should I configure it?

**Comment by MKdir98** [comment]
> ### Duplicates
> * [x]  I have searched the existing issues
> 
> ### Summary 💡
> Currently, the establishment of autogpt requires api secret. Now I want to change it to the company's gateway interface. How should I configure it?
> 
> ### Examples 🌈
> _No response_
> 
> ### Motivation 🔦
> _No response_

Is your company's gateway interface gpt API compatible? (chat completion format)
