### ISSUE TITLE
Wsl fails

### ISSUE THREAD

**Issue by MardSilva** [Significant-Gravitas/AutoGPT#6905]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

When I fork the project, and run trough wsl, i'm facing some errors:
![image](https://github.com/Significant-Gravitas/AutoGPT/assets/18332401/aae576dc-afa7-4fdd-b5b8-96474870f28b)

**Comment by zenetio** [comment]
You need to run the setup first that will install all dependencies:
./run setup
