### ISSUE TITLE
Failed to connect to duckduckgo.com

### ISSUE THREAD

**Issue by AppleRiven** [Significant-Gravitas/AutoGPT#6943]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

WARNING  Command web_search returned an error: CommandExecutionError("_get_url() https://duckduckgo.com RequestsError: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to duckduckgo.com port 443 after 21040 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.")

### Upload Error Log Content

WARNING  Command web_search returned an error: CommandExecutionError("_get_url() https://duckduckgo.com RequestsError: Failed to perform, ErrCode: 28, Reason: 'Failed to connect to duckduckgo.com port 443 after 21040 ms: Timed out'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.")

**Comment by ChinaMjm** [comment]
I have the same problem. Has it been solved

**Comment by Bentlybro** [comment]
this is something that has been happening a lot, we are actively looking into this

**Comment by kcze** [comment]
Should be fixed soon https://github.com/Significant-Gravitas/AutoGPT/pull/7045

**Comment by Git-Discord** [comment]
mk_dir98: I just enable the google_search and use it. It's stable and better

 - Posted By Discord User: mk_dir98 Using The Git-Discord Bot From AutoGPT's Discord Server

**Comment by kcze** [comment]
This should be fixed now https://github.com/Significant-Gravitas/AutoGPT/pull/7254
