### ISSUE TITLE
Agent returns Washington D.C.

### ISSUE THREAD

**Issue by mforoozandeh** [Significant-Gravitas/AutoGPT#6959]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Agents

### Describe your issue.

I get:
Output should be placeholder text Washington D.C. You'll need to 
modify execute_step to include LLM behavior. Follow the tutorial if confused. 

I am confused and there is no tutorial! :)

### Upload Error Log Content

--

**Comment by Saintj2324** [comment]
I have the same issue

**Comment by MKdir98** [comment]
I think you run `forge` agent and it needs to change its behavior. If you want to use Autogpt please start running `autogpt` agent instead of `forge`. Please tell me if the problem was not this.

**Comment by mforoozandeh** [comment]
> I think you run `forge` agent and it needs to change its behavior. If you want to use Autogpt please start running `autogpt` agent instead of `forge`. Please tell me if the problem was not this.

How can I do this? I use
`./run agent start MY_AGENT_NAME`

Should I run `autogpt` instead?

**Comment by MKdir98** [comment]
> > I think you run `forge` agent and it needs to change its behavior. If you want to use Autogpt please start running `autogpt` agent instead of `forge`. Please tell me if the problem was not this.
> 
> How can I do this? I use `./run agent start MY_AGENT_NAME`
> 
> Should I run `autogpt` instead?

Yes `./run agent start autogpt`

**Comment by ntindle** [comment]
you are running forge, not autogpt

**Comment by Neatik** [comment]
- Installing vcrpy (5.1.0 bfd15f9): Failed

  SSLCertVerificationError

  [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

**Comment by nauen** [comment]
autogpt is just not starting.
`           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/paul/Documents/AutoGPT/AutoGPT-autogpt-v0.5.1/autogpts/autogpt/autogpt/app/cli.py", line 270, in serve
    from autogpt.app.main import run_auto_gpt_server
  File "/Users/paul/Documents/AutoGPT/AutoGPT-autogpt-v0.5.1/autogpts/autogpt/autogpt/app/main.py", line 17, in <module>
    from forge.sdk.db import AgentDB
ModuleNotFoundError: No module named 'forge.sdk'`

but new agent does:

[2024-05-24 19:24:57,784] [__main__       ] [INFO]	📝  Agent server starting on http://localhost:8000
✅ Agent application started and available on port 8000
