### ISSUE TITLE
Autogpt ran local model error.

### ISSUE THREAD

**Issue by xingwozhonghua126** [Significant-Gravitas/AutoGPT#6961]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I use lm stdio to simulate the excuse of openai, and then use autogpt to call it. Then there is a time error on the picture. I don't know what the problem is and how to fix it.

### Upload Error Log Content

![mmexport1709507447790](https://github.com/Significant-Gravitas/AutoGPT/assets/18661883/d9b0fcac-8e5d-4e1e-b9bf-d0ffff8ec440)

**Comment by MKdir98** [comment]
Maybe it's happened because local llm does not create tool_calls. I'm not sure but I think you need to turn tool_call option off.
