### ISSUE TITLE
To complete setup: Where to paste Github access token? 

### ISSUE THREAD

**Issue by weiseanchan** [Significant-Gravitas/AutoGPT#6980]
I ran "./run setup"

Poetry was setup
Git is configured with name and email

However "GitHub access token file is empty".

Steps received:
To configure your GitHub access token, follow these steps:
	1. Ensure you are logged into your GitHub account
	2. Navigate to https://github.com/settings/tokens
	3. Click on 'Generate new token'.
	4. Click on 'Generate new token (classic)'.
	5. Fill out the form to generate a new token. Ensure you select the 'repo' scope.
	6. Open the '.github_access_token' file in the same directory as this script and paste the token into this file.
	7. Save the file and run the setup command again.
_______________________

I have generated a new token however I cannot get past step 6.
I cannot find the file '.github_access_token' 

Thank you!

**Comment by llmmddCoder** [comment]
Just open the .github_access_token file. Like `vim .github_access_token`.

**Comment by akasharunabharathi** [comment]
I couldn't find the `.github_access_token` on Finder, so I did the following:

`touch .github_access_token`
`echo "YOUR_ACESS_TOKEN" > .github_access_token`
