### ISSUE TITLE
Security advisory link broken

### ISSUE THREAD

**Issue by ruiqi-zhong** [Significant-Gravitas/AutoGPT#7043]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Other

### Describe your issue.

We would like to discuss a security vulnerability; however, the link to report a vunlerability in the security policy is broken: https://github.com/Significant-Gravitas/AutoGPT/security/advisories/new . Please let us know how we can make the discussio

**Comment by ntindle** [comment]
Should be fixed.
