### ISSUE TITLE
the deletion of $ENV_PATH in autogpts/forge/setup script might fail the launching of an agent

### ISSUE THREAD

**Issue by predator17** [Significant-Gravitas/AutoGPT#7063]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Master (branch)

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

in rocky linux, when following the QUICKSTART.md in a miniconda environment, it failed to launch an agent via executing 
 `./run agent start myagent` command. 
i found the issue was caused by a script from "autogpts/forge/setup", i have no idea why it should remove the poetry environment, in my case i simply comment out the code `rm -rf $ENV_PATH` from the script, then my agent can be launched properly. 

i'd like to suggest the setup `AutoGPT/autogpts/forge/setup` script should be modified as following:
```
#!/bin/bash
OS_DISTRO=$(grep -w NAME /etc/os-release | cut -d'=' -f2 | tr -d '"')

ENV_PATH=$(poetry env info --path)

if [ "$OS_DISTRO" != "Rocky Linux" ]; then
    if [ -d "$ENV_PATH" ]; then
        rm -rf $ENV_PATH
        echo "Removed the poetry environment at $ENV_PATH."
    else
        echo "No poetry environment found."
    fi
else
    echo "Running on Rocky Linux. The poetry environment at $ENV_PATH will not be removed."
fi

 poetry install --extras benchmark
 echo "Setup completed successfully."
 exit 0
```

**Comment by 1C0D** [comment]
I'm so frustrated. No fucking tuto on how to make it work under windows step by step and clear. I found a site explaining how to make it work with docker but then the api key is never recognized. They give raw commands too with no example on how to fix options as gpt3-only. tried many things without a result.

**Comment by dbuos** [comment]
I have the same issue, MacOS and miniconda env :(
