### ISSUE TITLE
using different duckduckgo backend

### ISSUE THREAD

**Issue by amirdaaee** [Significant-Gravitas/AutoGPT#7067]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Currently, the duckduckgo_search SDK likely relies solely on DuckDuckGo's API for searches. This can lead to rate-limiting issues for applications making frequent requests.

I propose adding support for alternative duckduckgo_search SDK supported backends ([as described here](https://github.com/deedy5/duckduckgo_search?tab=readme-ov-file#1-text---text-search-by-duckduckgocom)). 

### Motivation 🔦

web_search function constantly raises rate_limit error

**Comment by ntindle** [comment]
This is what we are using, do you have a proposal to switch?
