### ISSUE TITLE
AutoGPT fails with new OpenAI Project Keys

### ISSUE THREAD

**Issue by kamil6x** [Significant-Gravitas/AutoGPT#7090]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Macos 12.6.7
Setting the OPENAI_API_KEY to a new format project based api key, causes error:
2024-04-19 18:04:16,669 ERROR  Invalid OpenAI API key! Please set your OpenAI API key in .env or as an environment variable.

Switching to legacy user API key fixes the issue.

**Comment by Pwuts** [comment]
Thanks for flagging this, will fix ASAP
