### ISSUE TITLE
Allow for Azure Blob Storage file storage backend

### ISSUE THREAD

**Issue by tylerwinn** [Significant-Gravitas/AutoGPT#7092]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

In the .env file you will be able to set 

FILE_STORAGE_BACKEND=azure
STORAGE_BUCKET=your_blob_container_name

and a new field will need to be created for the account name, and access key.
AZURE_STORAGE_ACCOUNT=storage_account_name.blob.core.windows.net
AZURE_STORAGE_ACCESS_KEY=your_access_key_here

### Examples 🌈

It would work just the same as S3 or GCS, except be based on Azure Blob storage.

### Motivation 🔦

I work at a software company that wants to start using AutoGPT. I believe I can add this functionality to the project for our use and the open source community.

**Comment by ntindle** [comment]
Go for it! Let us know in the discord if you have trouble
