### ISSUE TITLE
Security issue - Docker-compose persisted volumes

### ISSUE THREAD

**Issue by Josh-XT** [Significant-Gravitas/AutoGPT#7114]
I was just looking at the security tab and saw this warning. https://github.com/Significant-Gravitas/AutoGPT/security/advisories/GHSA-x5gj-2chr-4ch6

I'm not sure if there is a reason but I noticed that the `docker-compose.yml` and `Dockerfile` as well as the rest of the whole directory is persisted in the `docker-compose.yml` file. You should pick and choose what directories need to be persisted locally. The whole folder should not be persisted. For example, if things in `data` and `logs` folders are the important things to save, persist those instead of the whole folder. If things are saving in the root of the project, I would consider a refactor.

https://github.com/Significant-Gravitas/AutoGPT/blob/180de0c9a9ce79939a8aae2b55d01e2bf2a5becb/autogpts/autogpt/docker-compose.yml#L14-L17

**Comment by ntindle** [comment]
Please open a pr to fix
