### ISSUE TITLE
Tried to install AutoGPT since 5 days

### ISSUE THREAD

**Issue by lassos** [Significant-Gravitas/AutoGPT#7119]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

hello, tried to install autogpt on a debian bookworm system . also tried on windows but also no success

tried python 3.12, 3.11 . 

tried to install all dependendies via pip install XXXX, tried to install via peotry

seems to be this make the problems:

curl-cffi 
onnxruntime
pulsar-client

This error originates from the build backend, and is likely not a problem with poetry but with curl-cffi (0.6.2) not supporting PEP 517 builds.
Unable to find installation candidates for pulsar-client
Unable to find installation candidates for onnxruntime (1.17.1)

tried to install it since days with no succcess. maybe some could help me please

thanks and greetz lars

 uname -a
Linux  multihome 6.1.0-18-686-pae #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) i686 GNU/Linux

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm

### Upload Error Log Content

  Exception: Unsupported arch: uname_result(system='Linux', node='lars-multihome', release='6.1.0-18-686-pae', version='#1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01)', machine='i686')

  at /usr/local/lib/python3.11/site-packages/poetry/installation/chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with curl-cffi (0.6.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "curl-cffi (==0.6.2)"'.

  - Installing distlib (0.3.8)
  - Installing fastapi (0.109.2)
  - Installing gitdb (4.0.11)
  - Installing google-cloud-core (2.4.1)
  - Installing google-resumable-media (2.7.0)
  - Installing hpack (4.0.0)
  - Installing httplib2 (0.22.0)
  - Installing hyperframe (6.0.1)
  - Installing importlib-resources (6.1.1)
  - Installing jinja2 (3.1.3)
  - Installing kubernetes (29.0.0)
  - Installing langcodes (3.3.0)
  - Installing mmh3 (4.1.0)
  - Installing mypy-extensions (1.0.0)
  - Installing onnxruntime (1.17.1): Failed

  RuntimeError

  Unable to find installation candidates for onnxruntime (1.17.1)

  at /usr/local/lib/python3.11/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│
       71│             links.append(link)
       72│
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│

Cannot install onnxruntime.

  - Installing opentelemetry-instrumentation-fastapi (0.43b0)
  - Installing orjson (3.10.1)
  - Installing openai (1.8.0)
  - Installing overrides (7.4.0)
  - Installing opentelemetry-exporter-otlp-proto-grpc (1.22.0)
  - Installing pathspec (0.12.1)
  - Installing pathy (0.11.0)
  - Installing pillow (10.2.0)
  - Installing platformdirs (4.1.0)
  - Installing posthog (3.3.1)
  - Installing proto-plus (1.23.0)
  - Installing pulsar-client (3.4.0): Failed

  RuntimeError

  Unable to find installation candidates for pulsar-client (3.4.0)

  at /usr/local/lib/python3.11/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│
       71│             links.append(link)
       72│
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│

Cannot install pulsar-client.

  - Installing pyflakes (3.2.0)
  - Installing pypika (0.48.9)
  - Installing pytest (7.4.4)
  - Installing referencing (0.32.1)
  - Installing spacy-legacy (3.0.12)
  - Installing spacy-loggers (1.0.5)
  - Installing tenacity (8.2.3)
  - Installing thinc (8.1.12)
  - Installing tiktoken (0.5.2)
  - Installing tokenizers (0.15.0)
  - Installing trio-websocket (0.11.1)
  - Installing types-awscrt (0.20.0)
  - Installing uvicorn (0.23.2)

**Comment by Evilander** [comment]
Did you poetry install - then once finished "poetry shell" to get into the environment? After that, if you run autogpt.bat in the ./autogpts/autogpt folder, you should be good.

**Comment by ntindle** [comment]
you should be able to run ./run setup and then ./run agent start autogpt

**Comment by ntindle** [comment]
This should be fixed
