### ISSUE TITLE
Use Azure OpenAI with AutoGPT latest version, return 'Invalid OpenAI API key' error. Where Can I set Azure key?

### ISSUE THREAD

**Issue by 35sui-com** [Significant-Gravitas/AutoGPT#7128]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4(32k)

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I set .env and azure.yaml in AutoGPT/autogpts/autogpt.

.env content
`
OPENAI_API_KEY=14fcdXXXXX -- Azure key start without sk-,and its pattern is not like OpenAI

TELEMETRY_OPT_IN=false

USE_AZURE=True

AZURE_CONFIG_FILE=azure.yaml
`
azure.yaml content
`
azure_api_type: azure

azure_api_version: 2024-04-01-preview

azure_endpoint: https://xxxx.openai.azure.com/

azure_model_map:

    gpt-3.5-turbo-0125: gpt-35-turbo

    gpt-4-turbo-preview: gpt-4-1106-Preview

    text-embedding-3-small: text-embedding-3-small
`

when I ran ./autogpt.sh serve in AutoGPT/autogpts/autogpt, it report 
AutoGPT/autogpts/autogpt
2024-05-06 15:09:18,850 ERROR  Invalid OpenAI API key! Please set your OpenAI API key in .env or as an environment variable.
2024-05-06 15:09:18,850 INFO  You can get your key from https://platform.openai.com/account/api-keys

Where Can I set Azure key?

### Upload Activity Log Content

AutoGPT/autogpts/autogpt
2024-05-06 15:09:18,850 ERROR  Invalid OpenAI API key! Please set your OpenAI API key in .env or as an environment variable.
2024-05-06 15:09:18,850 INFO  You can get your key from https://platform.openai.com/account/api-keys

### Upload Error Log Content

AutoGPT/autogpts/autogpt
2024-05-06 15:09:18,850 ERROR  Invalid OpenAI API key! Please set your OpenAI API key in .env or as an environment variable.
2024-05-06 15:09:18,850 INFO  You can get your key from https://platform.openai.com/account/api-keys

**Comment by klonhj2015** [comment]
the same problem.

**Comment by l33tm3** [comment]
Same problem 

![image](https://github.com/Significant-Gravitas/AutoGPT/assets/94154870/b68e12ac-2e0d-42ff-bcb5-7be97ed69608)

**Comment by IthacaDream** [comment]
![image](https://github.com/Significant-Gravitas/AutoGPT/assets/1230142/8be77d44-c11f-4a35-ad79-3427c7abc4cb)

**Comment by h496022202** [comment]
same problem

**Comment by joostgrunwald** [comment]
Same problem

**Comment by foreee** [comment]
Same problem

**Comment by aaaaaxiaoli** [comment]
same problem

**Comment by trend-johnson-jao** [comment]
same problem

**Comment by foreee** [comment]
I changed the code as the screenshot below, then success to run the azure api, for the 0.5.1 version

<img width="689" alt="image" src="https://github.com/Significant-Gravitas/AutoGPT/assets/17569582/ce212fa0-d25a-4103-b234-ae7227a86f1f">
<img width="902" alt="image" src="https://github.com/Significant-Gravitas/AutoGPT/assets/17569582/81fe18ad-bdfb-4a51-8400-1d8837190149">
<img width="780" alt="image" src="https://github.com/Significant-Gravitas/AutoGPT/assets/17569582/6d06695e-0ae7-45bf-8941-5203add16f02">

**Comment by ShahrOZe69** [comment]
Please fix this issue. Having the same problem
