### ISSUE TITLE
Remove autogpts folder

### ISSUE THREAD

**Issue by Swiftyos** [Significant-Gravitas/AutoGPT#7140]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

We should remove the autogpts folder to have autogpt and forge at the top level or the repo again.

This should include:
- updating docs
- removing the cli.py
- unifying pyproject again ??? 
- Anything else can think of to make the repo more accessible 

### Motivation 🔦

The arena was a failed experiment and we should focus on simplifying the repo for new comers again.

@kcze This issue was created so we can do this at an optimal time for you given the large changes your currently doing

**Comment by ntindle** [comment]
Proposal after talking with Craig
- Move AutoGPT agent folder to top level
- Move Forge to the top level
- Add a top level folder for example-agents
- Update the CLI to create agents in example-agents or another similar folder made at runtime

**Comment by Pwuts** [comment]
Resolved by #7163
