### ISSUE TITLE
Cannot create new agent

### ISSUE THREAD

**Issue by m0zzaR** [Significant-Gravitas/AutoGPT#7143]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I keep getting this error 

😢 An error occurred: [Errno 2] No such file or directory: './arena/'

whenever I run the command ./run agent create name

I have the project set up in Linux and I was able to use ./run setup successfully.

**Comment by m0zzaR** [comment]
I fixed this issue by commenting out these lines in cli.py 

@agent.command()
@click.argument("agent_name")
def create(agent_name):
    """Create's a new agent with the agent name provided"""
    import os
    import re
    import shutil

    if not re.match(r"\w*$", agent_name):
        click.echo(
            click.style(
                f"😞 Agent name '{agent_name}' is not valid. It should not contain spaces or special characters other than -_",
                fg="red",
            )
        )
        return
    try:
        new_agent_dir = f"./autogpts/{agent_name}"
        new_agent_name = f"{agent_name.lower()}.json"

        #existing_arena_files = [name.lower() for name in os.listdir("./arena/")]

        if (
            not os.path.exists(new_agent_dir)
            #and not new_agent_name in existing_arena_files
        ):
            shutil.copytree("./autogpts/forge", new_agent_dir)
            click.echo(
                click.style(
                    f"🎉 New agent '{agent_name}' created. The code for your new agent is in: autogpts/{agent_name}",
                    fg="green",
                )
            )
        else:
            click.echo(
                click.style(
                    f"😞 Agent '{agent_name}' already exists. Enter a different name for your agent, the name needs to be unique regardless of case",
                    fg="red",
                )
            )
    except Exception as e:
        click.echo(click.style(f"😢 An error occurred: {e}", fg="red"))

**Comment by m0zzaR** [comment]
I fixed this issue by commenting out lines 102 and 106

 #existing_arena_files = [name.lower() for name in os.listdir("./arena/")]
 
 #and not new_agent_name in existing_arena_files

**Comment by ntindle** [comment]
We should have pushed a fix for this. When did you pull?

**Comment by m0zzaR** [comment]
> We should have pushed a fix for this. When did you pull?

Made a fork about 15 hours ago.

**Comment by ntindle** [comment]
> > We should have pushed a fix for this. When did you pull?
> 
> Made a fork about 15 hours ago.

Fix was 9 hours ago

**Comment by ntindle** [comment]
Fixed in https://github.com/Significant-Gravitas/AutoGPT/commit/c562b3b6a3f6b5e5f64c9cfb22cf59b3fcbf43f9
