### ISSUE TITLE
The discord link is expired.

### ISSUE THREAD

**Issue by XianWoo** [Significant-Gravitas/AutoGPT#7153]
### ⚠️ Search for existing issues first ⚠️

- [x] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Other

### Describe your issue.

Hi there, the discord link is expired. Could you update the link?

**Comment by ntindle** [comment]
Service we are using to make the logo is down. https://discord.gg/autogpt should still work

**Comment by ntindle** [comment]
Thanks!

fixed
