### ISSUE TITLE
support for gpt-4o?

### ISSUE THREAD

**Issue by jwestonmoss** [Significant-Gravitas/AutoGPT#7155]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

was wondering when this would be supported or how i might add it myself if it's just a text value in a collection.  the application rejects it on start as not being valid

**Comment by jwestonmoss** [comment]
update:  i tracked down what needs to be done here, aside from updating the openai provider

the tiktoken package needs to be updated to 0.7.0 which has gpt-4o

however it cannot be updated because autogpt-forge 0.1.0 has a hard requirement of 0.5.0 tiktoken

but if you upgrade to autogpt-forge 0.1.4 which supports a higher version of tiktoken, there are a bunch of references in the current project that are broken, forge.logging at least.  i really need to get back to work on my day job so it would be pretty cash money if someone solved this, i'm able to run locally fine by manually editing the package but its not the real fix

**Comment by aitirga** [comment]
Any updates on this?
