### ISSUE TITLE
GPT4O

### ISSUE THREAD

**Issue by aizzataffero** [Significant-Gravitas/AutoGPT#7158]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

How can i run GPT4O instead GPT4 ?

### Examples 🌈

How can i run GPT4O instead GPT4 ?

### Motivation 🔦

How can i run GPT4O instead GPT4 ?

**Comment by linuffe** [comment]
the same issue. Can we change the soure code to achieve this?
