### ISSUE TITLE
Connexion serveur locale http://localhost:8000 erreur clée API pour le service "docker-compose run --rm auto-gpt serve"

### ISSUE THREAD

**Issue by Oswald85000** [Significant-Gravitas/AutoGPT#7176]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Commands

### Describe your issue.

Hello,

I have a small problem getting the command docker-compose run --rm auto-gpt serve to work.

The local server starts but it returns two requests:

bash
Copier le code
2024-05-29 09:21:34,729 INFO  HTTP Request: GET https://api.openai.com/v1/models "HTTP/1.1 200 OK"
2024-05-29 09:21:35,118 INFO  HTTP Request: GET https://api.openai.com/v1/models "HTTP/1.1 200 OK"
2024-05-29 09:21:35,232 INFO  AutoGPT server starting on http://localhost:8000
with this message:

json
Copier le code
{
  "error": {
    "message": "You did not provide an API key. You must provide your API key in an authorization header using Bearer authentication (i.e., Authorization: Bearer YOUR_KEY). You can get an API key from https://platform.openai.com/account/api-keys.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
However, with the command docker-compose run --rm auto-gpt, the service works correctly with the API key.

I have checked several points:

The OpenAI key is valid and functional.
The command curl -X GET https://api.openai.com/v1/models -H "Authorization: Bearer (APIKEY)" correctly lists the models.
With GPT 4o i also tried including the key directly in the service environment in the docker-compose file. It was also suggested to modify the cli.py too

Do you have any ideas or suggestions? Thank you for your help! :100: 

### Upload Error Log Content

{
  "error": {
    "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY). You can obtain an API key from https://platform.openai.com/account/api-keys.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by ntindle** [comment]
Provide an api key when running in your .env or via environment variables
