### ISSUE TITLE
File paths for images in forge docs are out of date

### ISSUE THREAD

**Issue by xfq** [Significant-Gravitas/AutoGPT#7198]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Documentation

### Describe your issue.

1. Go to https://github.com/Significant-Gravitas/AutoGPT?tab=readme-ov-file#-building-blocks
2. Click [Getting Started with Forge](https://github.com/Significant-Gravitas/AutoGPT/blob/master/forge/tutorials/001_getting_started.md)
3. The images in the Markdown file are broken

**Comment by vasnt** [comment]
It seems %2F is missing in yellow lines. 
<img width="448" alt="image" src="https://github.com/user-attachments/assets/1ef7080e-20c6-4b57-b3ab-cff4debcf5f4">

**Comment by ntindle** [comment]
You can test this locally by running medics serve

**Comment by vasnt** [comment]
> You can test this locally by running medics serve

what is medics serve? could you elaborate?

**Comment by ntindle** [comment]
Autocorrect got me!
`mkdocs serve` is a command to serve the documentation locally to see if your changes work. 

Here’s the whole how to: https://docs.agpt.co/docs/
