### ISSUE TITLE
Web_search doesn’t work and needs replaced

### ISSUE THREAD

**Issue by crudo0-arch** [Significant-Gravitas/AutoGPT#7201]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-4

### Which area covers your issue best?

Other

### Describe your issue.

as title, every prompt lead to 

WARNING Command web_search returned an error: CommandExecutionError(https://links.duckduckgo.com/ /// : 202 Ratelimit')

**Comment by ntindle** [comment]
I’d be interested in replacing duck duck go at this point if anyone has ideas

**Comment by edferr** [comment]
same issue, a temporary way to disable or make the agent not be advised of the availability of duckduckgo for now would be good as well. having trouble trying to pluck the duck from the code =/

**Comment by ntindle** [comment]
You should be able to disable the command 

> DISABLED_COMMANDS: Commands to disable. Use comma separated names of commands. See the list of commands from built-in components [here](https://docs.agpt.co/autogpt/configuration/components/components.md). Default: None

**Comment by crudo0-arch** [comment]
So have someone a temporary fix to get web searching working?

**Comment by crudo0-arch** [comment]
now I can't even start autogpt, because it gives me an error about the api credentials which have not been set correctly in the .env file. But I checked and everything is set correctly. Previously it gave me the same error but asked to enter the api key into the program to open an instance. now it doesn't work...

**Comment by deedy5** [comment]
If there are problems with duckduckgo_search, you might be using an old version. 
Try updating the package:
`pip install -U duckduckgo_search`

**Comment by chriskuech** [comment]
I'm having this same issue. Did anyone find a mitigation?

**Comment by deedy5** [comment]
Versions of duckduckgo_search below 6.3 no longer work

**Comment by chriskuech** [comment]
> Versions of duckduckgo_search below 6.3 no longer work

Are you saying the official autogpt docker image has an outdated dependency? Sounds like a bug and this issue should be reopened?

**Comment by Pwuts** [comment]
Feel free to open a pull request to fix it. Updating `duckduckgo-search` would probably do it. (`poetry update duckduckgo-search`)
