### ISSUE TITLE
I agree, it seems that it can understand what tasks need to be done but then goes and does another task.

### ISSUE THREAD

**Issue by Nichebiche** [Significant-Gravitas/AutoGPT#7217]
I agree, it seems that it can understand what tasks need to be done but then goes and does another task.

ie. finds 5 websites that are relevant to your question and understands it needs to visits those sites to get more detail. But then it goes and does another google search instead of  visiting those sites.

_Originally posted by @digital-soul18 in https://github.com/Significant-Gravitas/AutoGPT/issues/305#issuecomment-1500755771_

**Comment by Bentlybro** [comment]
Closed by bentlybro
