### ISSUE TITLE
Blank Screen when Running Flutter Web Ap

### ISSUE THREAD

**Issue by jinxlo** [Significant-Gravitas/AutoGPT#7221]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

I'm trying to run the Flutter web app (AutoGPT) on my Windows 10 laptop, but instead of seeing the expected UI, I'm getting a blank screen. I'm also getting the following warnings:

Warning: In index.html:38: Local variable for "serviceWorkerVersion" is deprecated. Use "{{flutter_service_worker_version}}" template token instead.

Warning: In index.html:71: "FlutterLoader.loadEntrypoint" is deprecated. Use "FlutterLoader.load" instead.

Steps to Reproduce:

Clone the repo: git clone https://github.com/Significant-Gravitas/AutoGPT.git

Navigate to the project directory: cd AutoGPT/frontend

Run the app: flutter run -d chrome --web-port 5000

Expected Result: The app should load and display the expected UI.

Actual Result: The app loads, but the UI is blank. No error messages or loading animations are present.

Additional Information:

Flutter version: 3.22.2

Dart version: 3.4.3

OS: Windows 10

**Comment by Swiftyos** [comment]
If to develop the flutter app, this is the way to do it and you will need to debug this yourself.

If you just want to use the UI, it is automatically handled for you when you start autogpt.

If you start autogpt and go to[ 0.0.0.0:8000](http://0.0.0.0:8000) you should see the flutter app
