### ISSUE TITLE
Installment on i5 not working

### ISSUE THREAD

**Issue by mrneverend** [Significant-Gravitas/AutoGPT#7279]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Latest Release

### Do you use OpenAI GPT-3 or GPT-4?

GPT-3.5

### Which area covers your issue best?

Installation and setup

### Describe your issue.

Following all possible installation guides, reinstalling dependencies and refetching GIT still gives me the same issue: 
$ python3 -m autogpt
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/Desktop/ag/Auto-GPT/autogpt/autogpt/__main__.py", line 2, in <module>
    import autogpt.app.cli
  File "/Users/Desktop/ag/Auto-GPT/autogpt/autogpt/app/cli.py", line 7, in <module>
    from forge.logging.config import LogFormatName
ModuleNotFoundError: No module named 'forge'

I have tried everything I can and every possible solution I can find but still not working. 

Running a patched MacBook Pro with i5. Could this be the issue?

**Comment by Swiftyos** [comment]
Have you installed the dependencies using poetry and activated the poetry shell first.

Like so:

```
poetry install
poetry shell
```
