### ISSUE TITLE
After Loading an Agent, Connections Incorrectly show Input Field

### ISSUE THREAD

**Issue by aarushik93** [Significant-Gravitas/AutoGPT#7392]
When you Edit or Load a flow, the connection shows up but the input is still rendered. The behaviour is supposed to be that if a node input has a connection, that input box should be invisible<br><br>**Correct (Before Loading Agent):**

<img src="https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/0ed920ab-db0e-4b95-a4f9-ff54e962b04c/347aa139-20d6-4a8d-a6ab-c9023f7695df?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi8wZWQ5MjBhYi1kYjBlLTRiOTUtYTRmOS1mZjU0ZTk2MmIwNGMvMzQ3YWExMzktMjBkNi00YThkLWE2YWItYzkwMjNmNzY5NWRmIiwiaWF0IjoxNzIxODExMzE3LCJleHAiOjMzMjkyMzcxMzE3fQ.Av2GjBdfnOrfHj3Tfghd4eWTNuINb3tlelDf58wAAyY " alt="image.png" width="795" height="261" />

<br>Incorrect (**After Reloading the agent):**

<img src="https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/35655786-0073-4aa1-b3d9-19422c617b27/346f08e2-40d9-4c5e-92cd-38d571ac9e01?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi8zNTY1NTc4Ni0wMDczLTRhYTEtYjNkOS0xOTQyMmM2MTdiMjcvMzQ2ZjA4ZTItNDBkOS00YzVlLTkyY2QtMzhkNTcxYWM5ZTAxIiwiaWF0IjoxNzIxODExMzE3LCJleHAiOjMzMjkyMzcxMzE3fQ.o_kQxQ2S2hIw6EaHQg55Of2V4NSVJFaTqCXkrmWn17c " alt="image.png" width="863" height="306" />

~~The Agent still functions as if connected when you run it, so this is purely a visual bug.~~

~~Update: seems to be more than just visual, I'm observing intermittent behaviour where an inputted value (underneath the connection) is actually **used** instead of the connection on Graph reload.~~

~~Update 2: The non-visual aspect seems to be caused by [OPEN-1532](https://linear.app/autogpt/issue/OPEN-1532/make-pin-connections-become-the-mandatory-source-of-input-never-using)~~

**Comment by Pwuts** [comment]
After a bit of debugging, I have found out that `data.connections` as passed to the `CustomNode` components is empty after loading an existing graph.

Logically, `data.connections` should be populated based on the `edges` that are passed to `ReactFlow`. So I checked those:

`edges` as passed to the `ReactFlow` component after a fresh page load:

<img src="https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/52e6d73a-b508-4ab4-91ef-c614bd944f29/19f882ca-e8f2-42bc-985b-7b361b98c702?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi81MmU2ZDczYS1iNTA4LTRhYjQtOTFlZi1jNjE0YmQ5NDRmMjkvMTlmODgyY2EtZThmMi00MmJjLTk4NWItN2IzNjFiOThjNzAyIiwiaWF0IjoxNzIxODI1NDQ4LCJleHAiOjMzMjkyMzg1NDQ4fQ.1QvKTxlxi3ILv4Ysk8JT3eumfGkZooC65aEBZI_A09g " alt="image.png" width="748" height="231" />

after deleting and re-connecting the edge:

<img src="https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/936e94e7-7428-4871-a51c-91a5070d2f5f/80228d1b-0a86-4266-9a69-9f3f37c5a651?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi85MzZlOTRlNy03NDI4LTQ4NzEtYTUxYy05MWE1MDcwZDJmNWYvODAyMjhkMWItMGE4Ni00MjY2LTlhNjktOWYzZjM3YzVhNjUxIiwiaWF0IjoxNzIxODI1NDQ4LCJleHAiOjMzMjkyMzg1NDQ4fQ.rOs4-x-5uMXltlU98dMOz-RT9ANqBFaAT9T48jPz8Yo " alt="image.png" width="863" height="232" />

**Comment by Pwuts** [comment]
Apparently I forgot to populate `node.data.connections` in the `loadGraph` function
