### ISSUE TITLE
Where is the node? 

### ISSUE THREAD

**Issue by Zakutu** [Significant-Gravitas/AutoGPT#7456]
I may not understand the basic usage.
![image](https://github.com/user-attachments/assets/9e30616b-46ec-494b-bc3b-c4ac1526bfb6)

**Comment by Torantulino** [comment]
Hey there!

It looks like you don't have the `autogpt_server` running, **or** the frontend isn't connected to the `autogpt_server`.

Please check this tutorial for getting set up:
https://github.com/Significant-Gravitas/AutoGPT/blob/master/rnd/README.md

Make sure you end up with **2 running terminal windows** at the end of it, and keep them open.

 If you're hosting the server and builder on separate machines (or VMs), you'll need to make sure that you set the correct IP in your `.env` file.
