### ISSUE TITLE
/run setup quits at Setup initiated -> No module named 'google.cloud.logging_v2'

### ISSUE THREAD

**Issue by Nubebuster** [Significant-Gravitas/AutoGPT#7552]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Master (branch)

### What LLM Provider do you use?

Other (detail in issue)

### Which area covers your issue best?

Installation and setup

### What commit or version are you using?

56b82369b69e05a05574822a4a5cf9a26c83d23d

### Describe your issue.

/run setup quits at Setup initiated (also in a fresh clone)

I did some tinkering to install deps from the requirements.txt. But now I get 

ModuleNotFoundError: No module named 'google.cloud.logging_v2'

When trying to start my newly created agent.

Am I supposed to run setup and agent with sudo? I was not up to this point.

**Comment by hykhhijk** [comment]
I got same error my terminal output looks like this
![image](https://github.com/user-attachments/assets/85ca0ca6-537b-4b48-af4a-f18682b33e61)

and webpage output is
![image](https://github.com/user-attachments/assets/8d7f200a-7bba-48fc-b3e3-837d86520a11)

I did many messy things to install deps too.

**Comment by nbb3210** [comment]
me too
