### ISSUE TITLE
[Builder] Fix `CustomNode` deleting array items

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/AutoGPT#7561]
* Related: #7409

<img src="https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/c0032ccf-b0a8-460e-8c71-77e253b23819/36053501-8724-4973-abe6-d4af4ab60b70?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi9jMDAzMmNjZi1iMGE4LTQ2MGUtOGM3MS03N2UyNTNiMjM4MTkvMzYwNTM1MDEtODcyNC00OTczLWFiZTYtZDRhZjRhYjYwYjcwIiwiaWF0IjoxNzIxODE3OTk1LCJleHAiOjMzMjkyMzc3OTk1fQ.1cPy4Qw7uS2l-r4mU8QZuyMsEG4p4Vst-BCWTQZWPmU " alt="image.png" width="690" height="764" />

* Clicking that red button doesn't do anything
* Empty items are not filtered from the list when saved

**Comment by andrewhooker2** [comment]
Hi again @Pwuts I can happily pick this up too.

**Comment by Pwuts** [comment]
@andrewhooker2 thanks, but I'm currently working on this as it's a high priority issue.
