### ISSUE TITLE
[Builder] Fix `FlowEditor` menu styling/spacing

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/AutoGPT#7562]
<img src="https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/57526df7-0d63-4e50-95a7-97ca06e81133/f6fc8e7e-61e5-4068-987f-63ff37fd9b44?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi81NzUyNmRmNy0wZDYzLTRlNTAtOTVhNy05N2NhMDZlODExMzMvZjZmYzhlN2UtNjFlNS00MDY4LTk4N2YtNjNmZjM3ZmQ5YjQ0IiwiaWF0IjoxNzIxNzI1NjY0LCJleHAiOjMzMjkyMjg1NjY0fQ.7_a_f3AxAiNShLHjjHnzInh738YuKXO0_VicOS4xn8E " alt="image.png" width="441" height="530" />

* Maybe move this to the sidebar? Or make it non-transparent.
* Fix spacing between fields and buttons
* Add icons to buttons

**Comment by andrewhooker2** [comment]
Hey @Pwuts , I can happily pick this up
