### ISSUE TITLE
(Builder) UI Bug: Gap Appears in Sidebar When Scrolling

### ISSUE THREAD

**Issue by andrewhooker2** [Significant-Gravitas/AutoGPT#7594]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### What LLM Provider do you use?

Azure

### Which area covers your issue best?

Installation and setup

### What commit or version are you using?

c98061bc3b4a47c8c8b67383f439416c312b19d9

### Description
When scrolling down the main page, a gap appears in the left-hand sidebar that contains the list of nodes. This gap disrupts the visual layout of the sidebar.

### Screenshot
![image](https://github.com/user-attachments/assets/df87727a-087b-4409-bf32-24c2bfc67e57)

### Steps to Reproduce
- Open the application and navigate to the page with the sidebar.
- Scroll down the main page (not the sidebar).
- Observe the gap that appears in the sidebar.

### Expected Behavior
The sidebar should remain fixed without any gaps, regardless of the scrolling on the main page.

**Comment by Torantulino** [comment]
Yes! If you could pick this up that would be a huge help, we'd really appreciate it.

In my opinion you shouldn't be able to scroll the page at all.
