### ISSUE TITLE
[Builder] Add "Pan to Center" for the view on Build Screen for agents

### ISSUE THREAD

**Issue by andrewhooker2** [Significant-Gravitas/AutoGPT#7627]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

An option to pan the view to bring agents back into view on the build screen.

Currently, if users move the view too far away from their agents, they can easily lose track of them, disrupting their workflow. This feature will help users quickly reorient themselves by centering the view on their agents, enhancing the usability of the build screen.

There should be a button or keyboard shortcut that, when pressed, automatically pans the view to bring all agents back into view. This feature should smoothly transition the view to center on the agents without abrupt movements.

### Examples 🌈

A user working on a complex flow of agents accidentally moves the view far away and needs to quickly reorient the screen to continue working efficiently.

During a presentation or demo, the presenter can quickly bring the agents back into view after navigating through other parts of the build screen. When building very large flows.

Additional Context:
Here are some ideas on how this feature can be implemented:

UI Button: A button labeled "Center View on Agents" placed in the toolbar or settings menu.
For Implementation please refer to the React Flow documentation : [Link To Docs](https://reactflow.dev/api-reference/components/controls)

The [ReactFlow documentation](https://reactflow.dev/examples/interaction/zoom-transitions) provides an example of how to achieve smooth zoom and pan transitions, which can be adapted for this feature.

### Motivation 🔦

The motivation for this feature comes from the need to improve the UX when working with flows of tasks. Losing track of agents due to an off-centered view can be frustrating and time-consuming, especially when working on intricate agent building or during presentations. By providing a quick and easy way to re-center the view, users can maintain their focus and workflow without unnecessary interruptions.

**Comment by lelcruz** [comment]
I've noticed this issue and I'm interested in working on it. Would it be possible for me to pick it up?
