### ISSUE TITLE
[Documentation] Link Error Navigation 

### ISSUE THREAD

**Issue by lelcruz** [Significant-Gravitas/AutoGPT#7651]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Master (branch)

### What LLM Provider do you use?

Other (detail in issue)

### Which area covers your issue best?

Documentation

### What commit or version are you using?

e21cf5b576218cf9ef647a133ca59f6eaf31ce1b

### Describe your issue.

 The link in the "Improving Documentation" section under "Full Contributing Guide" that directs to the internal and contributor docs in the wiki leads to a 404 error page.

### Document location
[Improving documentation](https://github.com/Significant-Gravitas/AutoGPT/wiki/Contributing#improving-documentation-)

### Screenshots
![image](https://github.com/user-attachments/assets/3a15c662-e0a2-413f-b897-eacc4e3c0dc1)
![image](https://github.com/user-attachments/assets/a64e093d-8658-48bb-89f5-bdb15bb6a54c)

**Comment by ntindle** [comment]
Should point here https://github.com/Significant-Gravitas/AutoGPT/wiki

**Comment by ntindle** [comment]
Also @lelcruz let me know if you can't just edit that page. @Pwuts may need to jump in with some details on how to get you perms to edit it

**Comment by lelcruz** [comment]
@ntindle Yeah, I just tried to edit the page, but it didn't let me.

**Comment by ntindle** [comment]
Okay sounds good, I'll see if I can change it
