### ISSUE TITLE
Make 5 Example Agents

### ISSUE THREAD

**Issue by Torantulino** [Significant-Gravitas/AutoGPT#7660]
We need a few example agents to get people familiar with the system. We've had users request this, and currently we have only one.

**Comment by alexpvpmindustry** [comment]
interested in this as well

**Comment by ntindle** [comment]
@alexpvpmindustry happy to have you contribute! The docs for server have a few agents we’re looking contibutors for if you need inspiration [1] or you can reply with your ideas (or edit that and add them yourself in the other PR you made)

[1]: https://docs.agpt.co/server/new_blocks/#agent-templates-we-want-to-see

**Comment by alexpvpmindustry** [comment]
> you need inspiration [1](https://docs.agpt.co/server/new_blocks/#agent-templates-we-want-to-see)

wow. thats a big list.
will come back to this again!
