### ISSUE TITLE
[Builder] Fix Secrets being shown in the Builder

### ISSUE THREAD

**Issue by Torantulino** [Significant-Gravitas/AutoGPT#7681]
<img src="https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/a8da6289-2b95-4909-893f-871bc36938ea/1eb3aa86-d4a5-45e8-b91b-565dec893c48?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi9hOGRhNjI4OS0yYjk1LTQ5MDktODkzZi04NzFiYzM2OTM4ZWEvMWViM2FhODYtZDRhNS00NWU4LWI5MWItNTY1ZGVjODkzYzQ4IiwiaWF0IjoxNzIyNjMyMzMyLCJleHAiOjMzMjkzMTkyMzMyfQ.Jty2Gx-r4BYK3qf1w11ezu5JBDvJ3j6MnAggUnxktes " alt="image.png" width="454" height="193" />

**Comment by andrewhooker2** [comment]
@Torantulino Would you mind sharing a bit more context here on where this issue is taking place?
