### ISSUE TITLE
Check CORS rules

### ISSUE THREAD

**Issue by Swiftyos** [Significant-Gravitas/AutoGPT#7700]
<br>Cors rules for the market place are currently locked down to allow only the nextjs dev server.<br><br>This will need to be changed for cloud deployment.

See the comment on the PR:<br>[https://github.com/Significant-Gravitas/AutoGPT/pull/7657#discussion_r1704204966](https://github.com/Significant-Gravitas/AutoGPT/pull/7657#discussion_r1704204966)

**Comment by ntindle** [comment]
We have this on AutoGPT proper’s server. I think we manage the extensions cia environment variables
