### ISSUE TITLE
Implement OAuth code->token exchange routes for each service

### ISSUE THREAD

**Issue by aarushik93** [Significant-Gravitas/AutoGPT#7813]
Add token exchange endpoints for each service chosen in #7811. TODO: break this down into tickets for each service if needed.

* Blocked by #7812

Each service will need two endpoints:

1. Initiate OAuth flow and get log-in URL (#7812)
2. **Exchange code for tokens and store the newly acquired credentials** (this ticket)

Logging in and acquiring an authorization code will be done by the front end.

**Comment by Pwuts** [comment]
I'm merging this ticket into #7812
