### ISSUE TITLE
Storage of server credentials - client IDs and secrets

### ISSUE THREAD

**Issue by aarushik93** [Significant-Gravitas/AutoGPT#7814]
* Figure out & implement a straight-forward way to get the needed server credentials from env vars

TBD:

1. ~~Where to store the server credentials needed for auth for integrations (as in #7811)? Env vars?~~
2. Can we and do we want to provide server credentials for local development? Apparently GitHub tends to block pushing credentials to repos, but it could make local development much easier.
3. Should we disable the auth functionality for a service if server credentials for it are not set? (Unless an alternative auth method is available ofc - e.g. GitHub supports both OAuth and token auth)

**Comment by Pwuts** [comment]
I think to begin with I'll just let the OAuth managers for each service get the env vars directly using `os.getenv`.

**Comment by ntindle** [comment]
Use the Configs plz

**Comment by Pwuts** [comment]
How does that work
