### ISSUE TITLE
Integration with OpenAI Compatible APIs with Different Model Names

### ISSUE THREAD

**Issue by vmohan-sn** [Significant-Gravitas/AutoGPT#7942]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

I'd like to integrate with OpenAI compatible APIs like Cerebras and SambaNova. I am able to provide a base URL and API key override. However, when I input their model names, I am unable to use them due to the fact that the models are not in the base list. As a result, I get this error when I set a Smart and Fast LLM to use:

`  Input should be 'text-embedding-ada-002', 'text-embedding-3-small', 'text-embedding-3-large', 'gpt-3.5-turbo-0301', 'gpt-3.5-turbo-0613', 'gpt-3.5-turbo-16k-0613', 'gpt-3.5-turbo-1106', 'gpt-3.5-turbo-0125', 'gpt-3.5-turbo', 'gpt-3.5-turbo-16k', 'gpt-3.5-turbo', 'gpt-3.5-turbo-16k', 'gpt-4-0314', 'gpt-4-32k-0314', 'gpt-4-0613', 'gpt-4-32k-0613', 'gpt-4-1106-preview', 'gpt-4-1106-vision-preview', 'gpt-4-0125-preview', 'gpt-4-turbo-2024-04-09', 'gpt-4', 'gpt-4-32k', 'gpt-4-turbo', 'gpt-4-turbo-preview', 'gpt-4-vision-preview', 'gpt-4o-2024-05-13', 'gpt-4o', 'gpt-4', 'gpt-4-32k' or 'gpt-4o' [type=enum, input_value='Meta-Llama-3.1-405B-Instruct', input_type=str]`

Doesn't seem like there is an easy way to override and provide the names of these service providers.

**Comment by zdondada** [comment]
how did you override the base URL?

**Comment by ntindle** [comment]
You’ll need to add a new provider. The OpenAI provider is abstracted to make this easy. Take a look at open ai provider and the base OpenAI provider dor more details
