### ISSUE TITLE
When using multiple blocks with links, running the agent throws error.

### ISSUE THREAD

**Issue by navneet35371** [Significant-Gravitas/AutoGPT#8066]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

MacOS

### Which version of AutoGPT are you using?

Master (branch)

### What LLM Provider do you use?

Other (detail in issue)

### Which area covers your issue best?

Agents

### What commit or version are you using?

5a7193c

### Describe your issue.

When i try to create a agent with multiple blocks and links, it throws below error. It works fine with agent with just blocks. But linking them gives this error.

While debugging this i found it is throwing in validate graph method. The souce and sink ids are still the one's assigned in UI but the nodemap has the uuid's saved in db.

![image](https://github.com/user-attachments/assets/620749bb-f132-4ee8-b4b3-9c87ae6c5807)

`return await cls.create_graph(create_graph, is_template=False, user_id=user_id)
  File "/Users/nsuman/workspace/AutoGPT/rnd/autogpt_server/autogpt_server/server/rest_api.py", line 366, in create_graph
    graph.reassign_ids(reassign_graph_id=True)
  File "/Users/nsuman/workspace/AutoGPT/rnd/autogpt_server/autogpt_server/data/graph.py", line 146, in reassign_ids
    self.validate_graph()
  File "/Users/nsuman/workspace/AutoGPT/rnd/autogpt_server/autogpt_server/data/graph.py", line 220, in validate_graph
    raise ValueError(
ValueError: Link ('1', 'transcript') <-> ('2', 'text'), 1 is invalid node id, available nodes: dict_keys(['ec16416b-c06a-41cc-80b2-d3506d20b0f9', 'd8f6a0c3-79a4-4c2c-a3d0-256973f15728'])`

**Comment by ntindle** [comment]
@navneet35371 can you post what agent you were trying to build and how it’s connected
