### ISSUE TITLE
WARNING  Frontend not found.

### ISSUE THREAD

**Issue by wp-coin** [Significant-Gravitas/AutoGPT#8097]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows

### Which version of AutoGPT are you using?

Latest Release

### What LLM Provider do you use?

Other (detail in issue)

### Which area covers your issue best?

Installation and setup

### What commit or version are you using?

latest

### Describe your issue.

 WARNING  Frontend not found. /frontend/build/web does not exist. The frontend will not be available.

I'm on windows wsl with docker ce installed, no desktop because it consumes too much memory

as you can see in my log everything should be working except my frontend folder is not there

### Upload Activity Log Content

~/autogpt2$ docker pull significantgravitas/auto-gpt
Using default tag: latest
latest: Pulling from significantgravitas/auto-gpt
Digest: sha256:6abda195ed28cc223138002ef457ffa407f510bc1da7d750583697ae4bf5b39f
Status: Image is up to date for significantgravitas/auto-gpt:latest
docker.io/significantgravitas/auto-gpt:latest

~/autogpt2$ docker compose run --rm auto-gpt serve
WARN[0000] /home/brody/autogpt2/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Creating 1/1
 ✔ Network autogpt2_default  Created                                                                               0.2s
Path /benchmark for agbenchmark does not exist
plugins_config.yaml does not exist, creating base config.
2024-09-18 21:00:49,066 INFO  HTTP Request: GET https://api.openai.com/v1/models "HTTP/1.1 200 OK"
2024-09-18 21:00:49,874 INFO  HTTP Request: GET https://api.openai.com/v1/models "HTTP/1.1 200 OK"
2024-09-18 21:00:50,000 WARNING  Frontend not found. /frontend/build/web does not exist. The frontend will not be available.
2024-09-18 21:00:50,000 INFO  AutoGPT server starting on http://localhost:8888
^C2024-09-18 21:04:02,007 INFO  Total OpenAI session cost: $0

### Upload Error Log Content

Path /benchmark for agbenchmark does not exist

WARNING  Frontend not found. /frontend/build/web does not exist. The frontend will not be available.

**Comment by ntindle** [comment]
This is not a problem. You should find the folder only required if you want to setup the dart frontend which is generally uncommon and not recommended
