### ISSUE TITLE
folder rnd is missing

### ISSUE THREAD

**Issue by FreddyE1982** [Significant-Gravitas/AutoGPT#8127]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Windows Subsystem for Linux (WSL)

### Which version of AutoGPT are you using?

Master (branch)

### What LLM Provider do you use?

Llamafile

### Which area covers your issue best?

Installation and setup

### What commit or version are you using?

not at that pc right now

### Describe your issue.

I can not finish the setup because the folder rnd is missing in the repo for some reason

**Comment by morfidon** [comment]
First video tutorial on readme on main branch suggests using rnd folder which doesn't exist in the main branch.

I've went ahead and try using link below to use setup from here: 
https://docs.agpt.co/server/setup/

but unfortunately at the end i must find supabase folder which should be in rnd folder which is missing.

Other branches for example: [zamilmajdy](https://github.com/Significant-Gravitas/AutoGPT/tree/zamilmajdy/simplify-ai-block)
has rnd folder. 

The question is why main branch doesn't have rnd folder which is suggested to be used in installation process in readme file?

**Comment by Bentlybro** [comment]
Hey sorry guys we just did a repo restructure and are in the process of updating the docs, the rnd folder you are after has now been moved to https://github.com/Significant-Gravitas/AutoGPT/tree/master/autogpt_platform

**Comment by bjornfix** [comment]
I just tried to install it, but to no avail.
