### ISSUE TITLE
Unhandled Runtime Errors

### ISSUE THREAD

**Issue by mbruehl0828** [Significant-Gravitas/AutoGPT#8208]
### ⚠️ Search for existing issues first ⚠️

- [X] I have searched the existing issues, and there is no existing issue for my problem

### Which Operating System are you using?

Linux

### Which version of AutoGPT are you using?

Latest Release

### What LLM Provider do you use?

Azure

### Which area covers your issue best?

Installation and setup

### What commit or version are you using?

a5c63880b8a5d809892bc23c95323a6a4cc968f0

### Describe your issue.

Did a git clone, and followed the setup video and README exactly.  There were no errors during installation or docker compose. 
Upon logging in a fresh install I get 'Error' box with following message.  And when I click on 'Build' tab, there are no blocks in the menu.

![image](https://github.com/user-attachments/assets/32e184cc-b7e3-4676-9039-c1a66db95c56)

### Upload Activity Log Content

I can't find a 'logs' directory in the the AutoGPT folder...

### Upload Error Log Content

I can't find a 'logs' directory in the the AutoGPT folder...

**Comment by JJGGu** [comment]
I met the same problem...

**Comment by mohan-s-gopal** [comment]
Facing the same problem "Unhandled Runtime Error"
