### ISSUE TITLE
Include the frontend in the docker image

### ISSUE THREAD

**Issue by chriskuech** [Significant-Gravitas/AutoGPT#8323]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

This warning should be resolved by including the frontend in the image

> WARNING  Frontend not found. /frontend/build/web does not exist. The frontend will not be available.

### Motivation 🔦

I want to run autogpt as a docker image for isolation and portability.

**Comment by ntindle** [comment]
we don't intend to update classic if that's what this is about, sorry :')
