### ISSUE TITLE
Bind Ctrl/Command S to save agent on builder rather than save page

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/AutoGPT#8329]
@ntindle is this still relevant (not implemented)?

**Comment by ntindle** [comment]
don't think this is done

**Comment by Abhi1992002** [comment]
@ntindle @Pwuts Do we need to implement something so that when a user presses Ctrl/Cmd + S, a dialog box pops up allowing them to save changes?

**Comment by ntindle** [comment]
We already have save on the sidebar so we need to override the default ctrl/cmd + s to not pop up the browser's save html dialog and instead open ours
