### ISSUE TITLE
Show error if queueing graph execution fails

### ISSUE THREAD

**Issue by Pwuts** [Significant-Gravitas/AutoGPT#8332]
If clicking "Run" results in a failure, e.g. the hard-coded input values are no longer valid, this isn't visible in the UI. This can happen e.g. with credentials when they are deleted from the user but not from the graph. The execution request returns an HTTP 400 but the UI doesn't show anything.

Suggestion: show a toast (`variant="destructive"`) with the error message.

**Comment by nakul-py** [comment]
\assign

**Comment by ChineseHamberger** [comment]
Hi!

I'm a new contributor and I noticed this issue labeled as "good first issue." 

It seems that if clicking "Run" results in a failure (e.g., the hard-coded input values are no longer valid), this isn't visible in the UI. This can happen, for example, with credentials when they are deleted from the user but not from the graph. The execution request returns an HTTP 400, but the UI doesn't show anything.

The suggestion is to show a toast (variant="destructive") with the error message.

I would like to take on this issue and implement the suggested solution. Please let me know if there are any specific guidelines or steps I should follow.
