### ISSUE TITLE
[Frontend/Market] Graceful handling when no agents or featured agents

### ISSUE THREAD

**Issue by aarushik93** [Significant-Gravitas/AutoGPT#8370]
When there are no agents or featured agents returned from the backend, the marketplace breaks and won't display anything. We should handle this more gracefully<br><br>374-caa09da3d09594f2.js:14 TypeError: Cannot read properties of undefined (reading 'length') at j (page-c8cc863c15f77079.js:1:9859) at rE (fd9d1056-752c9b863fd314ce.js:1:40686) at l$ (fd9d1056-752c9b863fd314ce.js:1:59661) at iZ (fd9d1056-752c9b863fd314ce.js:1:118268) at ia (fd9d1056-752c9b863fd314ce.js:1:95507) at fd9d1056-752c9b863fd314ce.js:1:95329 at il (fd9d1056-752c9b863fd314ce.js:1:95336) at oJ (fd9d1056-752c9b863fd314ce.js:1:92692) at oZ (fd9d1056-752c9b863fd314ce.js:1:92111) at MessagePort.j (374-caa09da3d09594f2.js:1:108919)

<img src="https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/868880c4-35d3-4240-a048-2c69cba40357/23397ab6-1981-40c5-a3c2-9e79e0f6437b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi84Njg4ODBjNC0zNWQzLTQyNDAtYTA0OC0yYzY5Y2JhNDAzNTcvMjMzOTdhYjYtMTk4MS00MGM1LWEzYzItOWU3OWUwZjY0MzdiIiwiaWF0IjoxNzI5MTgyOTI0LCJleHAiOjMzMjk5NzQyOTI0fQ.SiAkHRMw23ROQq1irSGO1k-Y0RcQriYV2DuIprkAPzU " alt="Screenshot 2024-10-17 at 5.35.05 PM.png" width="1157" height="432" />

**Comment by Torantulino** [comment]
New marketplace is coming soon so we probably won't need to fix this, unless the bug follows into V2.

**Comment by aarushik93** [comment]
It was already fixed and merged thanks to @Abhi1992002
