### ISSUE TITLE
[Market] Allow use of dev marketplace in dev project

### ISSUE THREAD

**Issue by aarushik93** [Significant-Gravitas/AutoGPT#8371]
Currently, we can use only the local marketplace or the production market place. We should be able to swap the URL based on dev or prod environment in marketplace

**Comment by ntindle** [comment]
This can be done using the app env and the behave as variables

app env to tell us dev/prod and behave as to use opening the remote instance or localhost instance

**Comment by Torantulino** [comment]
@aarushi.kansal is this still an active issue?
