### ISSUE TITLE
Love for reame files.

### ISSUE THREAD

**Issue by bbarclay** [Significant-Gravitas/AutoGPT#8460]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Cleaner readme file layout. 

https://github.com/bbarclay/AutoGPT/blob/readmeupdate/README.md

You can see it here. It's a rough draft. Pull what you like. 

### Examples 🌈

https://github.com/bbarclay/AutoGPT/blob/readmeupdate/README.md

### Motivation 🔦

Because this readme file could be a lot better. With love.

**Comment by ntindle** [comment]
closing because we can't use this without agreement with the CLA :(
