### ISSUE TITLE
Research and MSc Thesis in AI on AutoGPT

### ISSUE THREAD

**Issue by czerwinskilukasz1** [Significant-Gravitas/AutoGPT#8503]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

Hello, I am helping the Computer Science department of University of Warsaw (it's the department where the co-founder of OpenAI, Wojciech Zaremba, did his BSc in Computer Science) with coordinating Master of Science thesis on AI.  We have at least one team interested in doing research in AI related to the AutoGPT project and writing a Master of Science thesis on this. 

With whom should I talk about the topic to choose?   

So far, I tried sending a connection invite on LinkedIn to Toran Bruce Richards, but it is still pending. Thank you in advance for swift replies.

### Motivation 🔦

We want to develop AI further and have great minds who want to work on it.  Our alumni are the co-founder of OpenAI and the co-founder of Snowflake Inc.

**Comment by ntindle** [comment]
Forgive me for the late reply; our discord is the right place for discussions like these. Please reach out there. https://discord.gg/autogpt
