### ISSUE TITLE
Marketplace - search results - search box reduce height to 60px

### ISSUE THREAD

**Issue by ograce1421** [Significant-Gravitas/AutoGPT#8977]
### Describe your issue.

Reduce the height of search box from 72px to 60px <img width="1554" alt="Screenshot 2024-12-13 at 20 57 15" src="https://github.com/user-attachments/assets/ac4e243f-8701-40e5-b97b-d1e3a326b004" />

**Comment by navyanihitha** [comment]
Hi @Bentlybro , Interested to work on this issue. Could this be assigned to me

**Comment by Bentlybro** [comment]
@navyanihitha I have already done most of the search results changes and have a pr that I just need to finalise, that is why i self assigned the search result issues as they are almost done, but there are loads of other issues just like this that need working on!

**Comment by navyanihitha** [comment]
Sure @Bentlybro, Thanks !
