### ISSUE TITLE
Marketplace - agent page - star rating is not visible in dark mode

### ISSUE THREAD

**Issue by ograce1421** [Significant-Gravitas/AutoGPT#9035]
### Describe your issue.

<img width="1398" alt="Screenshot 2024-12-17 at 19 26 15" src="https://github.com/user-attachments/assets/dad177a3-8af5-4336-9619-74e8b4bd9cd9" />
<img width="602" alt="Screenshot 2024-12-17 at 19 27 03" src="https://github.com/user-attachments/assets/20239766-9087-400c-bdd0-53a27f0c89db" />

Star icons are not visible when in dark mode. Please update so that the color is the same as the neighboring elements

**Comment by Pawankalyan2023** [comment]
hey can i work on this issue ?

**Comment by Pawankalyan2023** [comment]
Can I get the file name where the issue arises and how to reproduce this ?

**Comment by Swiftyos** [comment]
It's this code from `autogpt_platform/frontend/src/components/ui/icons.tsx`
 
 ```typescript
 /**
 * Generates an array of JSX elements representing star icons based on the average rating.
 *
 * @param avgRating - The average rating (0 to 5)
 * @returns An array of star icons as JSX elements
 */
export function StarRatingIcons(avgRating: number): JSX.Element[] {
  const stars: JSX.Element[] = [];
  const rating = Math.max(0, Math.min(5, avgRating));
  for (let i = 1; i <= 5; i++) {
    if (i <= rating) {
      stars.push(<IconStarFilled key={i} className="text-black" />);
    } else {
      stars.push(<IconStar key={i} className="text-black" />);
    }
  }
  return stars;
}
```


Though we just removed the dark mode toggle for todays release, so you'd need to add the dark mode toggle back in to be able to test these changes.

We will include dark mode again when all the pages look good in dark mode
