### ISSUE TITLE
Marketplace - Dialogue doesn't close after Importing an Agent from a file

### ISSUE THREAD

**Issue by Torantulino** [Significant-Gravitas/AutoGPT#9055]
<img src="https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/d65dacdb-19f2-4a68-a920-47336b30ecf6/db3abeee-20a2-4a7d-a698-6ec64ed221cb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi9kNjVkYWNkYi0xOWYyLTRhNjgtYTkyMC00NzMzNmIzMGVjZjYvZGIzYWJlZWUtMjBhMi00YTdkLWE2OTgtNmVjNjRlZDIyMWNiIiwiaWF0IjoxNzM0NTQ0MzI2LCJleHAiOjMzMzA1MTA0MzI2fQ.ywkaGnzPKr78QJaGivdkqgCXAP6DP3JMMKIvTp2jlVk " alt="image.png" width="994" data-linear-height="1036" />

When you import an agent from file the dialogue box doesn't close. You can see in the background that the agent imported successfully.

**Comment by Bentlybro** [comment]
I cant seem to replicate this, I imported an agent and it sent me to the builder page to show the agent, can you see if you can re-produce this and share any console logs/network errors?

**Comment by Torantulino** [comment]
DMed you logs from importing 4 times with the same dialogue box open.

**Comment by Torantulino** [comment]
https://github.com/user-attachments/assets/0b2e82a4-09c1-499a-a292-d6110e3220f1

Video reproducing the bug

**Comment by Torantulino** [comment]
Okay weird! I'm in Windows Chrome, what about you?

**Comment by Bentlybro** [comment]
I'm currently on windows chrome too so i'm not sure why its not working, ill do some more looking into this soon

**Comment by Torantulino** [comment]
Fixed by https://github.com/Significant-Gravitas/AutoGPT/pull/9081
