### ISSUE TITLE
Uploading files doesn't seem to work

### ISSUE THREAD

**Issue by ntindle** [Significant-Gravitas/AutoGPT#9057]
Mac w/ edge

[Screen Recording 2024-12-18 at 12.00.47 PM.mov](https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/2e19d29e-2574-48c8-a92f-933b852548d7/1e16a662-abf9-40b6-bd1e-78d1256dca60?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi8yZTE5ZDI5ZS0yNTc0LTQ4YzgtYTkyZi05MzNiODUyNTQ4ZDcvMWUxNmE2NjItYWJmOS00MGI2LWJkMWUtNzhkMTI1NmRjYTYwIiwiaWF0IjoxNzM0NTQ3MDA5LCJleHAiOjMzMzA1MTA3MDA5fQ.FtztmseGIHuYrij_vqn16UyMUWx98jk7Espa1HQ93uY)

8867-2a402ca51e72eef0.js:7

```
    POST https://dev-server.agpt.co/api/store/submissions/media 500 (Internal Server Error)
```

(anonymous) @ 8867-2a402ca51e72eef0.js:7

\_uploadFile @ 5-ba7b081277c1c064.js:1

await in \_uploadFile

uploadStoreSubmissionMedia @ 5-ba7b081277c1c064.js:1

z @ 7332-e39df91f9d3725f2.js:1

await in z

a\_ @ fd9d1056-828c50f82cd2b0be.js:1

aO @ fd9d1056-828c50f82cd2b0be.js:1

(anonymous) @ fd9d1056-828c50f82cd2b0be.js:1

sF @ fd9d1056-828c50f82cd2b0be.js:1

sM @ fd9d1056-828c50f82cd2b0be.js:1

(anonymous) @ fd9d1056-828c50f82cd2b0be.js:1

o4 @ fd9d1056-828c50f82cd2b0be.js:1

iV @ fd9d1056-828c50f82cd2b0be.js:1

sU @ fd9d1056-828c50f82cd2b0be.js:1

uO @ fd9d1056-828c50f82cd2b0be.js:1

uM @ fd9d1056-828c50f82cd2b0be.js:1

r @ 8867-2a402ca51e72eef0.js:5

8867-2a402ca51e72eef0.js:19 Error uploading image: Error: Error uploading file:

```
at n._uploadFile (5-ba7b081277c1c064.js:1:5531)

at async z (7332-e39df91f9d3725f2.js:1:7311)
```

(anonymous) @ 8867-2a402ca51e72eef0.js:19

window.console.error @ 8867-2a402ca51e72eef0.js:1

overrideMethod @ hook.js:608

z @ 7332-e39df91f9d3725f2.js:1

await in z

a\_ @ fd9d1056-828c50f82cd2b0be.js:1

aO @ fd9d1056-828c50f82cd2b0be.js:1

(anonymous) @ fd9d1056-828c50f82cd2b0be.js:1

sF @ fd9d1056-828c50f82cd2b0be.js:1

sM @ fd9d1056-828c50f82cd2b0be.js:1

(anonymous) @ fd9d1056-828c50f82cd2b0be.js:1

o4 @ fd9d1056-828c50f82cd2b0be.js:1

iV @ fd9d1056-828c50f82cd2b0be.js:1

sU @ fd9d1056-828c50f82cd2b0be.js:1

uO @ fd9d1056-828c50f82cd2b0be.js:1

uM @ fd9d1056-828c50f82cd2b0be.js:1

r @ 8867-2a402ca51e72eef0.js:5

Show 1 more frame

Show less

8867-2a402ca51e72eef0.js:7

```
    POST https://dev-server.agpt.co/api/store/submissions/media 500 (Internal Server Error)
```

(anonymous) @ 8867-2a402ca51e72eef0.js:7

\_uploadFile @ 5-ba7b081277c1c064.js:1

await in \_uploadFile

uploadStoreSubmissionMedia @ 5-ba7b081277c1c064.js:1

z @ 7332-e39df91f9d3725f2.js:1

await in z

a\_ @ fd9d1056-828c50f82cd2b0be.js:1

aO @ fd9d1056-828c50f82cd2b0be.js:1

(anonymous) @ fd9d1056-828c50f82cd2b0be.js:1

sF @ fd9d1056-828c50f82cd2b0be.js:1

sM @ fd9d1056-828c50f82cd2b0be.js:1

(anonymous) @ fd9d1056-828c50f82cd2b0be.js:1

o4 @ fd9d1056-828c50f82cd2b0be.js:1

iV @ fd9d1056-828c50f82cd2b0be.js:1

sU @ fd9d1056-828c50f82cd2b0be.js:1

uO @ fd9d1056-828c50f82cd2b0be.js:1

uM @ fd9d1056-828c50f82cd2b0be.js:1

r @ 8867-2a402ca51e72eef0.js:5

8867-2a402ca51e72eef0.js:19 Error uploading image: Error: Error uploading file:

```
at n._uploadFile (5-ba7b081277c1c064.js:1:5531)

at async z (7332-e39df91f9d3725f2.js:1:7311)
```

<img src="https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/a93150c2-97f3-4d69-911b-49c9adf2a680/63faaa3d-c663-4e26-bcf2-3629758ad910?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi9hOTMxNTBjMi05N2YzLTRkNjktOTExYi00OWM5YWRmMmE2ODAvNjNmYWFhM2QtYzY2My00ZTI2LWJjZjItMzYyOTc1OGFkOTEwIiwiaWF0IjoxNzM0NTQ3MDA5LCJleHAiOjMzMzA1MTA3MDA5fQ.bBqvlxA74Y8_JsA9slIcSx0jrkMXK4_bybUjMrymVpc " alt="image.png" width="3450" />

Server side logs 🪵 ^

**Comment by Lanny2020** [comment]
The bug is clearly still there, why was it closed?
