### ISSUE TITLE
Profile updating is handled in an insecure and potentially broken way

### ISSUE THREAD

**Issue by ntindle** [Significant-Gravitas/AutoGPT#9058]
[Screen Recording 2024-12-18 at 1.06.40 PM.mov](https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/5a583bac-e51e-486d-bffe-377fbf4bffa7/1317ede8-2094-44f9-9131-8087f18b8cce?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi81YTU4M2JhYy1lNTFlLTQ4NmQtYmZmZS0zNzdmYmY0YmZmYTcvMTMxN2VkZTgtMjA5NC00NGY5LTkxMzEtODA4N2YxOGI4Y2NlIiwiaWF0IjoxNzM0NTQ5MDI2LCJleHAiOjMzMzA1MTA5MDI2fQ.PyZIBddcdL0r8IOlgJImzdI_79CZ1x1CpvlwmGVMqLM)

The profile page doesn't handle upserting partials nor check if the user is an admin before setting the profile as featured. Additionally, the links are not saved when saving a profile.

Request: POST /store/profile from: undefined

8867-2a402ca51e72eef0.js:19 Auth token found

8867-2a402ca51e72eef0.js:19 --------------------------------

8867-2a402ca51e72eef0.js:7 POST [https://dev-server.agpt.co/api/store/profile](https://dev-server.agpt.co/api/store/profile) 422 (Unprocessable Content)

|  | (anonymous) | @ | 8867-2a402ca51e72eef0.js:7 |
| -- | -- | -- | -- |
|  | \_request | @ | page-a3a49037abeedf8a.js:1 |
|  | **await in \_request** |  |  |
|  | updateStoreProfile | @ | page-a3a49037abeedf8a.js:1 |
|  | g | @ | page-a3a49037abeedf8a.js:1 |
|  | a\_ | @ | fd9d1056-828c50f82cd2b0be.js:1 |
|  | aO | @ | fd9d1056-828c50f82cd2b0be.js:1 |
|  | (anonymous) | @ | fd9d1056-828c50f82cd2b0be.js:1 |
|  | sF | @ | fd9d1056-828c50f82cd2b0be.js:1 |
|  | sM | @ | fd9d1056-828c50f82cd2b0be.js:1 |
|  | (anonymous) | @ | fd9d1056-828c50f82cd2b0be.js:1 |
|  | o4 | @ | fd9d1056-828c50f82cd2b0be.js:1 |
|  | iV | @ | fd9d1056-828c50f82cd2b0be.js:1 |
|  | sU | @ | fd9d1056-828c50f82cd2b0be.js:1 |
|  | uO | @ | fd9d1056-828c50f82cd2b0be.js:1 |
|  | uM | @ | fd9d1056-828c50f82cd2b0be.js:1 |
|  | r | @ | 8867-2a402ca51e72eef0.js:5 |

8867-2a402ca51e72eef0.js:19 POST /store/profile returned non-OK response:

1. *Response {type: 'cors', url: '*[*https://dev-server.agpt.co/api/store/profile*](https://dev-server.agpt.co/api/store/profile)*', redirected: false, status: 422, ok: false, …}*
    1. body: (...)
    2. bodyUsed: true
    3. headers: Headers {}
    4. ok: false
    5. redirected: false
    6. status: 422
    7. statusText: ""
    8. type: "cors"
    9. url: "[https://dev-server.agpt.co/api/store/profile](https://dev-server.agpt.co/api/store/profile)"
   10. \[\[Prototype\]\]: Response

8867-2a402ca51e72eef0.js:19 Error updating profile: Error: \[object Object\] at s.\_request (page-a3a49037abeedf8a.js:1:16805) at async g (page-a3a49037abeedf8a.js:1:3091)

|  | (anonymous) | @ | 8867-2a402ca51e72eef0.js:19 |  |
| -- | -- | -- | -- | -- |
|  | window.console.error | @ | 8867-2a402ca51e72eef0.js:1 |  |
|  | g | @ | page-a3a49037abeedf8a.js:1 |  |
|  | **await in g** |  |  |  |
|  | a\_ | @ | fd9d1056-828c50f82cd2b0be.js:1 |  |
|  | aO | @ | fd9d1056-828c50f82cd2b0be.js:1 |  |
|  | (anonymous) | @ | fd9d1056-828c50f82cd2b0be.js:1 |  |
|  | sF | @ | fd9d1056-828c50f82cd2b0be.js:1 |  |
|  | sM | @ | fd9d1056-828c50f82cd2b0be.js:1 |  |
|  | (anonymous) | @ | fd9d1056-828c50f82cd2b0be.js:1 |  |
|  | o4 | @ | fd9d1056-828c50f82cd2b0be.js:1 |  |
|  | iV | @ | fd9d1056-828c50f82cd2b0be.js:1 |  |
|  | sU | @ | fd9d1056-828c50f82cd2b0be.js:1 |  |
|  | uO | @ | fd9d1056-828c50f82cd2b0be.js:1 |  |
|  | uM | @ | fd9d1056-828c50f82cd2b0be.js:1 |  |
|  | r | @ | 8867-2a402ca51e72eef0.js:5 |  |
|  | *Show 1 more frame* |  |  |  |

Server logs
{

"textPayload": "INFO: 35.191.15.208:49944 - "POST /api/store/profile HTTP/1.1" 422 Unprocessable Entity",

"insertId": "8lno1ooaja8ec2jy",

"resource": {

```
"type": "k8s_container",

"labels": {

  "pod_name": "autogpt-server-d48bf5c54-nrt29",

  "namespace_name": "dev-agpt",

  "container_name": "autogpt-server",

  "project_id": "agpt-dev",

  "location": "us-central1-a",

  "cluster_name": "dev-gke-cluster"

}
```

},

"timestamp": "2024-12-18T19:09:24.289203308Z",

"severity": "INFO",

"labels": {

```
"k8s-pod/app_kubernetes_io/version": "1.0.0",

"compute.googleapis.com/resource_name": "gke-dev-gke-cluster-dev-main-pool-683cc602-jv75",

"k8s-pod/pod-template-hash": "d48bf5c54",

"k8s-pod/app_kubernetes_io/name": "autogpt-server",

"k8s-pod/app_kubernetes_io/managed-by": "Helm",

"k8s-pod/helm_sh/chart": "autogpt-server-0.1.0",

"k8s-pod/app_kubernetes_io/instance": "autogpt-server"
```

},

"logName": "projects/agpt-dev/logs/stdout",

"receiveTimestamp": "2024-12-18T19:09:28.614479101Z"

}

[console.cloud.google.com](https://console.cloud.google.com/logs/query;cursorTimestamp=2024-12-18T19:09:23.961898854Z;endTime=2024-12-18T20:08:53.219Z;query=timestamp%3D%222024-12-18T19:09:23.961898854Z%22%0AinsertId%3D%22hg3bbs6yyv0bgw48%22;startTime=2024-12-18T17:17:33.296Z?project=agpt-dev)

**Comment by Bentlybro** [comment]
{

"detail": \[

```
{

  "type": "missing",

  "loc": [

    "body",

    "is_featured"

  ],

  "msg": "Field required",

  "input": {

    "name": "No Profile Data",

    "username": "bright-owl_7133",

    "description": "No Profile Data",

    "links": [],

    "avatar_url": ""

  }

}
```

\]

}

<img src="https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/b8b2cd42-203e-4ae5-8d10-035262a8d6db/63c6e388-9c93-45f6-9055-b59fb7a860eb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi9iOGIyY2Q0Mi0yMDNlLTRhZTUtOGQxMC0wMzUyNjJhOGQ2ZGIvNjNjNmUzODgtOWM5My00NWY2LTkwNTUtYjU5ZmI3YTg2MGViIiwiaWF0IjoxNzM0NTUwNTIxLCJleHAiOjMzMzA1MTEwNTIxfQ.1HaHmgmr7EcQyvLZmuXVjYpwTvd0C99joUE9IvA0p1E " alt="image.png" width="1804" data-linear-height="887" />

**Comment by ntindle** [comment]
class Profile(pydantic.BaseModel):

```
name: str

username: str

description: str

links: list[str]

avatar_url: str

is_featured: bool
```

---

@router.post(

```
"/profile",

tags=["store", "private"],

dependencies=[fastapi.Depends(autogpt_libs.auth.middleware.auth_middleware)],
```

)

async def update_or_create_profile(

```
profile: backend.server.v2.store.model.Profile,

user_id: typing.Annotated[

    str, fastapi.Depends(autogpt_libs.auth.depends.get_user_id)

],
```

) -> backend.server.v2.store.model.CreatorDetails:

```
"""

Update the store profile for the authenticated user.

Args:

    profile (Profile): The updated profile details

    user_id (str): ID of the authenticated user

Returns:

    CreatorDetails: The updated profile

Raises:

    HTTPException: If there is an error updating the profile

"""

try:

    updated_profile = await backend.server.v2.store.db.update_or_create_profile(

        user_id=user_id, profile=profile

    )

    return updated_profile

except Exception:

    logger.exception("Exception occurred whilst updating profile")

    raise
```

---

This allows users to make themselves featured

**Comment by ntindle** [comment]
related #9061
