### ISSUE TITLE
Uploading to store selects two agents

### ISSUE THREAD

**Issue by aarushik93** [Significant-Gravitas/AutoGPT#9059]
[Screen Recording 2024-12-18 at 7.29.22 PM.mov](https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/f3266581-a08c-4d4e-a59a-fd49d053e345/15035d86-ea0d-4c90-b539-710ac6650bd7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi9mMzI2NjU4MS1hMDhjLTRkNGUtYTU5YS1mZDQ5ZDA1M2UzNDUvMTUwMzVkODYtZWEwZC00YzkwLWI1MzktNzEwYWM2NjUwYmQ3IiwiaWF0IjoxNzM0NTUwMzgwLCJleHAiOjMzMzA1MTEwMzgwfQ.99s6r2OCUo80t46xniuiLQgVVuuPrVNwWm0XeJwRs-k)

**Comment by chintanpuggalok** [comment]
Let me try to replicate this.
