### ISSUE TITLE
Marketplace - Profile description text doesn't render new-lines

### ISSUE THREAD

**Issue by Torantulino** [Significant-Gravitas/AutoGPT#9086]
<img src="https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/484659e5-29b1-4748-a9da-a46f73d3cc58/8e111859-ba25-4ba0-ac2f-c2fddec620ec?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi80ODQ2NTllNS0yOWIxLTQ3NDgtYTlkYS1hNDZmNzNkM2NjNTgvOGUxMTE4NTktYmEyNS00YmEwLWFjMmYtYzJmZGRlYzYyMGVjIiwiaWF0IjoxNzM0NjIxNjM5LCJleHAiOjMzMzA1MTgxNjM5fQ.iIEUDccEycfQz1JwR-aF-J1DK3wJTTIwS8gbZFRaIeE " alt="image.png" width="946" data-linear-height="330" />

<img src="https://uploads.linear.app/a47946b5-12cd-4b3d-8822-df04c855879f/cf2f5730-ea3e-4351-a559-764aff49bdd6/b22fca74-cff7-4b72-a53f-515ad917649e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E0Nzk0NmI1LTEyY2QtNGIzZC04ODIyLWRmMDRjODU1ODc5Zi9jZjJmNTczMC1lYTNlLTQzNTEtYTU1OS03NjRhZmY0OWJkZDYvYjIyZmNhNzQtY2ZmNy00YjcyLWE1M2YtNTE1YWQ5MTc2NDllIiwiaWF0IjoxNzM0NjIxNjM5LCJleHAiOjMzMzA1MTgxNjM5fQ.H26WbCg8LC3iWyHXheI3JLmuU-3aI6Pq8EONrumbJB8 " alt="image.png" width="1120" data-linear-height="353" />

**Comment by Swiftyos** [comment]
Sure thing, thank you @ethethanlee
