### ISSUE TITLE
Agent Input Values Shouldn't Export or Save

### ISSUE THREAD

**Issue by Torantulino** [Significant-Gravitas/AutoGPT#9139]
Currently the last value that you used in an Agent Input Block exports into the Agent JSON. This means that the Agent file is polluted with the last input the user tested their Agent with.<br><br>*This input value also saves to the database.<br>*<br>Steps to reproduce:

1. Make an Agent with an Agent Input Block.
2. Run the Agent with a recognisable input value
3. Go to the Library Page and Export the Agent to a JSON file.
4. Open the JSON File and observe your unique input has been exported with the file.

---

### Intended Behaviour:

The value field on Agent inputs should be empty when saving or exporting Agents.

**Comment by Torantulino** [comment]
Just been plagued by this issue for a while thinking it was some sort of deeper bug. This isn't necessarily a bug but it is a bad and unintended user experience.

**Comment by Swiftyos** [comment]
Done and released
